- name: CorporateGrey (Flat)
  author: malamanteau
  url: https://github.com/malamanteau
  config:
    PopupRounding: 3
    WindowPadding: [4,4]
    FramePadding: [6,4]
    ItemSpacing: [6,2]
    ScrollbarSize: 18
    WindowBorderSize: 1
    ChildBorderSize: 1
    PopupBorderSize: 1
    FrameBorderSize: 0
    WindowRounding: 3
    ChildRounding: 3
    FrameRounding: 3
    ScrollbarRounding: 2
    GrabRounding: 3
    TabBorderSize: 0
    TabRounding: 3
  colors:
    Text: [1.00, 1.00, 1.00, 1.00]
    TextDisabled: [0.40, 0.40, 0.40, 1.00]
    ChildBg: [0.25, 0.25, 0.25, 1.00]
    WindowBg: [0.25, 0.25, 0.25, 1.00]
    PopupBg: [0.25, 0.25, 0.25, 1.00]
    Border: [0.12, 0.12, 0.12, 0.71]
    BorderShadow: [1.00, 1.00, 1.00, 0.06]
    FrameBg: [0.42, 0.42, 0.42, 0.54]
    FrameBgHovered: [0.42, 0.42, 0.42, 0.40]
    FrameBgActive: [0.56, 0.56, 0.56, 0.67]
    TitleBg: [0.19, 0.19, 0.19, 1.00]
    TitleBgActive: [0.22, 0.22, 0.22, 1.00]
    TitleBgCollapsed: [0.17, 0.17, 0.17, 0.90]
    MenuBarBg: [0.335, 0.335, 0.335, 1.000]
    ScrollbarBg: [0.24, 0.24, 0.24, 0.53]
    ScrollbarGrab: [0.41, 0.41, 0.41, 1.00]
    ScrollbarGrabHovered: [0.52, 0.52, 0.52, 1.00]
    ScrollbarGrabActive: [0.76, 0.76, 0.76, 1.00]
    CheckMark: [0.65, 0.65, 0.65, 1.00]
    SliderGrab: [0.52, 0.52, 0.52, 1.00]
    SliderGrabActive: [0.64, 0.64, 0.64, 1.00]
    Button: [0.54, 0.54, 0.54, 0.35]
    ButtonHovered: [0.52, 0.52, 0.52, 0.59]
    ButtonActive: [0.76, 0.76, 0.76, 1.00]
    Header: [0.38, 0.38, 0.38, 1.00]
    HeaderHovered: [0.47, 0.47, 0.47, 1.00]
    HeaderActive: [0.76, 0.76, 0.76, 0.77]
    Separator: [0.000, 0.000, 0.000, 0.137]
    SeparatorHovered: [0.700, 0.671, 0.600, 0.290]
    SeparatorActive: [0.702, 0.671, 0.600, 0.674]
    ResizeGrip: [0.26, 0.59, 0.98, 0.25]
    ResizeGripHovered: [0.26, 0.59, 0.98, 0.67]
    ResizeGripActive: [0.26, 0.59, 0.98, 0.95]
    PlotLines: [0.61, 0.61, 0.61, 1.00]
    PlotLinesHovered: [1.00, 0.43, 0.35, 1.00]
    PlotHistogram: [0.90, 0.70, 0.00, 1.00]
    PlotHistogramHovered: [1.00, 0.60, 0.00, 1.00]
    TextSelectedBg: [0.73, 0.73, 0.73, 0.35]
    ModalWindowDimBg: [0.80, 0.80, 0.80, 0.35]
    DragDropTarget: [1.00, 1.00, 0.00, 0.90]
    NavHighlight: [0.26, 0.59, 0.98, 1.00]
    NavWindowingHighlight: [1.00, 1.00, 1.00, 0.70]
    NavWindowingDimBg: [0.80, 0.80, 0.80, 0.20]
    DockingEmptyBg: [0.38, 0.38, 0.38, 1.00]
    Tab: [0.25, 0.25, 0.25, 1.00]
    TabHovered: [0.40, 0.40, 0.40, 1.00]
    TabActive: [0.33, 0.33, 0.33, 1.00]
    TabUnfocused: [0.25, 0.25, 0.25, 1.00]
    TabUnfocusedActive: [0.33, 0.33, 0.33, 1.00]
    DockingPreview: [0.85, 0.85, 0.85, 0.28]

- name: CorporateGrey (3D)
  author: malamanteau
  url: https://github.com/malamanteau
  config:
    PopupRounding: 3
    WindowPadding: [4,4]
    FramePadding: [6,4]
    ItemSpacing: [6,2]
    ScrollbarSize: 18
    WindowBorderSize: 1
    ChildBorderSize: 1
    PopupBorderSize: 1
    FrameBorderSize: 1
    WindowRounding: 3
    ChildRounding: 3
    FrameRounding: 3
    ScrollbarRounding: 2
    GrabRounding: 3
    TabBorderSize: 1
    TabRounding: 3
  colors:
    Text: [1.00, 1.00, 1.00, 1.00]
    TextDisabled: [0.40, 0.40, 0.40, 1.00]
    ChildBg: [0.25, 0.25, 0.25, 1.00]
    WindowBg: [0.25, 0.25, 0.25, 1.00]
    PopupBg: [0.25, 0.25, 0.25, 1.00]
    Border: [0.12, 0.12, 0.12, 0.71]
    BorderShadow: [1.00, 1.00, 1.00, 0.06]
    FrameBg: [0.42, 0.42, 0.42, 0.54]
    FrameBgHovered: [0.42, 0.42, 0.42, 0.40]
    FrameBgActive: [0.56, 0.56, 0.56, 0.67]
    TitleBg: [0.19, 0.19, 0.19, 1.00]
    TitleBgActive: [0.22, 0.22, 0.22, 1.00]
    TitleBgCollapsed: [0.17, 0.17, 0.17, 0.90]
    MenuBarBg: [0.335, 0.335, 0.335, 1.000]
    ScrollbarBg: [0.24, 0.24, 0.24, 0.53]
    ScrollbarGrab: [0.41, 0.41, 0.41, 1.00]
    ScrollbarGrabHovered: [0.52, 0.52, 0.52, 1.00]
    ScrollbarGrabActive: [0.76, 0.76, 0.76, 1.00]
    CheckMark: [0.65, 0.65, 0.65, 1.00]
    SliderGrab: [0.52, 0.52, 0.52, 1.00]
    SliderGrabActive: [0.64, 0.64, 0.64, 1.00]
    Button: [0.54, 0.54, 0.54, 0.35]
    ButtonHovered: [0.52, 0.52, 0.52, 0.59]
    ButtonActive: [0.76, 0.76, 0.76, 1.00]
    Header: [0.38, 0.38, 0.38, 1.00]
    HeaderHovered: [0.47, 0.47, 0.47, 1.00]
    HeaderActive: [0.76, 0.76, 0.76, 0.77]
    Separator: [0.000, 0.000, 0.000, 0.137]
    SeparatorHovered: [0.700, 0.671, 0.600, 0.290]
    SeparatorActive: [0.702, 0.671, 0.600, 0.674]
    ResizeGrip: [0.26, 0.59, 0.98, 0.25]
    ResizeGripHovered: [0.26, 0.59, 0.98, 0.67]
    ResizeGripActive: [0.26, 0.59, 0.98, 0.95]
    PlotLines: [0.61, 0.61, 0.61, 1.00]
    PlotLinesHovered: [1.00, 0.43, 0.35, 1.00]
    PlotHistogram: [0.90, 0.70, 0.00, 1.00]
    PlotHistogramHovered: [1.00, 0.60, 0.00, 1.00]
    TextSelectedBg: [0.73, 0.73, 0.73, 0.35]
    ModalWindowDimBg: [0.80, 0.80, 0.80, 0.35]
    DragDropTarget: [1.00, 1.00, 0.00, 0.90]
    NavHighlight: [0.26, 0.59, 0.98, 1.00]
    NavWindowingHighlight: [1.00, 1.00, 1.00, 0.70]
    NavWindowingDimBg: [0.80, 0.80, 0.80, 0.20]
    DockingEmptyBg: [0.38, 0.38, 0.38, 1.00]
    Tab: [0.25, 0.25, 0.25, 1.00]
    TabHovered: [0.40, 0.40, 0.40, 1.00]
    TabActive: [0.33, 0.33, 0.33, 1.00]
    TabUnfocused: [0.25, 0.25, 0.25, 1.00]
    TabUnfocusedActive: [0.33, 0.33, 0.33, 1.00]
    DockingPreview: [0.85, 0.85, 0.85, 0.28]
- name: Decay 1998
  author: metasprite
  url: https://github.com/metasprite
  config:
    FrameBorderSize: 1
    WindowRounding: 0
    ChildRounding: 0
    FrameRounding: 0
    PopupRounding: 0
    ScrollbarRounding: 0
    GrabRounding: 0
    TabRounding: 0
  colors:
    Text: [1.00, 1.00, 1.00, 1.00]
    TextDisabled: [0.50, 0.50, 0.50, 1.00]
    WindowBg: [0.29, 0.34, 0.26, 1.00]
    ChildBg: [0.29, 0.34, 0.26, 1.00]
    PopupBg: [0.24, 0.27, 0.20, 1.00]
    Border: [0.54, 0.57, 0.51, 0.50]
    BorderShadow: [0.14, 0.16, 0.11, 0.52]
    FrameBg: [0.24, 0.27, 0.20, 1.00]
    FrameBgHovered: [0.27, 0.30, 0.23, 1.00]
    FrameBgActive: [0.30, 0.34, 0.26, 1.00]
    TitleBg: [0.24, 0.27, 0.20, 1.00]
    TitleBgActive: [0.29, 0.34, 0.26, 1.00]
    TitleBgCollapsed: [0.00, 0.00, 0.00, 0.51]
    MenuBarBg: [0.24, 0.27, 0.20, 1.00]
    ScrollbarBg: [0.35, 0.42, 0.31, 1.00]
    ScrollbarGrab: [0.28, 0.32, 0.24, 1.00]
    ScrollbarGrabHovered: [0.25, 0.30, 0.22, 1.00]
    ScrollbarGrabActive: [0.23, 0.27, 0.21, 1.00]
    CheckMark: [0.59, 0.54, 0.18, 1.00]
    SliderGrab: [0.35, 0.42, 0.31, 1.00]
    SliderGrabActive: [0.54, 0.57, 0.51, 0.50]
    Button: [0.29, 0.34, 0.26, 0.40]
    ButtonHovered: [0.35, 0.42, 0.31, 1.00]
    ButtonActive: [0.54, 0.57, 0.51, 0.50]
    Header: [0.35, 0.42, 0.31, 1.00]
    HeaderHovered: [0.35, 0.42, 0.31, 0.6]
    HeaderActive: [0.54, 0.57, 0.51, 0.50]
    Separator: [0.14, 0.16, 0.11, 1.00]
    SeparatorHovered: [0.54, 0.57, 0.51, 1.00]
    SeparatorActive: [0.59, 0.54, 0.18, 1.00]
    ResizeGrip: [0.19, 0.23, 0.18, 0.00]
    ResizeGripHovered: [0.54, 0.57, 0.51, 1.00]
    ResizeGripActive: [0.59, 0.54, 0.18, 1.00]
    Tab: [0.35, 0.42, 0.31, 1.00]
    TabHovered: [0.54, 0.57, 0.51, 0.78]
    TabActive: [0.59, 0.54, 0.18, 1.00]
    TabUnfocused: [0.24, 0.27, 0.20, 1.00]
    TabUnfocusedActive: [0.35, 0.42, 0.31, 1.00]
    DockingPreview: [0.59, 0.54, 0.18, 1.00]
    DockingEmptyBg: [0.20, 0.20, 0.20, 1.00]
    PlotLines: [0.61, 0.61, 0.61, 1.00]
    PlotLinesHovered: [0.59, 0.54, 0.18, 1.00]
    PlotHistogram: [1.00, 0.78, 0.28, 1.00]
    PlotHistogramHovered: [1.00, 0.60, 0.00, 1.00]
    TextSelectedBg: [0.59, 0.54, 0.18, 1.00]
    DragDropTarget: [0.73, 0.67, 0.24, 1.00]
    NavHighlight: [0.59, 0.54, 0.18, 1.00]
    NavWindowingHighlight: [1.00, 1.00, 1.00, 0.70]
    NavWindowingDimBg: [0.80, 0.80, 0.80, 0.20]
    ModalWindowDimBg: [0.80, 0.80, 0.80, 0.35]
  