#pragma once

#include <stdint.h>

typedef uint32_t cuuint32_t;
typedef uint64_t cuuint64_t;
typedef unsigned long long CUdeviceptr_v2;
typedef CUdeviceptr_v2 CUdeviceptr;
typedef int CUdevice_v1;
typedef CUdevice_v1 CUdevice;
typedef struct CUctx_st* CUcontext;
typedef struct CUmod_st* CUmodule;
typedef struct CUfunc_st* CUfunction;
typedef struct CUlib_st* CUlibrary;
typedef struct CUkern_st* CUkernel;
typedef struct CUarray_st* CUarray;
typedef struct CUmipmappedArray_st* CUmipmappedArray;
typedef struct CUtexref_st* CUtexref;
typedef struct CUsurfref_st* CUsurfref;
typedef struct CUevent_st* CUevent;
typedef struct CUstream_st* CUstream;
typedef struct CUgraphicsResource_st* CUgraphicsResource;
typedef unsigned long long CUtexObject_v1;
typedef CUtexObject_v1 CUtexObject;
typedef unsigned long long CUsurfObject_v1;
typedef CUsurfObject_v1 CUsurfObject;
typedef struct CUextMemory_st* CUexternalMemory;
typedef struct CUextSemaphore_st* CUexternalSemaphore;
typedef struct CUgraph_st* CUgraph;
typedef struct CUgraphNode_st* CUgraphNode;
typedef struct CUgraphExec_st* CUgraphExec;
typedef struct CUmemPoolHandle_st* CUmemoryPool;
typedef struct CUuserObject_st* CUuserObject;
typedef cuuint64_t CUgraphConditionalHandle;
typedef struct CUgraphDeviceUpdatableNode_st* CUgraphDeviceNode;
typedef struct CUasyncCallbackEntry_st* CUasyncCallbackHandle;
typedef struct CUgreenCtx_st* CUgreenCtx;
typedef struct CUuuid_st {
	char bytes[16];
} CUuuid;
typedef struct CUmemFabricHandle_st {
	unsigned char data[64];
} CUmemFabricHandle_v1;
typedef CUmemFabricHandle_v1 CUmemFabricHandle;
typedef struct CUipcEventHandle_st {
	char reserved[64];
} CUipcEventHandle_v1;
typedef CUipcEventHandle_v1 CUipcEventHandle;
typedef struct CUipcMemHandle_st {
	char reserved[64];
} CUipcMemHandle_v1;
typedef CUipcMemHandle_v1 CUipcMemHandle;
typedef enum CUipcMem_flags_enum {
	CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 0x1
} CUipcMem_flags;
typedef enum CUmemAttach_flags_enum {
	CU_MEM_ATTACH_GLOBAL = 0x1,
	CU_MEM_ATTACH_HOST = 0x2,
	CU_MEM_ATTACH_SINGLE = 0x4
} CUmemAttach_flags;
typedef enum CUctx_flags_enum {
	CU_CTX_SCHED_AUTO = 0x00,
	CU_CTX_SCHED_SPIN = 0x01,
	CU_CTX_SCHED_YIELD = 0x02,
	CU_CTX_SCHED_BLOCKING_SYNC = 0x04,
	CU_CTX_BLOCKING_SYNC = 0x04,
	CU_CTX_SCHED_MASK = 0x07,
	CU_CTX_MAP_HOST = 0x08,
	CU_CTX_LMEM_RESIZE_TO_MAX = 0x10,
	CU_CTX_COREDUMP_ENABLE = 0x20,
	CU_CTX_USER_COREDUMP_ENABLE = 0x40,
	CU_CTX_SYNC_MEMOPS = 0x80,
	CU_CTX_FLAGS_MASK = 0xFF
} CUctx_flags;
typedef enum CUevent_sched_flags_enum {
	CU_EVENT_SCHED_AUTO = 0x00,
	CU_EVENT_SCHED_SPIN = 0x01,
	CU_EVENT_SCHED_YIELD = 0x02,
	CU_EVENT_SCHED_BLOCKING_SYNC = 0x04
} CUevent_sched_flags;
typedef enum cl_event_flags_enum {
	NVCL_EVENT_SCHED_AUTO = 0x00,
	NVCL_EVENT_SCHED_SPIN = 0x01,
	NVCL_EVENT_SCHED_YIELD = 0x02,
	NVCL_EVENT_SCHED_BLOCKING_SYNC = 0x04
} cl_event_flags;
typedef enum cl_context_flags_enum {
	NVCL_CTX_SCHED_AUTO = 0x00,
	NVCL_CTX_SCHED_SPIN = 0x01,
	NVCL_CTX_SCHED_YIELD = 0x02,
	NVCL_CTX_SCHED_BLOCKING_SYNC = 0x04
} cl_context_flags;
typedef enum CUstream_flags_enum {
	CU_STREAM_DEFAULT = 0x0,
	CU_STREAM_NON_BLOCKING = 0x1
} CUstream_flags;
typedef enum CUevent_flags_enum {
	CU_EVENT_DEFAULT = 0x0,
	CU_EVENT_BLOCKING_SYNC = 0x1,
	CU_EVENT_DISABLE_TIMING = 0x2,
	CU_EVENT_INTERPROCESS = 0x4
} CUevent_flags;
typedef enum CUevent_record_flags_enum {
	CU_EVENT_RECORD_DEFAULT = 0x0,
	CU_EVENT_RECORD_EXTERNAL = 0x1
} CUevent_record_flags;
typedef enum CUevent_wait_flags_enum {
	CU_EVENT_WAIT_DEFAULT = 0x0,
	CU_EVENT_WAIT_EXTERNAL = 0x1
} CUevent_wait_flags;
typedef enum CUatomicOperation_enum {
	CU_ATOMIC_OPERATION_INTEGER_ADD = 0,
	CU_ATOMIC_OPERATION_INTEGER_MIN = 1,
	CU_ATOMIC_OPERATION_INTEGER_MAX = 2,
	CU_ATOMIC_OPERATION_INTEGER_INCREMENT = 3,
	CU_ATOMIC_OPERATION_INTEGER_DECREMENT = 4,
	CU_ATOMIC_OPERATION_AND = 5,
	CU_ATOMIC_OPERATION_OR = 6,
	CU_ATOMIC_OPERATION_XOR = 7,
	CU_ATOMIC_OPERATION_EXCHANGE = 8,
	CU_ATOMIC_OPERATION_CAS = 9,
	CU_ATOMIC_OPERATION_FLOAT_ADD = 10,
	CU_ATOMIC_OPERATION_FLOAT_MIN = 11,
	CU_ATOMIC_OPERATION_FLOAT_MAX = 12,
	CU_ATOMIC_OPERATION_MAX
} CUatomicOperation;
typedef enum CUatomicOperationCapability_enum {
	CU_ATOMIC_CAPABILITY_SIGNED = 1u << 0,
	CU_ATOMIC_CAPABILITY_UNSIGNED = 1u << 1,
	CU_ATOMIC_CAPABILITY_REDUCTION = 1u << 2,
	CU_ATOMIC_CAPABILITY_SCALAR_32 = 1u << 3,
	CU_ATOMIC_CAPABILITY_SCALAR_64 = 1u << 4,
	CU_ATOMIC_CAPABILITY_SCALAR_128 = 1u << 5,
	CU_ATOMIC_CAPABILITY_VECTOR_32x4 = 1u << 6
} CUatomicOperationCapability;
typedef enum CUstreamWaitValue_flags_enum {
	CU_STREAM_WAIT_VALUE_GEQ = 0x0,
	CU_STREAM_WAIT_VALUE_EQ = 0x1,
	CU_STREAM_WAIT_VALUE_AND = 0x2,
	CU_STREAM_WAIT_VALUE_NOR = 0x3,
	CU_STREAM_WAIT_VALUE_FLUSH = 1 << 30
} CUstreamWaitValue_flags;
typedef enum CUstreamWriteValue_flags_enum {
	CU_STREAM_WRITE_VALUE_DEFAULT = 0x0,
	CU_STREAM_WRITE_VALUE_NO_MEMORY_BARRIER = 0x1
} CUstreamWriteValue_flags;
typedef enum CUstreamBatchMemOpType_enum {
	CU_STREAM_MEM_OP_WAIT_VALUE_32 = 1,
	CU_STREAM_MEM_OP_WRITE_VALUE_32 = 2,
	CU_STREAM_MEM_OP_WAIT_VALUE_64 = 4,
	CU_STREAM_MEM_OP_WRITE_VALUE_64 = 5,
	CU_STREAM_MEM_OP_BARRIER = 6,
	CU_STREAM_MEM_OP_ATOMIC_REDUCTION = 8,
	CU_STREAM_MEM_OP_FLUSH_REMOTE_WRITES = 3
} CUstreamBatchMemOpType;
typedef enum CUstreamMemoryBarrier_flags_enum {
	CU_STREAM_MEMORY_BARRIER_TYPE_SYS = 0x0,
	CU_STREAM_MEMORY_BARRIER_TYPE_GPU = 0x1
} CUstreamMemoryBarrier_flags;
typedef enum CUstreamAtomicReductionOpType_enum {
	CU_STREAM_ATOMIC_REDUCTION_OP_OR = CU_ATOMIC_OPERATION_OR,
	CU_STREAM_ATOMIC_REDUCTION_OP_AND = CU_ATOMIC_OPERATION_AND,
	CU_STREAM_ATOMIC_REDUCTION_OP_ADD = CU_ATOMIC_OPERATION_INTEGER_ADD
} CUstreamAtomicReductionOpType;
typedef enum CUstreamAtomicReductionDataType_enum {
	CU_STREAM_ATOMIC_REDUCTION_UNSIGNED_32 = CU_ATOMIC_CAPABILITY_UNSIGNED | CU_ATOMIC_CAPABILITY_SCALAR_32 | CU_ATOMIC_CAPABILITY_REDUCTION,
	CU_STREAM_ATOMIC_REDUCTION_UNSIGNED_64 = CU_ATOMIC_CAPABILITY_UNSIGNED | CU_ATOMIC_CAPABILITY_SCALAR_64 | CU_ATOMIC_CAPABILITY_REDUCTION
} CUstreamAtomicReductionDataType;
typedef union CUstreamBatchMemOpParams_union {
	CUstreamBatchMemOpType operation;
	struct CUstreamMemOpWaitValueParams_st {
		CUstreamBatchMemOpType operation;
		CUdeviceptr address;
		union {
			cuuint32_t value;
			cuuint64_t value64;
		};
		unsigned int flags;
		CUdeviceptr alias;
	} waitValue;
	struct CUstreamMemOpWriteValueParams_st {
		CUstreamBatchMemOpType operation;
		CUdeviceptr address;
		union {
			cuuint32_t value;
			cuuint64_t value64;
		};
		unsigned int flags;
		CUdeviceptr alias;
	} writeValue;
	struct CUstreamMemOpFlushRemoteWritesParams_st {
		CUstreamBatchMemOpType operation;
		unsigned int flags;
	} flushRemoteWrites;
	struct CUstreamMemOpMemoryBarrierParams_st {
		CUstreamBatchMemOpType operation;
		unsigned int flags;
	} memoryBarrier;
	struct CUstreamMemOpAtomicReductionParams_st {
		CUstreamBatchMemOpType operation;
		unsigned int flags;
		CUstreamAtomicReductionOpType reductionOp;
		CUstreamAtomicReductionDataType dataType;
		CUdeviceptr address;
		cuuint64_t value;
		CUdeviceptr alias;
	} atomicReduction;
	cuuint64_t pad[6];
} CUstreamBatchMemOpParams_v1;
typedef CUstreamBatchMemOpParams_v1 CUstreamBatchMemOpParams;
typedef struct CUDA_BATCH_MEM_OP_NODE_PARAMS_v1_st {
	CUcontext ctx;
	unsigned int count;
	CUstreamBatchMemOpParams* paramArray;
	unsigned int flags;
} CUDA_BATCH_MEM_OP_NODE_PARAMS_v1;
typedef CUDA_BATCH_MEM_OP_NODE_PARAMS_v1 CUDA_BATCH_MEM_OP_NODE_PARAMS;
typedef struct CUDA_BATCH_MEM_OP_NODE_PARAMS_v2_st {
	CUcontext ctx;
	unsigned int count;
	CUstreamBatchMemOpParams* paramArray;
	unsigned int flags;
} CUDA_BATCH_MEM_OP_NODE_PARAMS_v2;
typedef enum CUoccupancy_flags_enum {
	CU_OCCUPANCY_DEFAULT = 0x0,
	CU_OCCUPANCY_DISABLE_CACHING_OVERRIDE = 0x1
} CUoccupancy_flags;
typedef enum CUstreamUpdateCaptureDependencies_flags_enum {
	CU_STREAM_ADD_CAPTURE_DEPENDENCIES = 0x0,
	CU_STREAM_SET_CAPTURE_DEPENDENCIES = 0x1
} CUstreamUpdateCaptureDependencies_flags;
typedef enum CUasyncNotificationType_enum {
	CU_ASYNC_NOTIFICATION_TYPE_OVER_BUDGET = 0x1
} CUasyncNotificationType;
typedef struct CUasyncNotificationInfo_st {
	CUasyncNotificationType type;
	union {
		struct {
			unsigned long long bytesOverBudget;
		} overBudget;
	} info;
} CUasyncNotificationInfo;
typedef void (*CUasyncCallback)(CUasyncNotificationInfo* info, void* userData, CUasyncCallbackHandle callback);
typedef enum CUarray_format_enum {
	CU_AD_FORMAT_UNSIGNED_INT8 = 0x01,
	CU_AD_FORMAT_UNSIGNED_INT16 = 0x02,
	CU_AD_FORMAT_UNSIGNED_INT32 = 0x03,
	CU_AD_FORMAT_SIGNED_INT8 = 0x08,
	CU_AD_FORMAT_SIGNED_INT16 = 0x09,
	CU_AD_FORMAT_SIGNED_INT32 = 0x0a,
	CU_AD_FORMAT_HALF = 0x10,
	CU_AD_FORMAT_FLOAT = 0x20,
	CU_AD_FORMAT_NV12 = 0xb0,
	CU_AD_FORMAT_UNORM_INT8X1 = 0xc0,
	CU_AD_FORMAT_UNORM_INT8X2 = 0xc1,
	CU_AD_FORMAT_UNORM_INT8X4 = 0xc2,
	CU_AD_FORMAT_UNORM_INT16X1 = 0xc3,
	CU_AD_FORMAT_UNORM_INT16X2 = 0xc4,
	CU_AD_FORMAT_UNORM_INT16X4 = 0xc5,
	CU_AD_FORMAT_SNORM_INT8X1 = 0xc6,
	CU_AD_FORMAT_SNORM_INT8X2 = 0xc7,
	CU_AD_FORMAT_SNORM_INT8X4 = 0xc8,
	CU_AD_FORMAT_SNORM_INT16X1 = 0xc9,
	CU_AD_FORMAT_SNORM_INT16X2 = 0xca,
	CU_AD_FORMAT_SNORM_INT16X4 = 0xcb,
	CU_AD_FORMAT_BC1_UNORM = 0x91,
	CU_AD_FORMAT_BC1_UNORM_SRGB = 0x92,
	CU_AD_FORMAT_BC2_UNORM = 0x93,
	CU_AD_FORMAT_BC2_UNORM_SRGB = 0x94,
	CU_AD_FORMAT_BC3_UNORM = 0x95,
	CU_AD_FORMAT_BC3_UNORM_SRGB = 0x96,
	CU_AD_FORMAT_BC4_UNORM = 0x97,
	CU_AD_FORMAT_BC4_SNORM = 0x98,
	CU_AD_FORMAT_BC5_UNORM = 0x99,
	CU_AD_FORMAT_BC5_SNORM = 0x9a,
	CU_AD_FORMAT_BC6H_UF16 = 0x9b,
	CU_AD_FORMAT_BC6H_SF16 = 0x9c,
	CU_AD_FORMAT_BC7_UNORM = 0x9d,
	CU_AD_FORMAT_BC7_UNORM_SRGB = 0x9e,
	CU_AD_FORMAT_P010 = 0x9f,
	CU_AD_FORMAT_P016 = 0xa1,
	CU_AD_FORMAT_NV16 = 0xa2,
	CU_AD_FORMAT_P210 = 0xa3,
	CU_AD_FORMAT_P216 = 0xa4,
	CU_AD_FORMAT_YUY2 = 0xa5,
	CU_AD_FORMAT_Y210 = 0xa6,
	CU_AD_FORMAT_Y216 = 0xa7,
	CU_AD_FORMAT_AYUV = 0xa8,
	CU_AD_FORMAT_Y410 = 0xa9,
	CU_AD_FORMAT_Y416 = 0xb1,
	CU_AD_FORMAT_Y444_PLANAR8 = 0xb2,
	CU_AD_FORMAT_Y444_PLANAR10 = 0xb3,
	CU_AD_FORMAT_YUV444_8bit_SemiPlanar = 0xb4,
	CU_AD_FORMAT_YUV444_16bit_SemiPlanar = 0xb5,
	CU_AD_FORMAT_UNORM_INT_101010_2 = 0x50,
	CU_AD_FORMAT_UINT8_PACKED_422 = 0x51,
	CU_AD_FORMAT_UINT8_PACKED_444 = 0x52,
	CU_AD_FORMAT_UINT8_SEMIPLANAR_420 = 0x53,
	CU_AD_FORMAT_UINT16_SEMIPLANAR_420 = 0x54,
	CU_AD_FORMAT_UINT8_SEMIPLANAR_422 = 0x55,
	CU_AD_FORMAT_UINT16_SEMIPLANAR_422 = 0x56,
	CU_AD_FORMAT_UINT8_SEMIPLANAR_444 = 0x57,
	CU_AD_FORMAT_UINT16_SEMIPLANAR_444 = 0x58,
	CU_AD_FORMAT_UINT8_PLANAR_420 = 0x59,
	CU_AD_FORMAT_UINT16_PLANAR_420 = 0x5a,
	CU_AD_FORMAT_UINT8_PLANAR_422 = 0x5b,
	CU_AD_FORMAT_UINT16_PLANAR_422 = 0x5c,
	CU_AD_FORMAT_UINT8_PLANAR_444 = 0x5d,
	CU_AD_FORMAT_UINT16_PLANAR_444 = 0x5e,
	CU_AD_FORMAT_MAX = 0x7FFFFFFF
} CUarray_format;
typedef enum CUaddress_mode_enum {
	CU_TR_ADDRESS_MODE_WRAP = 0,
	CU_TR_ADDRESS_MODE_CLAMP = 1,
	CU_TR_ADDRESS_MODE_MIRROR = 2,
	CU_TR_ADDRESS_MODE_BORDER = 3
} CUaddress_mode;
typedef enum CUfilter_mode_enum {
	CU_TR_FILTER_MODE_POINT = 0,
	CU_TR_FILTER_MODE_LINEAR = 1
} CUfilter_mode;
typedef enum CUdevice_attribute_enum {
	CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK = 1,
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X = 2,
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y = 3,
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z = 4,
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X = 5,
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y = 6,
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z = 7,
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK = 8,
	CU_DEVICE_ATTRIBUTE_SHARED_MEMORY_PER_BLOCK = 8,
	CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY = 9,
	CU_DEVICE_ATTRIBUTE_WARP_SIZE = 10,
	CU_DEVICE_ATTRIBUTE_MAX_PITCH = 11,
	CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK = 12,
	CU_DEVICE_ATTRIBUTE_REGISTERS_PER_BLOCK = 12,
	CU_DEVICE_ATTRIBUTE_CLOCK_RATE = 13,
	CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT = 14,
	CU_DEVICE_ATTRIBUTE_GPU_OVERLAP = 15,
	CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT = 16,
	CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT = 17,
	CU_DEVICE_ATTRIBUTE_INTEGRATED = 18,
	CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY = 19,
	CU_DEVICE_ATTRIBUTE_COMPUTE_MODE = 20,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_WIDTH = 21,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH = 22,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT = 23,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH = 24,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT = 25,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH = 26,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_WIDTH = 27,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_HEIGHT = 28,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS = 29,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_WIDTH = 27,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_HEIGHT = 28,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_NUMSLICES = 29,
	CU_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT = 30,
	CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS = 31,
	CU_DEVICE_ATTRIBUTE_ECC_ENABLED = 32,
	CU_DEVICE_ATTRIBUTE_PCI_BUS_ID = 33,
	CU_DEVICE_ATTRIBUTE_PCI_DEVICE_ID = 34,
	CU_DEVICE_ATTRIBUTE_TCC_DRIVER = 35,
	CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE = 36,
	CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH = 37,
	CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE = 38,
	CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR = 39,
	CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT = 40,
	CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING = 41,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_WIDTH = 42,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_LAYERS = 43,
	CU_DEVICE_ATTRIBUTE_CAN_TEX2D_GATHER = 44,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_WIDTH = 45,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_HEIGHT = 46,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH_ALTERNATE = 47,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT_ALTERNATE = 48,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH_ALTERNATE = 49,
	CU_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID = 50,
	CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT = 51,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_WIDTH = 52,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_WIDTH = 53,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_LAYERS = 54,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_WIDTH = 55,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_WIDTH = 56,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_HEIGHT = 57,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_WIDTH = 58,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_HEIGHT = 59,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_DEPTH = 60,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_WIDTH = 61,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_LAYERS = 62,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_WIDTH = 63,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_HEIGHT = 64,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_LAYERS = 65,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_WIDTH = 66,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_WIDTH = 67,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_LAYERS = 68,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH = 69,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH = 70,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_HEIGHT = 71,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH = 72,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_WIDTH = 73,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_HEIGHT = 74,
	CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR = 75,
	CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR = 76,
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_MIPMAPPED_WIDTH = 77,
	CU_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED = 78,
	CU_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED = 79,
	CU_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED = 80,
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR = 81,
	CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR = 82,
	CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY = 83,
	CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD = 84,
	CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID = 85,
	CU_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED = 86,
	CU_DEVICE_ATTRIBUTE_SINGLE_TO_DOUBLE_PRECISION_PERF_RATIO = 87,
	CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS = 88,
	CU_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS = 89,
	CU_DEVICE_ATTRIBUTE_COMPUTE_PREEMPTION_SUPPORTED = 90,
	CU_DEVICE_ATTRIBUTE_CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM = 91,
	CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS_V1 = 92,
	CU_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS_V1 = 93,
	CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR_V1 = 94,
	CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH = 95,
	CU_DEVICE_ATTRIBUTE_COOPERATIVE_MULTI_DEVICE_LAUNCH = 96,
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN = 97,
	CU_DEVICE_ATTRIBUTE_CAN_FLUSH_REMOTE_WRITES = 98,
	CU_DEVICE_ATTRIBUTE_HOST_REGISTER_SUPPORTED = 99,
	CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS_USES_HOST_PAGE_TABLES = 100,
	CU_DEVICE_ATTRIBUTE_DIRECT_MANAGED_MEM_ACCESS_FROM_HOST = 101,
	CU_DEVICE_ATTRIBUTE_VIRTUAL_ADDRESS_MANAGEMENT_SUPPORTED = 102,
	CU_DEVICE_ATTRIBUTE_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED = 102,
	CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_POSIX_FILE_DESCRIPTOR_SUPPORTED = 103,
	CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_WIN32_HANDLE_SUPPORTED = 104,
	CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_WIN32_KMT_HANDLE_SUPPORTED = 105,
	CU_DEVICE_ATTRIBUTE_MAX_BLOCKS_PER_MULTIPROCESSOR = 106,
	CU_DEVICE_ATTRIBUTE_GENERIC_COMPRESSION_SUPPORTED = 107,
	CU_DEVICE_ATTRIBUTE_MAX_PERSISTING_L2_CACHE_SIZE = 108,
	CU_DEVICE_ATTRIBUTE_MAX_ACCESS_POLICY_WINDOW_SIZE = 109,
	CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_WITH_CUDA_VMM_SUPPORTED = 110,
	CU_DEVICE_ATTRIBUTE_RESERVED_SHARED_MEMORY_PER_BLOCK = 111,
	CU_DEVICE_ATTRIBUTE_SPARSE_CUDA_ARRAY_SUPPORTED = 112,
	CU_DEVICE_ATTRIBUTE_READ_ONLY_HOST_REGISTER_SUPPORTED = 113,
	CU_DEVICE_ATTRIBUTE_TIMELINE_SEMAPHORE_INTEROP_SUPPORTED = 114,
	CU_DEVICE_ATTRIBUTE_MEMORY_POOLS_SUPPORTED = 115,
	CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_SUPPORTED = 116,
	CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_FLUSH_WRITES_OPTIONS = 117,
	CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_WRITES_ORDERING = 118,
	CU_DEVICE_ATTRIBUTE_MEMPOOL_SUPPORTED_HANDLE_TYPES = 119,
	CU_DEVICE_ATTRIBUTE_CLUSTER_LAUNCH = 120,
	CU_DEVICE_ATTRIBUTE_DEFERRED_MAPPING_CUDA_ARRAY_SUPPORTED = 121,
	CU_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS = 122,
	CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR = 123,
	CU_DEVICE_ATTRIBUTE_DMA_BUF_SUPPORTED = 124,
	CU_DEVICE_ATTRIBUTE_IPC_EVENT_SUPPORTED = 125,
	CU_DEVICE_ATTRIBUTE_MEM_SYNC_DOMAIN_COUNT = 126,
	CU_DEVICE_ATTRIBUTE_TENSOR_MAP_ACCESS_SUPPORTED = 127,
	CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_FABRIC_SUPPORTED = 128,
	CU_DEVICE_ATTRIBUTE_UNIFIED_FUNCTION_POINTERS = 129,
	CU_DEVICE_ATTRIBUTE_NUMA_CONFIG = 130,
	CU_DEVICE_ATTRIBUTE_NUMA_ID = 131,
	CU_DEVICE_ATTRIBUTE_MULTICAST_SUPPORTED = 132,
	CU_DEVICE_ATTRIBUTE_MPS_ENABLED = 133,
	CU_DEVICE_ATTRIBUTE_HOST_NUMA_ID = 134,
	CU_DEVICE_ATTRIBUTE_D3D12_CIG_SUPPORTED = 135,
	CU_DEVICE_ATTRIBUTE_MEM_DECOMPRESS_ALGORITHM_MASK = 136,
	CU_DEVICE_ATTRIBUTE_MEM_DECOMPRESS_MAXIMUM_LENGTH = 137,
	CU_DEVICE_ATTRIBUTE_VULKAN_CIG_SUPPORTED = 138,
	CU_DEVICE_ATTRIBUTE_GPU_PCI_DEVICE_ID = 139,
	CU_DEVICE_ATTRIBUTE_GPU_PCI_SUBSYSTEM_ID = 140,
	CU_DEVICE_ATTRIBUTE_HOST_NUMA_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED = 141,
	CU_DEVICE_ATTRIBUTE_HOST_NUMA_MEMORY_POOLS_SUPPORTED = 142,
	CU_DEVICE_ATTRIBUTE_HOST_NUMA_MULTINODE_IPC_SUPPORTED = 143,
	CU_DEVICE_ATTRIBUTE_HOST_MEMORY_POOLS_SUPPORTED = 144,
	CU_DEVICE_ATTRIBUTE_HOST_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED = 145,
	CU_DEVICE_ATTRIBUTE_HOST_ALLOC_DMA_BUF_SUPPORTED = 146,
	CU_DEVICE_ATTRIBUTE_ONLY_PARTIAL_HOST_NATIVE_ATOMIC_SUPPORTED = 147,
	CU_DEVICE_ATTRIBUTE_ATOMIC_REDUCTION_SUPPORTED = 148,
	CU_DEVICE_ATTRIBUTE_MAX
} CUdevice_attribute;
typedef struct CUdevprop_st {
	int maxThreadsPerBlock;
	int maxThreadsDim[3];
	int maxGridSize[3];
	int sharedMemPerBlock;
	int totalConstantMemory;
	int SIMDWidth;
	int memPitch;
	int regsPerBlock;
	int clockRate;
	int textureAlign;
} CUdevprop_v1;
typedef CUdevprop_v1 CUdevprop;
typedef enum CUpointer_attribute_enum {
	CU_POINTER_ATTRIBUTE_CONTEXT = 1,
	CU_POINTER_ATTRIBUTE_MEMORY_TYPE = 2,
	CU_POINTER_ATTRIBUTE_DEVICE_POINTER = 3,
	CU_POINTER_ATTRIBUTE_HOST_POINTER = 4,
	CU_POINTER_ATTRIBUTE_P2P_TOKENS = 5,
	CU_POINTER_ATTRIBUTE_SYNC_MEMOPS = 6,
	CU_POINTER_ATTRIBUTE_BUFFER_ID = 7,
	CU_POINTER_ATTRIBUTE_IS_MANAGED = 8,
	CU_POINTER_ATTRIBUTE_DEVICE_ORDINAL = 9,
	CU_POINTER_ATTRIBUTE_IS_LEGACY_CUDA_IPC_CAPABLE = 10,
	CU_POINTER_ATTRIBUTE_RANGE_START_ADDR = 11,
	CU_POINTER_ATTRIBUTE_RANGE_SIZE = 12,
	CU_POINTER_ATTRIBUTE_MAPPED = 13,
	CU_POINTER_ATTRIBUTE_ALLOWED_HANDLE_TYPES = 14,
	CU_POINTER_ATTRIBUTE_IS_GPU_DIRECT_RDMA_CAPABLE = 15,
	CU_POINTER_ATTRIBUTE_ACCESS_FLAGS = 16,
	CU_POINTER_ATTRIBUTE_MEMPOOL_HANDLE = 17,
	CU_POINTER_ATTRIBUTE_MAPPING_SIZE = 18,
	CU_POINTER_ATTRIBUTE_MAPPING_BASE_ADDR = 19,
	CU_POINTER_ATTRIBUTE_MEMORY_BLOCK_ID = 20,
	CU_POINTER_ATTRIBUTE_IS_HW_DECOMPRESS_CAPABLE = 21
} CUpointer_attribute;
typedef enum CUfunction_attribute_enum {
	CU_FUNC_ATTRIBUTE_MAX_THREADS_PER_BLOCK = 0,
	CU_FUNC_ATTRIBUTE_SHARED_SIZE_BYTES = 1,
	CU_FUNC_ATTRIBUTE_CONST_SIZE_BYTES = 2,
	CU_FUNC_ATTRIBUTE_LOCAL_SIZE_BYTES = 3,
	CU_FUNC_ATTRIBUTE_NUM_REGS = 4,
	CU_FUNC_ATTRIBUTE_PTX_VERSION = 5,
	CU_FUNC_ATTRIBUTE_BINARY_VERSION = 6,
	CU_FUNC_ATTRIBUTE_CACHE_MODE_CA = 7,
	CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES = 8,
	CU_FUNC_ATTRIBUTE_PREFERRED_SHARED_MEMORY_CARVEOUT = 9,
	CU_FUNC_ATTRIBUTE_CLUSTER_SIZE_MUST_BE_SET = 10,
	CU_FUNC_ATTRIBUTE_REQUIRED_CLUSTER_WIDTH = 11,
	CU_FUNC_ATTRIBUTE_REQUIRED_CLUSTER_HEIGHT = 12,
	CU_FUNC_ATTRIBUTE_REQUIRED_CLUSTER_DEPTH = 13,
	CU_FUNC_ATTRIBUTE_NON_PORTABLE_CLUSTER_SIZE_ALLOWED = 14,
	CU_FUNC_ATTRIBUTE_CLUSTER_SCHEDULING_POLICY_PREFERENCE = 15,
	CU_FUNC_ATTRIBUTE_MAX
} CUfunction_attribute;
typedef enum CUfunc_cache_enum {
	CU_FUNC_CACHE_PREFER_NONE = 0x00,
	CU_FUNC_CACHE_PREFER_SHARED = 0x01,
	CU_FUNC_CACHE_PREFER_L1 = 0x02,
	CU_FUNC_CACHE_PREFER_EQUAL = 0x03
} CUfunc_cache;
typedef enum CUsharedconfig_enum {
	CU_SHARED_MEM_CONFIG_DEFAULT_BANK_SIZE = 0x00,
	CU_SHARED_MEM_CONFIG_FOUR_BYTE_BANK_SIZE = 0x01,
	CU_SHARED_MEM_CONFIG_EIGHT_BYTE_BANK_SIZE = 0x02
} CUsharedconfig;
typedef enum CUshared_carveout_enum {
	CU_SHAREDMEM_CARVEOUT_DEFAULT = -(1),
	CU_SHAREDMEM_CARVEOUT_MAX_SHARED = 100,
	CU_SHAREDMEM_CARVEOUT_MAX_L1 = 0
} CUshared_carveout;
typedef enum CUmemorytype_enum {
	CU_MEMORYTYPE_HOST = 0x01,
	CU_MEMORYTYPE_DEVICE = 0x02,
	CU_MEMORYTYPE_ARRAY = 0x03,
	CU_MEMORYTYPE_UNIFIED = 0x04
} CUmemorytype;
typedef enum CUcomputemode_enum {
	CU_COMPUTEMODE_DEFAULT = 0,
	CU_COMPUTEMODE_PROHIBITED = 2,
	CU_COMPUTEMODE_EXCLUSIVE_PROCESS = 3
} CUcomputemode;
typedef enum CUmem_advise_enum {
	CU_MEM_ADVISE_SET_READ_MOSTLY = 1,
	CU_MEM_ADVISE_UNSET_READ_MOSTLY = 2,
	CU_MEM_ADVISE_SET_PREFERRED_LOCATION = 3,
	CU_MEM_ADVISE_UNSET_PREFERRED_LOCATION = 4,
	CU_MEM_ADVISE_SET_ACCESSED_BY = 5,
	CU_MEM_ADVISE_UNSET_ACCESSED_BY = 6
} CUmem_advise;
typedef enum CUmem_range_attribute_enum {
	CU_MEM_RANGE_ATTRIBUTE_READ_MOSTLY = 1,
	CU_MEM_RANGE_ATTRIBUTE_PREFERRED_LOCATION = 2,
	CU_MEM_RANGE_ATTRIBUTE_ACCESSED_BY = 3,
	CU_MEM_RANGE_ATTRIBUTE_LAST_PREFETCH_LOCATION = 4,
	CU_MEM_RANGE_ATTRIBUTE_PREFERRED_LOCATION_TYPE = 5,
	CU_MEM_RANGE_ATTRIBUTE_PREFERRED_LOCATION_ID = 6,
	CU_MEM_RANGE_ATTRIBUTE_LAST_PREFETCH_LOCATION_TYPE = 7,
	CU_MEM_RANGE_ATTRIBUTE_LAST_PREFETCH_LOCATION_ID = 8
} CUmem_range_attribute;
typedef enum CUjit_option_enum {
	CU_JIT_MAX_REGISTERS = 0,
	CU_JIT_THREADS_PER_BLOCK = 1,
	CU_JIT_WALL_TIME = 2,
	CU_JIT_INFO_LOG_BUFFER = 3,
	CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES = 4,
	CU_JIT_ERROR_LOG_BUFFER = 5,
	CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES = 6,
	CU_JIT_OPTIMIZATION_LEVEL = 7,
	CU_JIT_TARGET_FROM_CUCONTEXT = 8,
	CU_JIT_TARGET = 9,
	CU_JIT_FALLBACK_STRATEGY = 10,
	CU_JIT_GENERATE_DEBUG_INFO = 11,
	CU_JIT_LOG_VERBOSE = 12,
	CU_JIT_GENERATE_LINE_INFO = 13,
	CU_JIT_CACHE_MODE = 14,
	CU_JIT_NEW_SM3X_OPT = 15,
	CU_JIT_FAST_COMPILE = 16,
	CU_JIT_GLOBAL_SYMBOL_NAMES = 17,
	CU_JIT_GLOBAL_SYMBOL_ADDRESSES = 18,
	CU_JIT_GLOBAL_SYMBOL_COUNT = 19,
	CU_JIT_LTO = 20,
	CU_JIT_FTZ = 21,
	CU_JIT_PREC_DIV = 22,
	CU_JIT_PREC_SQRT = 23,
	CU_JIT_FMA = 24,
	CU_JIT_REFERENCED_KERNEL_NAMES = 25,
	CU_JIT_REFERENCED_KERNEL_COUNT = 26,
	CU_JIT_REFERENCED_VARIABLE_NAMES = 27,
	CU_JIT_REFERENCED_VARIABLE_COUNT = 28,
	CU_JIT_OPTIMIZE_UNUSED_DEVICE_VARIABLES = 29,
	CU_JIT_POSITION_INDEPENDENT_CODE = 30,
	CU_JIT_MIN_CTA_PER_SM = 31,
	CU_JIT_MAX_THREADS_PER_BLOCK = 32,
	CU_JIT_OVERRIDE_DIRECTIVE_VALUES = 33,
	CU_JIT_SPLIT_COMPILE = 34,
	CU_JIT_BINARY_LOADER_THREAD_COUNT = 35,
	CU_JIT_NUM_OPTIONS
} CUjit_option;
typedef enum CUjit_target_enum {
	CU_TARGET_COMPUTE_30 = 30,
	CU_TARGET_COMPUTE_32 = 32,
	CU_TARGET_COMPUTE_35 = 35,
	CU_TARGET_COMPUTE_37 = 37,
	CU_TARGET_COMPUTE_50 = 50,
	CU_TARGET_COMPUTE_52 = 52,
	CU_TARGET_COMPUTE_53 = 53,
	CU_TARGET_COMPUTE_60 = 60,
	CU_TARGET_COMPUTE_61 = 61,
	CU_TARGET_COMPUTE_62 = 62,
	CU_TARGET_COMPUTE_70 = 70,
	CU_TARGET_COMPUTE_72 = 72,
	CU_TARGET_COMPUTE_75 = 75,
	CU_TARGET_COMPUTE_80 = 80,
	CU_TARGET_COMPUTE_86 = 86,
	CU_TARGET_COMPUTE_87 = 87,
	CU_TARGET_COMPUTE_89 = 89,
	CU_TARGET_COMPUTE_90 = 90,
	CU_TARGET_COMPUTE_100 = 100,
	CU_TARGET_COMPUTE_110 = 110,
	CU_TARGET_COMPUTE_103 = 103,
	CU_TARGET_COMPUTE_120 = 120,
	CU_TARGET_COMPUTE_121 = 121,
	CU_TARGET_COMPUTE_90A = 0x10000 + CU_TARGET_COMPUTE_90,
	CU_TARGET_COMPUTE_100A = 0x10000 + CU_TARGET_COMPUTE_100,
	CU_TARGET_COMPUTE_110A = 0x10000 + CU_TARGET_COMPUTE_110,
	CU_TARGET_COMPUTE_103A = 0x10000 + CU_TARGET_COMPUTE_103,
	CU_TARGET_COMPUTE_120A = 0x10000 + CU_TARGET_COMPUTE_120,
	CU_TARGET_COMPUTE_121A = 0x10000 + CU_TARGET_COMPUTE_121,
	CU_TARGET_COMPUTE_100F = 0x20000 + CU_TARGET_COMPUTE_100,
	CU_TARGET_COMPUTE_110F = 0x20000 + CU_TARGET_COMPUTE_110,
	CU_TARGET_COMPUTE_103F = 0x20000 + CU_TARGET_COMPUTE_103,
	CU_TARGET_COMPUTE_120F = 0x20000 + CU_TARGET_COMPUTE_120,
	CU_TARGET_COMPUTE_121F = 0x20000 + CU_TARGET_COMPUTE_121
} CUjit_target;
typedef enum CUjit_fallback_enum {
	CU_PREFER_PTX = 0,
	CU_PREFER_BINARY
} CUjit_fallback;
typedef enum CUjit_cacheMode_enum {
	CU_JIT_CACHE_OPTION_NONE = 0,
	CU_JIT_CACHE_OPTION_CG,
	CU_JIT_CACHE_OPTION_CA
} CUjit_cacheMode;
typedef enum CUjitInputType_enum {
	CU_JIT_INPUT_CUBIN = 0,
	CU_JIT_INPUT_PTX = 1,
	CU_JIT_INPUT_FATBINARY = 2,
	CU_JIT_INPUT_OBJECT = 3,
	CU_JIT_INPUT_LIBRARY = 4,
	CU_JIT_INPUT_NVVM = 5,
	CU_JIT_NUM_INPUT_TYPES = 6
} CUjitInputType;
typedef struct CUlinkState_st* CUlinkState;
typedef enum CUgraphicsRegisterFlags_enum {
	CU_GRAPHICS_REGISTER_FLAGS_NONE = 0x00,
	CU_GRAPHICS_REGISTER_FLAGS_READ_ONLY = 0x01,
	CU_GRAPHICS_REGISTER_FLAGS_WRITE_DISCARD = 0x02,
	CU_GRAPHICS_REGISTER_FLAGS_SURFACE_LDST = 0x04,
	CU_GRAPHICS_REGISTER_FLAGS_TEXTURE_GATHER = 0x08
} CUgraphicsRegisterFlags;
typedef enum CUgraphicsMapResourceFlags_enum {
	CU_GRAPHICS_MAP_RESOURCE_FLAGS_NONE = 0x00,
	CU_GRAPHICS_MAP_RESOURCE_FLAGS_READ_ONLY = 0x01,
	CU_GRAPHICS_MAP_RESOURCE_FLAGS_WRITE_DISCARD = 0x02
} CUgraphicsMapResourceFlags;
typedef enum CUarray_cubemap_face_enum {
	CU_CUBEMAP_FACE_POSITIVE_X = 0x00,
	CU_CUBEMAP_FACE_NEGATIVE_X = 0x01,
	CU_CUBEMAP_FACE_POSITIVE_Y = 0x02,
	CU_CUBEMAP_FACE_NEGATIVE_Y = 0x03,
	CU_CUBEMAP_FACE_POSITIVE_Z = 0x04,
	CU_CUBEMAP_FACE_NEGATIVE_Z = 0x05
} CUarray_cubemap_face;
typedef enum CUlimit_enum {
	CU_LIMIT_STACK_SIZE = 0x00,
	CU_LIMIT_PRINTF_FIFO_SIZE = 0x01,
	CU_LIMIT_MALLOC_HEAP_SIZE = 0x02,
	CU_LIMIT_DEV_RUNTIME_SYNC_DEPTH = 0x03,
	CU_LIMIT_DEV_RUNTIME_PENDING_LAUNCH_COUNT = 0x04,
	CU_LIMIT_MAX_L2_FETCH_GRANULARITY = 0x05,
	CU_LIMIT_PERSISTING_L2_CACHE_SIZE = 0x06,
	CU_LIMIT_SHMEM_SIZE = 0x07,
	CU_LIMIT_CIG_ENABLED = 0x08,
	CU_LIMIT_CIG_SHMEM_FALLBACK_ENABLED = 0x09,
	CU_LIMIT_MAX
} CUlimit;
typedef enum CUresourcetype_enum {
	CU_RESOURCE_TYPE_ARRAY = 0x00,
	CU_RESOURCE_TYPE_MIPMAPPED_ARRAY = 0x01,
	CU_RESOURCE_TYPE_LINEAR = 0x02,
	CU_RESOURCE_TYPE_PITCH2D = 0x03
} CUresourcetype;
typedef void (*CUhostFn)(void* userData);
typedef enum CUaccessProperty_enum {
	CU_ACCESS_PROPERTY_NORMAL = 0,
	CU_ACCESS_PROPERTY_STREAMING = 1,
	CU_ACCESS_PROPERTY_PERSISTING = 2
} CUaccessProperty;
typedef struct CUaccessPolicyWindow_st {
	void* base_ptr;
	size_t num_bytes;
	float hitRatio;
	CUaccessProperty hitProp;
	CUaccessProperty missProp;
} CUaccessPolicyWindow_v1;
typedef CUaccessPolicyWindow_v1 CUaccessPolicyWindow;
typedef struct CUDA_KERNEL_NODE_PARAMS_st {
	CUfunction func;
	unsigned int gridDimX;
	unsigned int gridDimY;
	unsigned int gridDimZ;
	unsigned int blockDimX;
	unsigned int blockDimY;
	unsigned int blockDimZ;
	unsigned int sharedMemBytes;
	void** kernelParams;
	void** extra;
} CUDA_KERNEL_NODE_PARAMS_v1;
typedef struct CUDA_KERNEL_NODE_PARAMS_v2_st {
	CUfunction func;
	unsigned int gridDimX;
	unsigned int gridDimY;
	unsigned int gridDimZ;
	unsigned int blockDimX;
	unsigned int blockDimY;
	unsigned int blockDimZ;
	unsigned int sharedMemBytes;
	void** kernelParams;
	void** extra;
	CUkernel kern;
	CUcontext ctx;
} CUDA_KERNEL_NODE_PARAMS_v2;
typedef CUDA_KERNEL_NODE_PARAMS_v2 CUDA_KERNEL_NODE_PARAMS;
typedef struct CUDA_KERNEL_NODE_PARAMS_v3_st {
	CUfunction func;
	unsigned int gridDimX;
	unsigned int gridDimY;
	unsigned int gridDimZ;
	unsigned int blockDimX;
	unsigned int blockDimY;
	unsigned int blockDimZ;
	unsigned int sharedMemBytes;
	void** kernelParams;
	void** extra;
	CUkernel kern;
	CUcontext ctx;
} CUDA_KERNEL_NODE_PARAMS_v3;
typedef struct CUDA_MEMSET_NODE_PARAMS_st {
	CUdeviceptr dst;
	size_t pitch;
	unsigned int value;
	unsigned int elementSize;
	size_t width;
	size_t height;
} CUDA_MEMSET_NODE_PARAMS_v1;
typedef CUDA_MEMSET_NODE_PARAMS_v1 CUDA_MEMSET_NODE_PARAMS;
typedef struct CUDA_MEMSET_NODE_PARAMS_v2_st {
	CUdeviceptr dst;
	size_t pitch;
	unsigned int value;
	unsigned int elementSize;
	size_t width;
	size_t height;
	CUcontext ctx;
} CUDA_MEMSET_NODE_PARAMS_v2;
typedef struct CUDA_HOST_NODE_PARAMS_st {
	CUhostFn fn;
	void* userData;
} CUDA_HOST_NODE_PARAMS_v1;
typedef CUDA_HOST_NODE_PARAMS_v1 CUDA_HOST_NODE_PARAMS;
typedef struct CUDA_HOST_NODE_PARAMS_v2_st {
	CUhostFn fn;
	void* userData;
} CUDA_HOST_NODE_PARAMS_v2;
typedef enum CUgraphConditionalNodeType_enum {
	CU_GRAPH_COND_TYPE_IF = 0,
	CU_GRAPH_COND_TYPE_WHILE = 1,
	CU_GRAPH_COND_TYPE_SWITCH = 2
} CUgraphConditionalNodeType;
typedef struct CUDA_CONDITIONAL_NODE_PARAMS {
	CUgraphConditionalHandle handle;
	CUgraphConditionalNodeType type;
	unsigned int size;
	CUgraph* phGraph_out;
	CUcontext ctx;
} CUDA_CONDITIONAL_NODE_PARAMS;
typedef enum CUgraphNodeType_enum {
	CU_GRAPH_NODE_TYPE_KERNEL = 0,
	CU_GRAPH_NODE_TYPE_MEMCPY = 1,
	CU_GRAPH_NODE_TYPE_MEMSET = 2,
	CU_GRAPH_NODE_TYPE_HOST = 3,
	CU_GRAPH_NODE_TYPE_GRAPH = 4,
	CU_GRAPH_NODE_TYPE_EMPTY = 5,
	CU_GRAPH_NODE_TYPE_WAIT_EVENT = 6,
	CU_GRAPH_NODE_TYPE_EVENT_RECORD = 7,
	CU_GRAPH_NODE_TYPE_EXT_SEMAS_SIGNAL = 8,
	CU_GRAPH_NODE_TYPE_EXT_SEMAS_WAIT = 9,
	CU_GRAPH_NODE_TYPE_MEM_ALLOC = 10,
	CU_GRAPH_NODE_TYPE_MEM_FREE = 11,
	CU_GRAPH_NODE_TYPE_BATCH_MEM_OP = 12,
	CU_GRAPH_NODE_TYPE_CONDITIONAL = 13
} CUgraphNodeType;
typedef enum CUgraphDependencyType_enum {
	CU_GRAPH_DEPENDENCY_TYPE_DEFAULT = 0,
	CU_GRAPH_DEPENDENCY_TYPE_PROGRAMMATIC = 1
} CUgraphDependencyType;
typedef struct CUgraphEdgeData_st {
	unsigned char from_port;
	unsigned char to_port;
	unsigned char type;
	unsigned char reserved[5];
} CUgraphEdgeData;
typedef enum CUgraphInstantiateResult_enum {
	CUDA_GRAPH_INSTANTIATE_SUCCESS = 0,
	CUDA_GRAPH_INSTANTIATE_ERROR = 1,
	CUDA_GRAPH_INSTANTIATE_INVALID_STRUCTURE = 2,
	CUDA_GRAPH_INSTANTIATE_NODE_OPERATION_NOT_SUPPORTED = 3,
	CUDA_GRAPH_INSTANTIATE_MULTIPLE_CTXS_NOT_SUPPORTED = 4,
	CUDA_GRAPH_INSTANTIATE_CONDITIONAL_HANDLE_UNUSED = 5
} CUgraphInstantiateResult;
typedef struct CUDA_GRAPH_INSTANTIATE_PARAMS_st {
	cuuint64_t flags;
	CUstream hUploadStream;
	CUgraphNode hErrNode_out;
	CUgraphInstantiateResult result_out;
} CUDA_GRAPH_INSTANTIATE_PARAMS;
typedef enum CUsynchronizationPolicy_enum {
	CU_SYNC_POLICY_AUTO = 1,
	CU_SYNC_POLICY_SPIN = 2,
	CU_SYNC_POLICY_YIELD = 3,
	CU_SYNC_POLICY_BLOCKING_SYNC = 4
} CUsynchronizationPolicy;
typedef enum CUclusterSchedulingPolicy_enum {
	CU_CLUSTER_SCHEDULING_POLICY_DEFAULT = 0,
	CU_CLUSTER_SCHEDULING_POLICY_SPREAD = 1,
	CU_CLUSTER_SCHEDULING_POLICY_LOAD_BALANCING = 2
} CUclusterSchedulingPolicy;
typedef enum CUlaunchMemSyncDomain_enum {
	CU_LAUNCH_MEM_SYNC_DOMAIN_DEFAULT = 0,
	CU_LAUNCH_MEM_SYNC_DOMAIN_REMOTE = 1
} CUlaunchMemSyncDomain;
typedef struct CUlaunchMemSyncDomainMap_st {
	unsigned char default_;
	unsigned char remote;
} CUlaunchMemSyncDomainMap;
typedef enum CUlaunchAttributeID_enum {
	CU_LAUNCH_ATTRIBUTE_IGNORE = 0,
	CU_LAUNCH_ATTRIBUTE_ACCESS_POLICY_WINDOW = 1,
	CU_LAUNCH_ATTRIBUTE_COOPERATIVE = 2,
	CU_LAUNCH_ATTRIBUTE_SYNCHRONIZATION_POLICY = 3,
	CU_LAUNCH_ATTRIBUTE_CLUSTER_DIMENSION = 4,
	CU_LAUNCH_ATTRIBUTE_CLUSTER_SCHEDULING_POLICY_PREFERENCE = 5,
	CU_LAUNCH_ATTRIBUTE_PROGRAMMATIC_STREAM_SERIALIZATION = 6,
	CU_LAUNCH_ATTRIBUTE_PROGRAMMATIC_EVENT = 7,
	CU_LAUNCH_ATTRIBUTE_PRIORITY = 8,
	CU_LAUNCH_ATTRIBUTE_MEM_SYNC_DOMAIN_MAP = 9,
	CU_LAUNCH_ATTRIBUTE_MEM_SYNC_DOMAIN = 10,
	CU_LAUNCH_ATTRIBUTE_PREFERRED_CLUSTER_DIMENSION = 11,
	CU_LAUNCH_ATTRIBUTE_LAUNCH_COMPLETION_EVENT = 12,
	CU_LAUNCH_ATTRIBUTE_DEVICE_UPDATABLE_KERNEL_NODE = 13,
	CU_LAUNCH_ATTRIBUTE_PREFERRED_SHARED_MEMORY_CARVEOUT = 14,
	CU_LAUNCH_ATTRIBUTE_NVLINK_UTIL_CENTRIC_SCHEDULING = 16
} CUlaunchAttributeID;
typedef union CUlaunchAttributeValue_union {
	char pad[64];
	CUaccessPolicyWindow accessPolicyWindow;
	int cooperative;
	CUsynchronizationPolicy syncPolicy;
	struct {
		unsigned int x;
		unsigned int y;
		unsigned int z;
	} clusterDim;
	CUclusterSchedulingPolicy clusterSchedulingPolicyPreference;
	int programmaticStreamSerializationAllowed;
	struct {
		CUevent event;
		int flags;
		int triggerAtBlockStart;
	} programmaticEvent;
	struct {
		CUevent event;
		int flags;
	} launchCompletionEvent;
	int priority;
	CUlaunchMemSyncDomainMap memSyncDomainMap;
	CUlaunchMemSyncDomain memSyncDomain;
	struct {
		unsigned int x;
		unsigned int y;
		unsigned int z;
	} preferredClusterDim;
	struct {
		int deviceUpdatable;
		CUgraphDeviceNode devNode;
	} deviceUpdatableKernelNode;
	unsigned int sharedMemCarveout;
	unsigned int nvlinkUtilCentricScheduling;
} CUlaunchAttributeValue;
typedef struct CUlaunchAttribute_st {
	CUlaunchAttributeID id;
	char pad[8 - sizeof(CUlaunchAttributeID)];
	CUlaunchAttributeValue value;
} CUlaunchAttribute;
typedef struct CUlaunchConfig_st {
	unsigned int gridDimX;
	unsigned int gridDimY;
	unsigned int gridDimZ;
	unsigned int blockDimX;
	unsigned int blockDimY;
	unsigned int blockDimZ;
	unsigned int sharedMemBytes;
	CUstream hStream;
	CUlaunchAttribute* attrs;
	unsigned int numAttrs;
} CUlaunchConfig;
typedef CUlaunchAttributeID CUkernelNodeAttrID;
typedef CUlaunchAttributeValue CUkernelNodeAttrValue_v1;
typedef CUkernelNodeAttrValue_v1 CUkernelNodeAttrValue;
typedef enum CUstreamCaptureStatus_enum {
	CU_STREAM_CAPTURE_STATUS_NONE = 0,
	CU_STREAM_CAPTURE_STATUS_ACTIVE = 1,
	CU_STREAM_CAPTURE_STATUS_INVALIDATED = 2
} CUstreamCaptureStatus;
typedef enum CUstreamCaptureMode_enum {
	CU_STREAM_CAPTURE_MODE_GLOBAL = 0,
	CU_STREAM_CAPTURE_MODE_THREAD_LOCAL = 1,
	CU_STREAM_CAPTURE_MODE_RELAXED = 2
} CUstreamCaptureMode;
typedef CUlaunchAttributeID CUstreamAttrID;
typedef CUlaunchAttributeValue CUstreamAttrValue_v1;
typedef CUstreamAttrValue_v1 CUstreamAttrValue;
typedef enum CUdriverProcAddress_flags_enum {
	CU_GET_PROC_ADDRESS_DEFAULT = 0,
	CU_GET_PROC_ADDRESS_LEGACY_STREAM = 1 << 0,
	CU_GET_PROC_ADDRESS_PER_THREAD_DEFAULT_STREAM = 1 << 1
} CUdriverProcAddress_flags;
typedef enum CUdriverProcAddressQueryResult_enum {
	CU_GET_PROC_ADDRESS_SUCCESS = 0,
	CU_GET_PROC_ADDRESS_SYMBOL_NOT_FOUND = 1,
	CU_GET_PROC_ADDRESS_VERSION_NOT_SUFFICIENT = 2
} CUdriverProcAddressQueryResult;
typedef enum CUexecAffinityType_enum {
	CU_EXEC_AFFINITY_TYPE_SM_COUNT = 0,
	CU_EXEC_AFFINITY_TYPE_MAX
} CUexecAffinityType;
typedef struct CUexecAffinitySmCount_st {
	unsigned int val;
} CUexecAffinitySmCount_v1;
typedef CUexecAffinitySmCount_v1 CUexecAffinitySmCount;
typedef struct CUexecAffinityParam_st {
	CUexecAffinityType type;
	union {
		CUexecAffinitySmCount smCount;
	} param;
} CUexecAffinityParam_v1;
typedef CUexecAffinityParam_v1 CUexecAffinityParam;
typedef enum CUcigDataType_enum {
	CIG_DATA_TYPE_D3D12_COMMAND_QUEUE = 0x1,
	CIG_DATA_TYPE_NV_BLOB = 0x2
} CUcigDataType;
typedef struct CUctxCigParam_st {
	CUcigDataType sharedDataType;
	void* sharedData;
} CUctxCigParam;
typedef struct CUctxCreateParams_st {
	CUexecAffinityParam* execAffinityParams;
	int numExecAffinityParams;
	CUctxCigParam* cigParams;
} CUctxCreateParams;
typedef enum CUlibraryOption_enum {
	CU_LIBRARY_HOST_UNIVERSAL_FUNCTION_AND_DATA_TABLE = 0,
	CU_LIBRARY_BINARY_IS_PRESERVED = 1,
	CU_LIBRARY_NUM_OPTIONS
} CUlibraryOption;
typedef struct CUlibraryHostUniversalFunctionAndDataTable_st {
	void* functionTable;
	size_t functionWindowSize;
	void* dataTable;
	size_t dataWindowSize;
} CUlibraryHostUniversalFunctionAndDataTable;
typedef enum cudaError_enum {
	CUDA_SUCCESS = 0,
	CUDA_ERROR_INVALID_VALUE = 1,
	CUDA_ERROR_OUT_OF_MEMORY = 2,
	CUDA_ERROR_NOT_INITIALIZED = 3,
	CUDA_ERROR_DEINITIALIZED = 4,
	CUDA_ERROR_PROFILER_DISABLED = 5,
	CUDA_ERROR_PROFILER_NOT_INITIALIZED = 6,
	CUDA_ERROR_PROFILER_ALREADY_STARTED = 7,
	CUDA_ERROR_PROFILER_ALREADY_STOPPED = 8,
	CUDA_ERROR_STUB_LIBRARY = 34,
	CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER = 36,
	CUDA_ERROR_DEVICE_UNAVAILABLE = 46,
	CUDA_ERROR_NO_DEVICE = 100,
	CUDA_ERROR_INVALID_DEVICE = 101,
	CUDA_ERROR_DEVICE_NOT_LICENSED = 102,
	CUDA_ERROR_INVALID_IMAGE = 200,
	CUDA_ERROR_INVALID_CONTEXT = 201,
	CUDA_ERROR_CONTEXT_ALREADY_CURRENT = 202,
	CUDA_ERROR_MAP_FAILED = 205,
	CUDA_ERROR_UNMAP_FAILED = 206,
	CUDA_ERROR_ARRAY_IS_MAPPED = 207,
	CUDA_ERROR_ALREADY_MAPPED = 208,
	CUDA_ERROR_NO_BINARY_FOR_GPU = 209,
	CUDA_ERROR_ALREADY_ACQUIRED = 210,
	CUDA_ERROR_NOT_MAPPED = 211,
	CUDA_ERROR_NOT_MAPPED_AS_ARRAY = 212,
	CUDA_ERROR_NOT_MAPPED_AS_POINTER = 213,
	CUDA_ERROR_ECC_UNCORRECTABLE = 214,
	CUDA_ERROR_UNSUPPORTED_LIMIT = 215,
	CUDA_ERROR_CONTEXT_ALREADY_IN_USE = 216,
	CUDA_ERROR_PEER_ACCESS_UNSUPPORTED = 217,
	CUDA_ERROR_INVALID_PTX = 218,
	CUDA_ERROR_INVALID_GRAPHICS_CONTEXT = 219,
	CUDA_ERROR_NVLINK_UNCORRECTABLE = 220,
	CUDA_ERROR_JIT_COMPILER_NOT_FOUND = 221,
	CUDA_ERROR_UNSUPPORTED_PTX_VERSION = 222,
	CUDA_ERROR_JIT_COMPILATION_DISABLED = 223,
	CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY = 224,
	CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC = 225,
	CUDA_ERROR_CONTAINED = 226,
	CUDA_ERROR_INVALID_SOURCE = 300,
	CUDA_ERROR_FILE_NOT_FOUND = 301,
	CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND = 302,
	CUDA_ERROR_SHARED_OBJECT_INIT_FAILED = 303,
	CUDA_ERROR_OPERATING_SYSTEM = 304,
	CUDA_ERROR_INVALID_HANDLE = 400,
	CUDA_ERROR_ILLEGAL_STATE = 401,
	CUDA_ERROR_LOSSY_QUERY = 402,
	CUDA_ERROR_NOT_FOUND = 500,
	CUDA_ERROR_NOT_READY = 600,
	CUDA_ERROR_ILLEGAL_ADDRESS = 700,
	CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES = 701,
	CUDA_ERROR_LAUNCH_TIMEOUT = 702,
	CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING = 703,
	CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED = 704,
	CUDA_ERROR_PEER_ACCESS_NOT_ENABLED = 705,
	CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE = 708,
	CUDA_ERROR_CONTEXT_IS_DESTROYED = 709,
	CUDA_ERROR_ASSERT = 710,
	CUDA_ERROR_TOO_MANY_PEERS = 711,
	CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED = 712,
	CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED = 713,
	CUDA_ERROR_HARDWARE_STACK_ERROR = 714,
	CUDA_ERROR_ILLEGAL_INSTRUCTION = 715,
	CUDA_ERROR_MISALIGNED_ADDRESS = 716,
	CUDA_ERROR_INVALID_ADDRESS_SPACE = 717,
	CUDA_ERROR_INVALID_PC = 718,
	CUDA_ERROR_LAUNCH_FAILED = 719,
	CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE = 720,
	CUDA_ERROR_TENSOR_MEMORY_LEAK = 721,
	CUDA_ERROR_NOT_PERMITTED = 800,
	CUDA_ERROR_NOT_SUPPORTED = 801,
	CUDA_ERROR_SYSTEM_NOT_READY = 802,
	CUDA_ERROR_SYSTEM_DRIVER_MISMATCH = 803,
	CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE = 804,
	CUDA_ERROR_MPS_CONNECTION_FAILED = 805,
	CUDA_ERROR_MPS_RPC_FAILURE = 806,
	CUDA_ERROR_MPS_SERVER_NOT_READY = 807,
	CUDA_ERROR_MPS_MAX_CLIENTS_REACHED = 808,
	CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED = 809,
	CUDA_ERROR_MPS_CLIENT_TERMINATED = 810,
	CUDA_ERROR_CDP_NOT_SUPPORTED = 811,
	CUDA_ERROR_CDP_VERSION_MISMATCH = 812,
	CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED = 900,
	CUDA_ERROR_STREAM_CAPTURE_INVALIDATED = 901,
	CUDA_ERROR_STREAM_CAPTURE_MERGE = 902,
	CUDA_ERROR_STREAM_CAPTURE_UNMATCHED = 903,
	CUDA_ERROR_STREAM_CAPTURE_UNJOINED = 904,
	CUDA_ERROR_STREAM_CAPTURE_ISOLATION = 905,
	CUDA_ERROR_STREAM_CAPTURE_IMPLICIT = 906,
	CUDA_ERROR_CAPTURED_EVENT = 907,
	CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD = 908,
	CUDA_ERROR_TIMEOUT = 909,
	CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE = 910,
	CUDA_ERROR_EXTERNAL_DEVICE = 911,
	CUDA_ERROR_INVALID_CLUSTER_SIZE = 912,
	CUDA_ERROR_FUNCTION_NOT_LOADED = 913,
	CUDA_ERROR_INVALID_RESOURCE_TYPE = 914,
	CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION = 915,
	CUDA_ERROR_KEY_ROTATION = 916,
	CUDA_ERROR_STREAM_DETACHED = 917,
	CUDA_ERROR_UNKNOWN = 999
} CUresult;
typedef enum CUdevice_P2PAttribute_enum {
	CU_DEVICE_P2P_ATTRIBUTE_PERFORMANCE_RANK = 0x01,
	CU_DEVICE_P2P_ATTRIBUTE_ACCESS_SUPPORTED = 0x02,
	CU_DEVICE_P2P_ATTRIBUTE_NATIVE_ATOMIC_SUPPORTED = 0x03,
	CU_DEVICE_P2P_ATTRIBUTE_ACCESS_ACCESS_SUPPORTED = 0x04,
	CU_DEVICE_P2P_ATTRIBUTE_CUDA_ARRAY_ACCESS_SUPPORTED = 0x04,
	CU_DEVICE_P2P_ATTRIBUTE_ONLY_PARTIAL_NATIVE_ATOMIC_SUPPORTED = 0x05
} CUdevice_P2PAttribute;
typedef void (*CUstreamCallback)(CUstream hStream, CUresult status, void* userData);
typedef size_t (*CUoccupancyB2DSize)(int blockSize);
typedef struct CUDA_MEMCPY2D_st {
	size_t srcXInBytes;
	size_t srcY;
	CUmemorytype srcMemoryType;
	const void* srcHost;
	CUdeviceptr srcDevice;
	CUarray srcArray;
	size_t srcPitch;
	size_t dstXInBytes;
	size_t dstY;
	CUmemorytype dstMemoryType;
	void* dstHost;
	CUdeviceptr dstDevice;
	CUarray dstArray;
	size_t dstPitch;
	size_t WidthInBytes;
	size_t Height;
} CUDA_MEMCPY2D_v2;
typedef CUDA_MEMCPY2D_v2 CUDA_MEMCPY2D;
typedef struct CUDA_MEMCPY3D_st {
	size_t srcXInBytes;
	size_t srcY;
	size_t srcZ;
	size_t srcLOD;
	CUmemorytype srcMemoryType;
	const void* srcHost;
	CUdeviceptr srcDevice;
	CUarray srcArray;
	void* reserved0;
	size_t srcPitch;
	size_t srcHeight;
	size_t dstXInBytes;
	size_t dstY;
	size_t dstZ;
	size_t dstLOD;
	CUmemorytype dstMemoryType;
	void* dstHost;
	CUdeviceptr dstDevice;
	CUarray dstArray;
	void* reserved1;
	size_t dstPitch;
	size_t dstHeight;
	size_t WidthInBytes;
	size_t Height;
	size_t Depth;
} CUDA_MEMCPY3D_v2;
typedef CUDA_MEMCPY3D_v2 CUDA_MEMCPY3D;
typedef struct CUDA_MEMCPY3D_PEER_st {
	size_t srcXInBytes;
	size_t srcY;
	size_t srcZ;
	size_t srcLOD;
	CUmemorytype srcMemoryType;
	const void* srcHost;
	CUdeviceptr srcDevice;
	CUarray srcArray;
	CUcontext srcContext;
	size_t srcPitch;
	size_t srcHeight;
	size_t dstXInBytes;
	size_t dstY;
	size_t dstZ;
	size_t dstLOD;
	CUmemorytype dstMemoryType;
	void* dstHost;
	CUdeviceptr dstDevice;
	CUarray dstArray;
	CUcontext dstContext;
	size_t dstPitch;
	size_t dstHeight;
	size_t WidthInBytes;
	size_t Height;
	size_t Depth;
} CUDA_MEMCPY3D_PEER_v1;
typedef CUDA_MEMCPY3D_PEER_v1 CUDA_MEMCPY3D_PEER;
typedef struct CUDA_MEMCPY_NODE_PARAMS_st {
	int flags;
	int reserved;
	CUcontext copyCtx;
	CUDA_MEMCPY3D copyParams;
} CUDA_MEMCPY_NODE_PARAMS;
typedef struct CUDA_ARRAY_DESCRIPTOR_st {
	size_t Width;
	size_t Height;
	CUarray_format Format;
	unsigned int NumChannels;
} CUDA_ARRAY_DESCRIPTOR_v2;
typedef CUDA_ARRAY_DESCRIPTOR_v2 CUDA_ARRAY_DESCRIPTOR;
typedef struct CUDA_ARRAY3D_DESCRIPTOR_st {
	size_t Width;
	size_t Height;
	size_t Depth;
	CUarray_format Format;
	unsigned int NumChannels;
	unsigned int Flags;
} CUDA_ARRAY3D_DESCRIPTOR_v2;
typedef CUDA_ARRAY3D_DESCRIPTOR_v2 CUDA_ARRAY3D_DESCRIPTOR;
typedef struct CUDA_ARRAY_SPARSE_PROPERTIES_st {
	struct {
		unsigned int width;
		unsigned int height;
		unsigned int depth;
	} tileExtent;
	unsigned int miptailFirstLevel;
	unsigned long long miptailSize;
	unsigned int flags;
	unsigned int reserved[4];
} CUDA_ARRAY_SPARSE_PROPERTIES_v1;
typedef CUDA_ARRAY_SPARSE_PROPERTIES_v1 CUDA_ARRAY_SPARSE_PROPERTIES;
typedef struct CUDA_ARRAY_MEMORY_REQUIREMENTS_st {
	size_t size;
	size_t alignment;
	unsigned int reserved[4];
} CUDA_ARRAY_MEMORY_REQUIREMENTS_v1;
typedef CUDA_ARRAY_MEMORY_REQUIREMENTS_v1 CUDA_ARRAY_MEMORY_REQUIREMENTS;
typedef struct CUDA_RESOURCE_DESC_st {
	CUresourcetype resType;
	union {
		struct {
			CUarray hArray;
		} array;
		struct {
			CUmipmappedArray hMipmappedArray;
		} mipmap;
		struct {
			CUdeviceptr devPtr;
			CUarray_format format;
			unsigned int numChannels;
			size_t sizeInBytes;
		} linear;
		struct {
			CUdeviceptr devPtr;
			CUarray_format format;
			unsigned int numChannels;
			size_t width;
			size_t height;
			size_t pitchInBytes;
		} pitch2D;
		struct {
			int reserved[32];
		} reserved;
	} res;
	unsigned int flags;
} CUDA_RESOURCE_DESC_v1;
typedef CUDA_RESOURCE_DESC_v1 CUDA_RESOURCE_DESC;
typedef struct CUDA_TEXTURE_DESC_st {
	CUaddress_mode addressMode[3];
	CUfilter_mode filterMode;
	unsigned int flags;
	unsigned int maxAnisotropy;
	CUfilter_mode mipmapFilterMode;
	float mipmapLevelBias;
	float minMipmapLevelClamp;
	float maxMipmapLevelClamp;
	float borderColor[4];
	int reserved[12];
} CUDA_TEXTURE_DESC_v1;
typedef CUDA_TEXTURE_DESC_v1 CUDA_TEXTURE_DESC;
typedef enum CUresourceViewFormat_enum {
	CU_RES_VIEW_FORMAT_NONE = 0x00,
	CU_RES_VIEW_FORMAT_UINT_1X8 = 0x01,
	CU_RES_VIEW_FORMAT_UINT_2X8 = 0x02,
	CU_RES_VIEW_FORMAT_UINT_4X8 = 0x03,
	CU_RES_VIEW_FORMAT_SINT_1X8 = 0x04,
	CU_RES_VIEW_FORMAT_SINT_2X8 = 0x05,
	CU_RES_VIEW_FORMAT_SINT_4X8 = 0x06,
	CU_RES_VIEW_FORMAT_UINT_1X16 = 0x07,
	CU_RES_VIEW_FORMAT_UINT_2X16 = 0x08,
	CU_RES_VIEW_FORMAT_UINT_4X16 = 0x09,
	CU_RES_VIEW_FORMAT_SINT_1X16 = 0x0a,
	CU_RES_VIEW_FORMAT_SINT_2X16 = 0x0b,
	CU_RES_VIEW_FORMAT_SINT_4X16 = 0x0c,
	CU_RES_VIEW_FORMAT_UINT_1X32 = 0x0d,
	CU_RES_VIEW_FORMAT_UINT_2X32 = 0x0e,
	CU_RES_VIEW_FORMAT_UINT_4X32 = 0x0f,
	CU_RES_VIEW_FORMAT_SINT_1X32 = 0x10,
	CU_RES_VIEW_FORMAT_SINT_2X32 = 0x11,
	CU_RES_VIEW_FORMAT_SINT_4X32 = 0x12,
	CU_RES_VIEW_FORMAT_FLOAT_1X16 = 0x13,
	CU_RES_VIEW_FORMAT_FLOAT_2X16 = 0x14,
	CU_RES_VIEW_FORMAT_FLOAT_4X16 = 0x15,
	CU_RES_VIEW_FORMAT_FLOAT_1X32 = 0x16,
	CU_RES_VIEW_FORMAT_FLOAT_2X32 = 0x17,
	CU_RES_VIEW_FORMAT_FLOAT_4X32 = 0x18,
	CU_RES_VIEW_FORMAT_UNSIGNED_BC1 = 0x19,
	CU_RES_VIEW_FORMAT_UNSIGNED_BC2 = 0x1a,
	CU_RES_VIEW_FORMAT_UNSIGNED_BC3 = 0x1b,
	CU_RES_VIEW_FORMAT_UNSIGNED_BC4 = 0x1c,
	CU_RES_VIEW_FORMAT_SIGNED_BC4 = 0x1d,
	CU_RES_VIEW_FORMAT_UNSIGNED_BC5 = 0x1e,
	CU_RES_VIEW_FORMAT_SIGNED_BC5 = 0x1f,
	CU_RES_VIEW_FORMAT_UNSIGNED_BC6H = 0x20,
	CU_RES_VIEW_FORMAT_SIGNED_BC6H = 0x21,
	CU_RES_VIEW_FORMAT_UNSIGNED_BC7 = 0x22
} CUresourceViewFormat;
typedef struct CUDA_RESOURCE_VIEW_DESC_st {
	CUresourceViewFormat format;
	size_t width;
	size_t height;
	size_t depth;
	unsigned int firstMipmapLevel;
	unsigned int lastMipmapLevel;
	unsigned int firstLayer;
	unsigned int lastLayer;
	unsigned int reserved[16];
} CUDA_RESOURCE_VIEW_DESC_v1;
typedef CUDA_RESOURCE_VIEW_DESC_v1 CUDA_RESOURCE_VIEW_DESC;
typedef struct CUtensorMap_st {
	cuuint64_t opaque[16];
} CUtensorMap;
typedef enum CUtensorMapDataType_enum {
	CU_TENSOR_MAP_DATA_TYPE_UINT8 = 0,
	CU_TENSOR_MAP_DATA_TYPE_UINT16,
	CU_TENSOR_MAP_DATA_TYPE_UINT32,
	CU_TENSOR_MAP_DATA_TYPE_INT32,
	CU_TENSOR_MAP_DATA_TYPE_UINT64,
	CU_TENSOR_MAP_DATA_TYPE_INT64,
	CU_TENSOR_MAP_DATA_TYPE_FLOAT16,
	CU_TENSOR_MAP_DATA_TYPE_FLOAT32,
	CU_TENSOR_MAP_DATA_TYPE_FLOAT64,
	CU_TENSOR_MAP_DATA_TYPE_BFLOAT16,
	CU_TENSOR_MAP_DATA_TYPE_FLOAT32_FTZ,
	CU_TENSOR_MAP_DATA_TYPE_TFLOAT32,
	CU_TENSOR_MAP_DATA_TYPE_TFLOAT32_FTZ,
	CU_TENSOR_MAP_DATA_TYPE_16U4_ALIGN8B,
	CU_TENSOR_MAP_DATA_TYPE_16U4_ALIGN16B,
	CU_TENSOR_MAP_DATA_TYPE_16U6_ALIGN16B
} CUtensorMapDataType;
typedef enum CUtensorMapInterleave_enum {
	CU_TENSOR_MAP_INTERLEAVE_NONE = 0,
	CU_TENSOR_MAP_INTERLEAVE_16B,
	CU_TENSOR_MAP_INTERLEAVE_32B
} CUtensorMapInterleave;
typedef enum CUtensorMapSwizzle_enum {
	CU_TENSOR_MAP_SWIZZLE_NONE = 0,
	CU_TENSOR_MAP_SWIZZLE_32B,
	CU_TENSOR_MAP_SWIZZLE_64B,
	CU_TENSOR_MAP_SWIZZLE_128B,
	CU_TENSOR_MAP_SWIZZLE_128B_ATOM_32B,
	CU_TENSOR_MAP_SWIZZLE_128B_ATOM_32B_FLIP_8B,
	CU_TENSOR_MAP_SWIZZLE_128B_ATOM_64B
} CUtensorMapSwizzle;
typedef enum CUtensorMapL2promotion_enum {
	CU_TENSOR_MAP_L2_PROMOTION_NONE = 0,
	CU_TENSOR_MAP_L2_PROMOTION_L2_64B,
	CU_TENSOR_MAP_L2_PROMOTION_L2_128B,
	CU_TENSOR_MAP_L2_PROMOTION_L2_256B
} CUtensorMapL2promotion;
typedef enum CUtensorMapFloatOOBfill_enum {
	CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE = 0,
	CU_TENSOR_MAP_FLOAT_OOB_FILL_NAN_REQUEST_ZERO_FMA
} CUtensorMapFloatOOBfill;
typedef enum CUtensorMapIm2ColWideMode_enum {
	CU_TENSOR_MAP_IM2COL_WIDE_MODE_W = 0,
	CU_TENSOR_MAP_IM2COL_WIDE_MODE_W128
} CUtensorMapIm2ColWideMode;
typedef struct CUDA_POINTER_ATTRIBUTE_P2P_TOKENS_st {
	unsigned long long p2pToken;
	unsigned int vaSpaceToken;
} CUDA_POINTER_ATTRIBUTE_P2P_TOKENS_v1;
typedef CUDA_POINTER_ATTRIBUTE_P2P_TOKENS_v1 CUDA_POINTER_ATTRIBUTE_P2P_TOKENS;
typedef enum CUDA_POINTER_ATTRIBUTE_ACCESS_FLAGS_enum {
	CU_POINTER_ATTRIBUTE_ACCESS_FLAG_NONE = 0x0,
	CU_POINTER_ATTRIBUTE_ACCESS_FLAG_READ = 0x1,
	CU_POINTER_ATTRIBUTE_ACCESS_FLAG_READWRITE = 0x3
} CUDA_POINTER_ATTRIBUTE_ACCESS_FLAGS;
typedef struct CUDA_LAUNCH_PARAMS_st {
	CUfunction function;
	unsigned int gridDimX;
	unsigned int gridDimY;
	unsigned int gridDimZ;
	unsigned int blockDimX;
	unsigned int blockDimY;
	unsigned int blockDimZ;
	unsigned int sharedMemBytes;
	CUstream hStream;
	void** kernelParams;
} CUDA_LAUNCH_PARAMS_v1;
typedef CUDA_LAUNCH_PARAMS_v1 CUDA_LAUNCH_PARAMS;
typedef enum CUexternalMemoryHandleType_enum {
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD = 1,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32 = 2,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT = 3,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP = 4,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE = 5,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_RESOURCE = 6,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_RESOURCE_KMT = 7,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_NVSCIBUF = 8,
	CU_EXTERNAL_MEMORY_HANDLE_TYPE_DMABUF_FD = 9
} CUexternalMemoryHandleType;
typedef struct CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st {
	CUexternalMemoryHandleType type;
	union {
		int fd;
		struct {
			void* handle;
			const void* name;
		} win32;
		const void* nvSciBufObject;
	} handle;
	unsigned long long size;
	unsigned int flags;
	unsigned int reserved[16];
} CUDA_EXTERNAL_MEMORY_HANDLE_DESC_v1;
typedef CUDA_EXTERNAL_MEMORY_HANDLE_DESC_v1 CUDA_EXTERNAL_MEMORY_HANDLE_DESC;
typedef struct CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st {
	unsigned long long offset;
	unsigned long long size;
	unsigned int flags;
	unsigned int reserved[16];
} CUDA_EXTERNAL_MEMORY_BUFFER_DESC_v1;
typedef CUDA_EXTERNAL_MEMORY_BUFFER_DESC_v1 CUDA_EXTERNAL_MEMORY_BUFFER_DESC;
typedef struct CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st {
	unsigned long long offset;
	CUDA_ARRAY3D_DESCRIPTOR arrayDesc;
	unsigned int numLevels;
	unsigned int reserved[16];
} CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_v1;
typedef CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_v1 CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC;
typedef enum CUexternalSemaphoreHandleType_enum {
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD = 1,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32 = 2,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT = 3,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE = 4,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D11_FENCE = 5,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_NVSCISYNC = 6,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D11_KEYED_MUTEX = 7,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D11_KEYED_MUTEX_KMT = 8,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_TIMELINE_SEMAPHORE_FD = 9,
	CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_TIMELINE_SEMAPHORE_WIN32 = 10
} CUexternalSemaphoreHandleType;
typedef struct CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st {
	CUexternalSemaphoreHandleType type;
	union {
		int fd;
		struct {
			void* handle;
			const void* name;
		} win32;
		const void* nvSciSyncObj;
	} handle;
	unsigned int flags;
	unsigned int reserved[16];
} CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_v1;
typedef CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_v1 CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC;
typedef struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st {
	struct {
		struct {
			unsigned long long value;
		} fence;
		union {
			void* fence;
			unsigned long long reserved;
		} nvSciSync;
		struct {
			unsigned long long key;
		} keyedMutex;
		unsigned int reserved[12];
	} params;
	unsigned int flags;
	unsigned int reserved[16];
} CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_v1;
typedef CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_v1 CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS;
typedef struct CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_st {
	struct {
		struct {
			unsigned long long value;
		} fence;
		union {
			void* fence;
			unsigned long long reserved;
		} nvSciSync;
		struct {
			unsigned long long key;
			unsigned int timeoutMs;
		} keyedMutex;
		unsigned int reserved[10];
	} params;
	unsigned int flags;
	unsigned int reserved[16];
} CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_v1;
typedef CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS_v1 CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS;
typedef struct CUDA_EXT_SEM_SIGNAL_NODE_PARAMS_st {
	CUexternalSemaphore* extSemArray;
	const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS* paramsArray;
	unsigned int numExtSems;
} CUDA_EXT_SEM_SIGNAL_NODE_PARAMS_v1;
typedef CUDA_EXT_SEM_SIGNAL_NODE_PARAMS_v1 CUDA_EXT_SEM_SIGNAL_NODE_PARAMS;
typedef struct CUDA_EXT_SEM_SIGNAL_NODE_PARAMS_v2_st {
	CUexternalSemaphore* extSemArray;
	const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS* paramsArray;
	unsigned int numExtSems;
} CUDA_EXT_SEM_SIGNAL_NODE_PARAMS_v2;
typedef struct CUDA_EXT_SEM_WAIT_NODE_PARAMS_st {
	CUexternalSemaphore* extSemArray;
	const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS* paramsArray;
	unsigned int numExtSems;
} CUDA_EXT_SEM_WAIT_NODE_PARAMS_v1;
typedef CUDA_EXT_SEM_WAIT_NODE_PARAMS_v1 CUDA_EXT_SEM_WAIT_NODE_PARAMS;
typedef struct CUDA_EXT_SEM_WAIT_NODE_PARAMS_v2_st {
	CUexternalSemaphore* extSemArray;
	const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS* paramsArray;
	unsigned int numExtSems;
} CUDA_EXT_SEM_WAIT_NODE_PARAMS_v2;
typedef unsigned long long CUmemGenericAllocationHandle_v1;
typedef CUmemGenericAllocationHandle_v1 CUmemGenericAllocationHandle;
typedef enum CUmemAllocationHandleType_enum {
	CU_MEM_HANDLE_TYPE_NONE = 0x0,
	CU_MEM_HANDLE_TYPE_POSIX_FILE_DESCRIPTOR = 0x1,
	CU_MEM_HANDLE_TYPE_WIN32 = 0x2,
	CU_MEM_HANDLE_TYPE_WIN32_KMT = 0x4,
	CU_MEM_HANDLE_TYPE_FABRIC = 0x8,
	CU_MEM_HANDLE_TYPE_MAX = 0x7FFFFFFF
} CUmemAllocationHandleType;
typedef enum CUmemAccess_flags_enum {
	CU_MEM_ACCESS_FLAGS_PROT_NONE = 0x0,
	CU_MEM_ACCESS_FLAGS_PROT_READ = 0x1,
	CU_MEM_ACCESS_FLAGS_PROT_READWRITE = 0x3,
	CU_MEM_ACCESS_FLAGS_PROT_MAX = 0x7FFFFFFF
} CUmemAccess_flags;
typedef enum CUmemLocationType_enum {
	CU_MEM_LOCATION_TYPE_INVALID = 0x0,
	CU_MEM_LOCATION_TYPE_NONE = 0x0,
	CU_MEM_LOCATION_TYPE_DEVICE = 0x1,
	CU_MEM_LOCATION_TYPE_HOST = 0x2,
	CU_MEM_LOCATION_TYPE_HOST_NUMA = 0x3,
	CU_MEM_LOCATION_TYPE_HOST_NUMA_CURRENT = 0x4,
	CU_MEM_LOCATION_TYPE_MAX = 0x7FFFFFFF
} CUmemLocationType;
typedef enum CUmemAllocationType_enum {
	CU_MEM_ALLOCATION_TYPE_INVALID = 0x0,
	CU_MEM_ALLOCATION_TYPE_PINNED = 0x1,
	CU_MEM_ALLOCATION_TYPE_MANAGED = 0x2,
	CU_MEM_ALLOCATION_TYPE_MAX = 0x7FFFFFFF
} CUmemAllocationType;
typedef enum CUmemAllocationGranularity_flags_enum {
	CU_MEM_ALLOC_GRANULARITY_MINIMUM = 0x0,
	CU_MEM_ALLOC_GRANULARITY_RECOMMENDED = 0x1
} CUmemAllocationGranularity_flags;
typedef enum CUmemRangeHandleType_enum {
	CU_MEM_RANGE_HANDLE_TYPE_DMA_BUF_FD = 0x1,
	CU_MEM_RANGE_HANDLE_TYPE_MAX = 0x7FFFFFFF
} CUmemRangeHandleType;
typedef enum CUmemRangeFlags_enum {
	CU_MEM_RANGE_FLAG_DMA_BUF_MAPPING_TYPE_PCIE = 0x1
} CUmemRangeFlags;
typedef enum CUarraySparseSubresourceType_enum {
	CU_ARRAY_SPARSE_SUBRESOURCE_TYPE_SPARSE_LEVEL = 0,
	CU_ARRAY_SPARSE_SUBRESOURCE_TYPE_MIPTAIL = 1
} CUarraySparseSubresourceType;
typedef enum CUmemOperationType_enum {
	CU_MEM_OPERATION_TYPE_MAP = 1,
	CU_MEM_OPERATION_TYPE_UNMAP = 2
} CUmemOperationType;
typedef enum CUmemHandleType_enum {
	CU_MEM_HANDLE_TYPE_GENERIC = 0
} CUmemHandleType;
typedef struct CUarrayMapInfo_st {
	CUresourcetype resourceType;
	union {
		CUmipmappedArray mipmap;
		CUarray array;
	} resource;
	CUarraySparseSubresourceType subresourceType;
	union {
		struct {
			unsigned int level;
			unsigned int layer;
			unsigned int offsetX;
			unsigned int offsetY;
			unsigned int offsetZ;
			unsigned int extentWidth;
			unsigned int extentHeight;
			unsigned int extentDepth;
		} sparseLevel;
		struct {
			unsigned int layer;
			unsigned long long offset;
			unsigned long long size;
		} miptail;
	} subresource;
	CUmemOperationType memOperationType;
	CUmemHandleType memHandleType;
	union {
		CUmemGenericAllocationHandle memHandle;
	} memHandle;
	unsigned long long offset;
	unsigned int deviceBitMask;
	unsigned int flags;
	unsigned int reserved[2];
} CUarrayMapInfo_v1;
typedef CUarrayMapInfo_v1 CUarrayMapInfo;
typedef struct CUmemLocation_st {
	CUmemLocationType type;
	int id;
} CUmemLocation_v1;
typedef CUmemLocation_v1 CUmemLocation;
typedef enum CUmemAllocationCompType_enum {
	CU_MEM_ALLOCATION_COMP_NONE = 0x0,
	CU_MEM_ALLOCATION_COMP_GENERIC = 0x1
} CUmemAllocationCompType;
typedef struct CUmemAllocationProp_st {
	CUmemAllocationType type;
	CUmemAllocationHandleType requestedHandleTypes;
	CUmemLocation location;
	void* win32HandleMetaData;
	struct {
		unsigned char compressionType;
		unsigned char gpuDirectRDMACapable;
		unsigned short usage;
		unsigned char reserved[4];
	} allocFlags;
} CUmemAllocationProp_v1;
typedef CUmemAllocationProp_v1 CUmemAllocationProp;
typedef enum CUmulticastGranularity_flags_enum {
	CU_MULTICAST_GRANULARITY_MINIMUM = 0x0,
	CU_MULTICAST_GRANULARITY_RECOMMENDED = 0x1
} CUmulticastGranularity_flags;
typedef struct CUmulticastObjectProp_st {
	unsigned int numDevices;
	size_t size;
	unsigned long long handleTypes;
	unsigned long long flags;
} CUmulticastObjectProp_v1;
typedef CUmulticastObjectProp_v1 CUmulticastObjectProp;
typedef struct CUmemAccessDesc_st {
	CUmemLocation location;
	CUmemAccess_flags flags;
} CUmemAccessDesc_v1;
typedef CUmemAccessDesc_v1 CUmemAccessDesc;
typedef enum CUgraphExecUpdateResult_enum {
	CU_GRAPH_EXEC_UPDATE_SUCCESS = 0x0,
	CU_GRAPH_EXEC_UPDATE_ERROR = 0x1,
	CU_GRAPH_EXEC_UPDATE_ERROR_TOPOLOGY_CHANGED = 0x2,
	CU_GRAPH_EXEC_UPDATE_ERROR_NODE_TYPE_CHANGED = 0x3,
	CU_GRAPH_EXEC_UPDATE_ERROR_FUNCTION_CHANGED = 0x4,
	CU_GRAPH_EXEC_UPDATE_ERROR_PARAMETERS_CHANGED = 0x5,
	CU_GRAPH_EXEC_UPDATE_ERROR_NOT_SUPPORTED = 0x6,
	CU_GRAPH_EXEC_UPDATE_ERROR_UNSUPPORTED_FUNCTION_CHANGE = 0x7,
	CU_GRAPH_EXEC_UPDATE_ERROR_ATTRIBUTES_CHANGED = 0x8
} CUgraphExecUpdateResult;
typedef struct CUgraphExecUpdateResultInfo_st {
	CUgraphExecUpdateResult result;
	CUgraphNode errorNode;
	CUgraphNode errorFromNode;
} CUgraphExecUpdateResultInfo_v1;
typedef CUgraphExecUpdateResultInfo_v1 CUgraphExecUpdateResultInfo;
typedef enum CUmemPool_attribute_enum {
	CU_MEMPOOL_ATTR_REUSE_FOLLOW_EVENT_DEPENDENCIES = 1,
	CU_MEMPOOL_ATTR_REUSE_ALLOW_OPPORTUNISTIC,
	CU_MEMPOOL_ATTR_REUSE_ALLOW_INTERNAL_DEPENDENCIES,
	CU_MEMPOOL_ATTR_RELEASE_THRESHOLD,
	CU_MEMPOOL_ATTR_RESERVED_MEM_CURRENT,
	CU_MEMPOOL_ATTR_RESERVED_MEM_HIGH,
	CU_MEMPOOL_ATTR_USED_MEM_CURRENT,
	CU_MEMPOOL_ATTR_USED_MEM_HIGH
} CUmemPool_attribute;
typedef struct CUmemPoolProps_st {
	CUmemAllocationType allocType;
	CUmemAllocationHandleType handleTypes;
	CUmemLocation location;
	void* win32SecurityAttributes;
	size_t maxSize;
	unsigned short usage;
	unsigned char reserved[54];
} CUmemPoolProps_v1;
typedef CUmemPoolProps_v1 CUmemPoolProps;
typedef struct CUmemPoolPtrExportData_st {
	unsigned char reserved[64];
} CUmemPoolPtrExportData_v1;
typedef CUmemPoolPtrExportData_v1 CUmemPoolPtrExportData;
typedef enum CUmemcpyFlags_enum {
	CU_MEMCPY_FLAG_DEFAULT = 0x0,
	CU_MEMCPY_FLAG_PREFER_OVERLAP_WITH_COMPUTE = 0x1
} CUmemcpyFlags;
typedef enum CUmemcpySrcAccessOrder_enum {
	CU_MEMCPY_SRC_ACCESS_ORDER_INVALID = 0x0,
	CU_MEMCPY_SRC_ACCESS_ORDER_STREAM = 0x1,
	CU_MEMCPY_SRC_ACCESS_ORDER_DURING_API_CALL = 0x2,
	CU_MEMCPY_SRC_ACCESS_ORDER_ANY = 0x3,
	CU_MEMCPY_SRC_ACCESS_ORDER_MAX = 0x7FFFFFFF
} CUmemcpySrcAccessOrder;
typedef struct CUmemcpyAttributes_st {
	CUmemcpySrcAccessOrder srcAccessOrder;
	CUmemLocation srcLocHint;
	CUmemLocation dstLocHint;
	unsigned int flags;
} CUmemcpyAttributes_v1;
typedef CUmemcpyAttributes_v1 CUmemcpyAttributes;
typedef enum CUmemcpy3DOperandType_enum {
	CU_MEMCPY_OPERAND_TYPE_POINTER = 0x1,
	CU_MEMCPY_OPERAND_TYPE_ARRAY = 0x2,
	CU_MEMCPY_OPERAND_TYPE_MAX = 0x7FFFFFFF
} CUmemcpy3DOperandType;
typedef struct CUoffset3D_st {
	size_t x;
	size_t y;
	size_t z;
} CUoffset3D_v1;
typedef CUoffset3D_v1 CUoffset3D;
typedef struct CUextent3D_st {
	size_t width;
	size_t height;
	size_t depth;
} CUextent3D_v1;
typedef CUextent3D_v1 CUextent3D;
typedef struct CUmemcpy3DOperand_st {
	CUmemcpy3DOperandType type;
	union {
		struct {
			CUdeviceptr ptr;
			size_t rowLength;
			size_t layerHeight;
			CUmemLocation locHint;
		} ptr;
		struct {
			CUarray array;
			CUoffset3D offset;
		} array;
	} op;
} CUmemcpy3DOperand_v1;
typedef CUmemcpy3DOperand_v1 CUmemcpy3DOperand;
typedef struct CUDA_MEMCPY3D_BATCH_OP_st {
	CUmemcpy3DOperand src;
	CUmemcpy3DOperand dst;
	CUextent3D extent;
	CUmemcpySrcAccessOrder srcAccessOrder;
	unsigned int flags;
} CUDA_MEMCPY3D_BATCH_OP_v1;
typedef CUDA_MEMCPY3D_BATCH_OP_v1 CUDA_MEMCPY3D_BATCH_OP;
typedef struct CUDA_MEM_ALLOC_NODE_PARAMS_v1_st {
	CUmemPoolProps poolProps;
	const CUmemAccessDesc* accessDescs;
	size_t accessDescCount;
	size_t bytesize;
	CUdeviceptr dptr;
} CUDA_MEM_ALLOC_NODE_PARAMS_v1;
typedef CUDA_MEM_ALLOC_NODE_PARAMS_v1 CUDA_MEM_ALLOC_NODE_PARAMS;
typedef struct CUDA_MEM_ALLOC_NODE_PARAMS_v2_st {
	CUmemPoolProps poolProps;
	const CUmemAccessDesc* accessDescs;
	size_t accessDescCount;
	size_t bytesize;
	CUdeviceptr dptr;
} CUDA_MEM_ALLOC_NODE_PARAMS_v2;
typedef struct CUDA_MEM_FREE_NODE_PARAMS_st {
	CUdeviceptr dptr;
} CUDA_MEM_FREE_NODE_PARAMS;
typedef enum CUgraphMem_attribute_enum {
	CU_GRAPH_MEM_ATTR_USED_MEM_CURRENT,
	CU_GRAPH_MEM_ATTR_USED_MEM_HIGH,
	CU_GRAPH_MEM_ATTR_RESERVED_MEM_CURRENT,
	CU_GRAPH_MEM_ATTR_RESERVED_MEM_HIGH
} CUgraphMem_attribute;
typedef enum CUgraphChildGraphNodeOwnership_enum {
	CU_GRAPH_CHILD_GRAPH_OWNERSHIP_CLONE = 0,
	CU_GRAPH_CHILD_GRAPH_OWNERSHIP_MOVE = 1
} CUgraphChildGraphNodeOwnership;
typedef struct CUDA_CHILD_GRAPH_NODE_PARAMS_st {
	CUgraph graph;
	CUgraphChildGraphNodeOwnership ownership;
} CUDA_CHILD_GRAPH_NODE_PARAMS;
typedef struct CUDA_EVENT_RECORD_NODE_PARAMS_st {
	CUevent event;
} CUDA_EVENT_RECORD_NODE_PARAMS;
typedef struct CUDA_EVENT_WAIT_NODE_PARAMS_st {
	CUevent event;
} CUDA_EVENT_WAIT_NODE_PARAMS;
typedef struct CUgraphNodeParams_st {
	CUgraphNodeType type;
	int reserved0[3];
	union {
		long long reserved1[29];
		CUDA_KERNEL_NODE_PARAMS_v3 kernel;
		CUDA_MEMCPY_NODE_PARAMS memcpy;
		CUDA_MEMSET_NODE_PARAMS_v2 memset;
		CUDA_HOST_NODE_PARAMS_v2 host;
		CUDA_CHILD_GRAPH_NODE_PARAMS graph;
		CUDA_EVENT_WAIT_NODE_PARAMS eventWait;
		CUDA_EVENT_RECORD_NODE_PARAMS eventRecord;
		CUDA_EXT_SEM_SIGNAL_NODE_PARAMS_v2 extSemSignal;
		CUDA_EXT_SEM_WAIT_NODE_PARAMS_v2 extSemWait;
		CUDA_MEM_ALLOC_NODE_PARAMS_v2 alloc;
		CUDA_MEM_FREE_NODE_PARAMS free;
		CUDA_BATCH_MEM_OP_NODE_PARAMS_v2 memOp;
		CUDA_CONDITIONAL_NODE_PARAMS conditional;
	};
	long long reserved2;
} CUgraphNodeParams;
typedef enum CUflushGPUDirectRDMAWritesOptions_enum {
	CU_FLUSH_GPU_DIRECT_RDMA_WRITES_OPTION_HOST = 1 << 0,
	CU_FLUSH_GPU_DIRECT_RDMA_WRITES_OPTION_MEMOPS = 1 << 1
} CUflushGPUDirectRDMAWritesOptions;
typedef enum CUGPUDirectRDMAWritesOrdering_enum {
	CU_GPU_DIRECT_RDMA_WRITES_ORDERING_NONE = 0,
	CU_GPU_DIRECT_RDMA_WRITES_ORDERING_OWNER = 100,
	CU_GPU_DIRECT_RDMA_WRITES_ORDERING_ALL_DEVICES = 200
} CUGPUDirectRDMAWritesOrdering;
typedef enum CUflushGPUDirectRDMAWritesScope_enum {
	CU_FLUSH_GPU_DIRECT_RDMA_WRITES_TO_OWNER = 100,
	CU_FLUSH_GPU_DIRECT_RDMA_WRITES_TO_ALL_DEVICES = 200
} CUflushGPUDirectRDMAWritesScope;
typedef enum CUflushGPUDirectRDMAWritesTarget_enum {
	CU_FLUSH_GPU_DIRECT_RDMA_WRITES_TARGET_CURRENT_CTX = 0
} CUflushGPUDirectRDMAWritesTarget;
typedef enum CUgraphDebugDot_flags_enum {
	CU_GRAPH_DEBUG_DOT_FLAGS_VERBOSE = 1 << 0,
	CU_GRAPH_DEBUG_DOT_FLAGS_RUNTIME_TYPES = 1 << 1,
	CU_GRAPH_DEBUG_DOT_FLAGS_KERNEL_NODE_PARAMS = 1 << 2,
	CU_GRAPH_DEBUG_DOT_FLAGS_MEMCPY_NODE_PARAMS = 1 << 3,
	CU_GRAPH_DEBUG_DOT_FLAGS_MEMSET_NODE_PARAMS = 1 << 4,
	CU_GRAPH_DEBUG_DOT_FLAGS_HOST_NODE_PARAMS = 1 << 5,
	CU_GRAPH_DEBUG_DOT_FLAGS_EVENT_NODE_PARAMS = 1 << 6,
	CU_GRAPH_DEBUG_DOT_FLAGS_EXT_SEMAS_SIGNAL_NODE_PARAMS = 1 << 7,
	CU_GRAPH_DEBUG_DOT_FLAGS_EXT_SEMAS_WAIT_NODE_PARAMS = 1 << 8,
	CU_GRAPH_DEBUG_DOT_FLAGS_KERNEL_NODE_ATTRIBUTES = 1 << 9,
	CU_GRAPH_DEBUG_DOT_FLAGS_HANDLES = 1 << 10,
	CU_GRAPH_DEBUG_DOT_FLAGS_MEM_ALLOC_NODE_PARAMS = 1 << 11,
	CU_GRAPH_DEBUG_DOT_FLAGS_MEM_FREE_NODE_PARAMS = 1 << 12,
	CU_GRAPH_DEBUG_DOT_FLAGS_BATCH_MEM_OP_NODE_PARAMS = 1 << 13,
	CU_GRAPH_DEBUG_DOT_FLAGS_EXTRA_TOPO_INFO = 1 << 14,
	CU_GRAPH_DEBUG_DOT_FLAGS_CONDITIONAL_NODE_PARAMS = 1 << 15
} CUgraphDebugDot_flags;
typedef enum CUuserObject_flags_enum {
	CU_USER_OBJECT_NO_DESTRUCTOR_SYNC = 1
} CUuserObject_flags;
typedef enum CUuserObjectRetain_flags_enum {
	CU_GRAPH_USER_OBJECT_MOVE = 1
} CUuserObjectRetain_flags;
typedef enum CUgraphInstantiate_flags_enum {
	CUDA_GRAPH_INSTANTIATE_FLAG_AUTO_FREE_ON_LAUNCH = 1,
	CUDA_GRAPH_INSTANTIATE_FLAG_UPLOAD = 2,
	CUDA_GRAPH_INSTANTIATE_FLAG_DEVICE_LAUNCH = 4,
	CUDA_GRAPH_INSTANTIATE_FLAG_USE_NODE_PRIORITY = 8
} CUgraphInstantiate_flags;
typedef enum CUdeviceNumaConfig_enum {
	CU_DEVICE_NUMA_CONFIG_NONE = 0,
	CU_DEVICE_NUMA_CONFIG_NUMA_NODE
} CUdeviceNumaConfig;
typedef enum CUprocessState_enum {
	CU_PROCESS_STATE_RUNNING = 0,
	CU_PROCESS_STATE_LOCKED,
	CU_PROCESS_STATE_CHECKPOINTED,
	CU_PROCESS_STATE_FAILED
} CUprocessState;
typedef struct CUcheckpointLockArgs_st {
	unsigned int timeoutMs;
	unsigned int reserved0;
	cuuint64_t reserved1[7];
} CUcheckpointLockArgs;
typedef struct CUcheckpointCheckpointArgs_st {
	cuuint64_t reserved[8];
} CUcheckpointCheckpointArgs;
typedef struct CUcheckpointGpuPair_st {
	CUuuid oldUuid;
	CUuuid newUuid;
} CUcheckpointGpuPair;
typedef struct CUcheckpointRestoreArgs_st {
	CUcheckpointGpuPair* gpuPairs;
	unsigned int gpuPairsCount;
	char reserved[52 - sizeof(CUcheckpointGpuPair*)];
	cuuint64_t reserved1;
} CUcheckpointRestoreArgs;
typedef struct CUcheckpointUnlockArgs_st {
	cuuint64_t reserved[8];
} CUcheckpointUnlockArgs;
typedef enum CUmoduleLoadingMode_enum {
	CU_MODULE_EAGER_LOADING = 0x1,
	CU_MODULE_LAZY_LOADING = 0x2
} CUmoduleLoadingMode;
typedef enum CUmemDecompressAlgorithm_enum {
	CU_MEM_DECOMPRESS_UNSUPPORTED = 0,
	CU_MEM_DECOMPRESS_ALGORITHM_DEFLATE = 1 << 0,
	CU_MEM_DECOMPRESS_ALGORITHM_SNAPPY = 1 << 1,
	CU_MEM_DECOMPRESS_ALGORITHM_LZ4 = 1 << 2
} CUmemDecompressAlgorithm;
typedef struct CUmemDecompressParams_st {
	size_t srcNumBytes;
	size_t dstNumBytes;
	cuuint32_t* dstActBytes;
	const void* src;
	void* dst;
	CUmemDecompressAlgorithm algo;
	unsigned char padding[20];
} CUmemDecompressParams;
typedef enum CUfunctionLoadingState_enum {
	CU_FUNCTION_LOADING_STATE_UNLOADED = 0,
	CU_FUNCTION_LOADING_STATE_LOADED = 1,
	CU_FUNCTION_LOADING_STATE_MAX
} CUfunctionLoadingState;
typedef enum CUcoredumpSettings_enum {
	CU_COREDUMP_ENABLE_ON_EXCEPTION = 1,
	CU_COREDUMP_TRIGGER_HOST,
	CU_COREDUMP_LIGHTWEIGHT,
	CU_COREDUMP_ENABLE_USER_TRIGGER,
	CU_COREDUMP_FILE,
	CU_COREDUMP_PIPE,
	CU_COREDUMP_GENERATION_FLAGS,
	CU_COREDUMP_MAX
} CUcoredumpSettings;
typedef enum CUCoredumpGenerationFlags {
	CU_COREDUMP_DEFAULT_FLAGS = 0,
	CU_COREDUMP_SKIP_NONRELOCATED_ELF_IMAGES = 1 << 0,
	CU_COREDUMP_SKIP_GLOBAL_MEMORY = 1 << 1,
	CU_COREDUMP_SKIP_SHARED_MEMORY = 1 << 2,
	CU_COREDUMP_SKIP_LOCAL_MEMORY = 1 << 3,
	CU_COREDUMP_SKIP_ABORT = 1 << 4,
	CU_COREDUMP_SKIP_CONSTBANK_MEMORY = 1 << 5,
	CU_COREDUMP_GZIP_COMPRESS = 1 << 6,
	CU_COREDUMP_LIGHTWEIGHT_FLAGS = CU_COREDUMP_SKIP_NONRELOCATED_ELF_IMAGES | CU_COREDUMP_SKIP_GLOBAL_MEMORY | CU_COREDUMP_SKIP_SHARED_MEMORY | CU_COREDUMP_SKIP_LOCAL_MEMORY | CU_COREDUMP_SKIP_CONSTBANK_MEMORY
} CUCoredumpGenerationFlags;
typedef struct CUdevResourceDesc_st* CUdevResourceDesc;
typedef enum {
	CU_GREEN_CTX_DEFAULT_STREAM = 0x1
} CUgreenCtxCreate_flags;
typedef enum {
	CU_DEV_SM_RESOURCE_GROUP_DEFAULT = 0,
	CU_DEV_SM_RESOURCE_GROUP_BACKFILL = 0x1
} CUdevSmResourceGroup_flags;
typedef enum {
	CU_DEV_SM_RESOURCE_SPLIT_IGNORE_SM_COSCHEDULING = 0x1,
	CU_DEV_SM_RESOURCE_SPLIT_MAX_POTENTIAL_CLUSTER_SIZE = 0x2
} CUdevSmResourceSplitByCount_flags;
typedef enum {
	CU_DEV_RESOURCE_TYPE_INVALID = 0,
	CU_DEV_RESOURCE_TYPE_SM = 1,
	CU_DEV_RESOURCE_TYPE_WORKQUEUE_CONFIG = 1000,
	CU_DEV_RESOURCE_TYPE_WORKQUEUE = 10000
} CUdevResourceType;
typedef struct CUdevSmResource_st {
	unsigned int smCount;
	unsigned int minSmPartitionSize;
	unsigned int smCoscheduledAlignment;
	unsigned int flags;
} CUdevSmResource;
typedef enum {
	CU_WORKQUEUE_SCOPE_DEVICE_CTX = 0,
	CU_WORKQUEUE_SCOPE_GREEN_CTX_BALANCED = 1
} CUdevWorkqueueConfigScope;
typedef struct CUdevWorkqueueConfigResource_st {
	CUdevice device;
	unsigned int wqConcurrencyLimit;
	CUdevWorkqueueConfigScope sharingScope;
} CUdevWorkqueueConfigResource;
typedef struct CUdevWorkqueueResource_st {
	unsigned char reserved[40];
} CUdevWorkqueueResource;
typedef struct CU_DEV_SM_RESOURCE_GROUP_PARAMS_st {
	unsigned int smCount;
	unsigned int coscheduledSmCount;
	unsigned int preferredCoscheduledSmCount;
	unsigned int flags;
	unsigned int reserved[12];
} CU_DEV_SM_RESOURCE_GROUP_PARAMS;
typedef struct CUdevResource_st {
	CUdevResourceType type;
	unsigned char _internal_padding[92];
	union {
		CUdevSmResource sm;
		CUdevWorkqueueConfigResource wqConfig;
		CUdevWorkqueueResource wq;
		unsigned char _oversize[40];
	};
	struct CUdevResource_st* nextResource;
} CUdevResource_v1;
typedef CUdevResource_v1 CUdevResource;
typedef enum CUlogLevel_enum {
	CU_LOG_LEVEL_ERROR = 0,
	CU_LOG_LEVEL_WARNING = 1
} CUlogLevel;
typedef struct CUlogsCallbackEntry_st* CUlogsCallbackHandle;
typedef void (*CUlogsCallback)(void* data, CUlogLevel logLevel, char* message, size_t length);
typedef unsigned int CUlogIterator;
typedef enum CUGLDeviceList_enum {
	CU_GL_DEVICE_LIST_ALL = 0x01,
	CU_GL_DEVICE_LIST_CURRENT_FRAME = 0x02,
	CU_GL_DEVICE_LIST_NEXT_FRAME = 0x03
} CUGLDeviceList;
typedef enum CUGLmap_flags_enum {
	CU_GL_MAP_RESOURCE_FLAGS_NONE = 0x00,
	CU_GL_MAP_RESOURCE_FLAGS_READ_ONLY = 0x01,
	CU_GL_MAP_RESOURCE_FLAGS_WRITE_DISCARD = 0x02
} CUGLmap_flags;
typedef enum {
	NVRTC_SUCCESS = 0,
	NVRTC_ERROR_OUT_OF_MEMORY = 1,
	NVRTC_ERROR_PROGRAM_CREATION_FAILURE = 2,
	NVRTC_ERROR_INVALID_INPUT = 3,
	NVRTC_ERROR_INVALID_PROGRAM = 4,
	NVRTC_ERROR_INVALID_OPTION = 5,
	NVRTC_ERROR_COMPILATION = 6,
	NVRTC_ERROR_BUILTIN_OPERATION_FAILURE = 7,
	NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION = 8,
	NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION = 9,
	NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID = 10,
	NVRTC_ERROR_INTERNAL_ERROR = 11,
	NVRTC_ERROR_TIME_FILE_WRITE_FAILED = 12,
	NVRTC_ERROR_NO_PCH_CREATE_ATTEMPTED = 13,
	NVRTC_ERROR_PCH_CREATE_HEAP_EXHAUSTED = 14,
	NVRTC_ERROR_PCH_CREATE = 15,
	NVRTC_ERROR_CANCELLED = 16,
	NVRTC_ERROR_TIME_TRACE_FILE_WRITE_FAILED = 17
} nvrtcResult;
typedef struct _nvrtcProgram* nvrtcProgram;