#pragma once

#ifndef ROCCU_DEFINE_FUNC
#define ROCCU_DEFINE_FUNC(...)
#endif

ROCCU_DEFINE_FUNC(cuArray3DCreate, CU_DRIVER, cuArray3DCreate_v2, NOOP, CUresult, (CUarray* pHandle, const CUDA_ARRAY3D_DESCRIPTOR* pAllocateArray));
ROCCU_DEFINE_FUNC(cuArray3DGetDescriptor, CU_DRIVER, cuArray3DGetDescriptor_v2, NOOP, CUresult, (CUDA_ARRAY3D_DESCRIPTOR* pArrayDescriptor, CUarray hArray));
ROCCU_DEFINE_FUNC(cuArrayCreate, CU_DRIVER, cuArrayCreate_v2, NOOP, CUresult, (CUarray* pHandle, const CUDA_ARRAY_DESCRIPTOR* pAllocateArray));
ROCCU_DEFINE_FUNC(cuArrayDestroy, CU_DRIVER, cuArrayDestroy, NOOP, CUresult, (CUarray hArray));
ROCCU_DEFINE_FUNC(cuArrayGetDescriptor, CU_DRIVER, cuArrayGetDescriptor_v2, NOOP, CUresult, (CUDA_ARRAY_DESCRIPTOR* pArrayDescriptor, CUarray hArray));
ROCCU_DEFINE_FUNC(cuArrayGetMemoryRequirements, CU_DRIVER, cuArrayGetMemoryRequirements, NOOP, CUresult, (CUDA_ARRAY_MEMORY_REQUIREMENTS* memoryRequirements, CUarray array, CUdevice device));
ROCCU_DEFINE_FUNC(cuArrayGetPlane, CU_DRIVER, cuArrayGetPlane, NOOP, CUresult, (CUarray* pPlaneArray, CUarray hArray, unsigned int planeIdx));
ROCCU_DEFINE_FUNC(cuArrayGetSparseProperties, CU_DRIVER, cuArrayGetSparseProperties, NOOP, CUresult, (CUDA_ARRAY_SPARSE_PROPERTIES* sparseProperties, CUarray array));
ROCCU_DEFINE_FUNC(cuCheckpointProcessCheckpoint, CU_DRIVER, cuCheckpointProcessCheckpoint, NOOP, CUresult, (int pid, CUcheckpointCheckpointArgs* args));
ROCCU_DEFINE_FUNC(cuCheckpointProcessGetRestoreThreadId, CU_DRIVER, cuCheckpointProcessGetRestoreThreadId, NOOP, CUresult, (int pid, int* tid));
ROCCU_DEFINE_FUNC(cuCheckpointProcessGetState, CU_DRIVER, cuCheckpointProcessGetState, NOOP, CUresult, (int pid, CUprocessState* state));
ROCCU_DEFINE_FUNC(cuCheckpointProcessLock, CU_DRIVER, cuCheckpointProcessLock, NOOP, CUresult, (int pid, CUcheckpointLockArgs* args));
ROCCU_DEFINE_FUNC(cuCheckpointProcessRestore, CU_DRIVER, cuCheckpointProcessRestore, NOOP, CUresult, (int pid, CUcheckpointRestoreArgs* args));
ROCCU_DEFINE_FUNC(cuCheckpointProcessUnlock, CU_DRIVER, cuCheckpointProcessUnlock, NOOP, CUresult, (int pid, CUcheckpointUnlockArgs* args));
ROCCU_DEFINE_FUNC(cuCoredumpGetAttribute, CU_DRIVER, cuCoredumpGetAttribute, NOOP, CUresult, (CUcoredumpSettings attrib, void* value, size_t* size));
ROCCU_DEFINE_FUNC(cuCoredumpGetAttributeGlobal, CU_DRIVER, cuCoredumpGetAttributeGlobal, NOOP, CUresult, (CUcoredumpSettings attrib, void* value, size_t* size));
ROCCU_DEFINE_FUNC(cuCoredumpSetAttribute, CU_DRIVER, cuCoredumpSetAttribute, NOOP, CUresult, (CUcoredumpSettings attrib, void* value, size_t* size));
ROCCU_DEFINE_FUNC(cuCoredumpSetAttributeGlobal, CU_DRIVER, cuCoredumpSetAttributeGlobal, NOOP, CUresult, (CUcoredumpSettings attrib, void* value, size_t* size));
ROCCU_DEFINE_FUNC(cuCtxCreate, CU_DRIVER, cuCtxCreate_v4, NOOP, CUresult, (CUcontext* pctx, CUctxCreateParams* ctxCreateParams, unsigned int flags, CUdevice dev));
ROCCU_DEFINE_FUNC(cuCtxDestroy, CU_DRIVER, cuCtxDestroy_v2, NOOP, CUresult, (CUcontext ctx));
ROCCU_DEFINE_FUNC(cuCtxDisablePeerAccess, CU_DRIVER, cuCtxDisablePeerAccess, NOOP, CUresult, (CUcontext peerContext));
ROCCU_DEFINE_FUNC(cuCtxEnablePeerAccess, CU_DRIVER, cuCtxEnablePeerAccess, NOOP, CUresult, (CUcontext peerContext, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuCtxFromGreenCtx, CU_DRIVER, cuCtxFromGreenCtx, NOOP, CUresult, (CUcontext* pContext, CUgreenCtx hCtx));
ROCCU_DEFINE_FUNC(cuCtxGetApiVersion, CU_DRIVER, cuCtxGetApiVersion, NOOP, CUresult, (CUcontext ctx, unsigned int* version));
ROCCU_DEFINE_FUNC(cuCtxGetCacheConfig, CU_DRIVER, cuCtxGetCacheConfig, NOOP, CUresult, (CUfunc_cache* pconfig));
ROCCU_DEFINE_FUNC(cuCtxGetCurrent, CU_DRIVER, cuCtxGetCurrent, NOOP, CUresult, (CUcontext* pctx));
ROCCU_DEFINE_FUNC(cuCtxGetDevResource, CU_DRIVER, cuCtxGetDevResource, NOOP, CUresult, (CUcontext hCtx, CUdevResource* resource, CUdevResourceType type));
ROCCU_DEFINE_FUNC(cuCtxGetDevice, CU_DRIVER, cuCtxGetDevice, NOOP, CUresult, (CUdevice* device));
ROCCU_DEFINE_FUNC(cuCtxGetDevice_v2, CU_DRIVER, cuCtxGetDevice_v2, NOOP, CUresult, (CUdevice* device, CUcontext ctx));
ROCCU_DEFINE_FUNC(cuCtxGetExecAffinity, CU_DRIVER, cuCtxGetExecAffinity, NOOP, CUresult, (CUexecAffinityParam* pExecAffinity, CUexecAffinityType type));
ROCCU_DEFINE_FUNC(cuCtxGetFlags, CU_DRIVER, cuCtxGetFlags, NOOP, CUresult, (unsigned int* flags));
ROCCU_DEFINE_FUNC(cuCtxGetId, CU_DRIVER, cuCtxGetId, NOOP, CUresult, (CUcontext ctx, unsigned long long* ctxId));
ROCCU_DEFINE_FUNC(cuCtxGetLimit, CU_DRIVER, cuCtxGetLimit, NOOP, CUresult, (size_t* pvalue, CUlimit limit));
ROCCU_DEFINE_FUNC(cuCtxGetStreamPriorityRange, CU_DRIVER, cuCtxGetStreamPriorityRange, NOOP, CUresult, (int* leastPriority, int* greatestPriority));
ROCCU_DEFINE_FUNC(cuCtxPopCurrent, CU_DRIVER, cuCtxPopCurrent_v2, NOOP, CUresult, (CUcontext* pctx));
ROCCU_DEFINE_FUNC(cuCtxPushCurrent, CU_DRIVER, cuCtxPushCurrent_v2, NOOP, CUresult, (CUcontext ctx));
ROCCU_DEFINE_FUNC(cuCtxRecordEvent, CU_DRIVER, cuCtxRecordEvent, NOOP, CUresult, (CUcontext hCtx, CUevent hEvent));
ROCCU_DEFINE_FUNC(cuCtxResetPersistingL2Cache, CU_DRIVER, cuCtxResetPersistingL2Cache, NOOP, CUresult, (void));
ROCCU_DEFINE_FUNC(cuCtxSetCacheConfig, CU_DRIVER, cuCtxSetCacheConfig, NOOP, CUresult, (CUfunc_cache config));
ROCCU_DEFINE_FUNC(cuCtxSetCurrent, CU_DRIVER, cuCtxSetCurrent, NOOP, CUresult, (CUcontext ctx));
ROCCU_DEFINE_FUNC(cuCtxSetFlags, CU_DRIVER, cuCtxSetFlags, NOOP, CUresult, (unsigned int flags));
ROCCU_DEFINE_FUNC(cuCtxSetLimit, CU_DRIVER, cuCtxSetLimit, NOOP, CUresult, (CUlimit limit, size_t value));
ROCCU_DEFINE_FUNC(cuCtxSynchronize, CU_DRIVER, cuCtxSynchronize, NOOP, CUresult, (void));
ROCCU_DEFINE_FUNC(cuCtxSynchronize_v2, CU_DRIVER, cuCtxSynchronize_v2, NOOP, CUresult, (CUcontext ctx));
ROCCU_DEFINE_FUNC(cuCtxWaitEvent, CU_DRIVER, cuCtxWaitEvent, NOOP, CUresult, (CUcontext hCtx, CUevent hEvent));
ROCCU_DEFINE_FUNC(cuDestroyExternalMemory, CU_DRIVER, cuDestroyExternalMemory, NOOP, CUresult, (CUexternalMemory extMem));
ROCCU_DEFINE_FUNC(cuDestroyExternalSemaphore, CU_DRIVER, cuDestroyExternalSemaphore, NOOP, CUresult, (CUexternalSemaphore extSem));
ROCCU_DEFINE_FUNC(cuDevResourceGenerateDesc, CU_DRIVER, cuDevResourceGenerateDesc, NOOP, CUresult, (CUdevResourceDesc* phDesc, CUdevResource* resources, unsigned int nbResources));
ROCCU_DEFINE_FUNC(cuDevSmResourceSplit, CU_DRIVER, cuDevSmResourceSplit, NOOP, CUresult, (CUdevResource* result, unsigned int nbGroups, const CUdevResource* input, CUdevResource* remainder, unsigned int flags, CU_DEV_SM_RESOURCE_GROUP_PARAMS* groupParams));
ROCCU_DEFINE_FUNC(cuDevSmResourceSplitByCount, CU_DRIVER, cuDevSmResourceSplitByCount, NOOP, CUresult, (CUdevResource* result, unsigned int* nbGroups, const CUdevResource* input, CUdevResource* remainder, unsigned int flags, unsigned int minCount));
ROCCU_DEFINE_FUNC(cuDeviceCanAccessPeer, CU_DRIVER, cuDeviceCanAccessPeer, NOOP, CUresult, (int* canAccessPeer, CUdevice dev, CUdevice peerDev));
ROCCU_DEFINE_FUNC(cuDeviceGet, CU_DRIVER, cuDeviceGet, NOOP, CUresult, (CUdevice* device, int ordinal));
ROCCU_DEFINE_FUNC(cuDeviceGetAttribute, CU_DRIVER, cuDeviceGetAttribute, NOOP, CUresult, (int* pi, CUdevice_attribute attrib, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetByPCIBusId, CU_DRIVER, cuDeviceGetByPCIBusId, NOOP, CUresult, (CUdevice* dev, const char* pciBusId));
ROCCU_DEFINE_FUNC(cuDeviceGetCount, CU_DRIVER, cuDeviceGetCount, NOOP, CUresult, (int* count));
ROCCU_DEFINE_FUNC(cuDeviceGetDefaultMemPool, CU_DRIVER, cuDeviceGetDefaultMemPool, NOOP, CUresult, (CUmemoryPool* pool_out, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetDevResource, CU_DRIVER, cuDeviceGetDevResource, NOOP, CUresult, (CUdevice device, CUdevResource* resource, CUdevResourceType type));
ROCCU_DEFINE_FUNC(cuDeviceGetExecAffinitySupport, CU_DRIVER, cuDeviceGetExecAffinitySupport, NOOP, CUresult, (int* pi, CUexecAffinityType type, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetGraphMemAttribute, CU_DRIVER, cuDeviceGetGraphMemAttribute, NOOP, CUresult, (CUdevice device, CUgraphMem_attribute attr, void* value));
ROCCU_DEFINE_FUNC(cuDeviceGetHostAtomicCapabilities, CU_DRIVER, cuDeviceGetHostAtomicCapabilities, NOOP, CUresult, (unsigned int* capabilities, const CUatomicOperation* operations, unsigned int count, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetLuid, CU_DRIVER, cuDeviceGetLuid, NOOP, CUresult, (char* luid, unsigned int* deviceNodeMask, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetMemPool, CU_DRIVER, cuDeviceGetMemPool, NOOP, CUresult, (CUmemoryPool* pool, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetName, CU_DRIVER, cuDeviceGetName, NOOP, CUresult, (char* name, int len, CUdevice dev));
//ROCCU_DEFINE_FUNC(cuDeviceGetNvSciSyncAttributes, CU_DRIVER, cuDeviceGetNvSciSyncAttributes, NOOP, CUresult, (void* nvSciSyncAttrList, CUdevice dev, int flags));
ROCCU_DEFINE_FUNC(cuDeviceGetP2PAtomicCapabilities, CU_DRIVER, cuDeviceGetP2PAtomicCapabilities, NOOP, CUresult, (unsigned int* capabilities, const CUatomicOperation* operations, unsigned int count, CUdevice srcDevice, CUdevice dstDevice));
ROCCU_DEFINE_FUNC(cuDeviceGetP2PAttribute, CU_DRIVER, cuDeviceGetP2PAttribute, NOOP, CUresult, (int* value, CUdevice_P2PAttribute attrib, CUdevice srcDevice, CUdevice dstDevice));
ROCCU_DEFINE_FUNC(cuDeviceGetPCIBusId, CU_DRIVER, cuDeviceGetPCIBusId, NOOP, CUresult, (char* pciBusId, int len, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetTexture1DLinearMaxWidth, CU_DRIVER, cuDeviceGetTexture1DLinearMaxWidth, NOOP, CUresult, (size_t* maxWidthInElements, CUarray_format format, unsigned numChannels, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGetUuid, CU_DRIVER, cuDeviceGetUuid_v2, NOOP, CUresult, (CUuuid* uuid, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceGraphMemTrim, CU_DRIVER, cuDeviceGraphMemTrim, NOOP, CUresult, (CUdevice device));
ROCCU_DEFINE_FUNC(cuDevicePrimaryCtxGetState, CU_DRIVER, cuDevicePrimaryCtxGetState, NOOP, CUresult, (CUdevice dev, unsigned int* flags, int* active));
ROCCU_DEFINE_FUNC(cuDevicePrimaryCtxRelease, CU_DRIVER, cuDevicePrimaryCtxRelease_v2, NOOP, CUresult, (CUdevice dev));
ROCCU_DEFINE_FUNC(cuDevicePrimaryCtxReset, CU_DRIVER, cuDevicePrimaryCtxReset_v2, NOOP, CUresult, (CUdevice dev));
ROCCU_DEFINE_FUNC(cuDevicePrimaryCtxRetain, CU_DRIVER, cuDevicePrimaryCtxRetain, NOOP, CUresult, (CUcontext* pctx, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDevicePrimaryCtxSetFlags, CU_DRIVER, cuDevicePrimaryCtxSetFlags_v2, NOOP, CUresult, (CUdevice dev, unsigned int flags));
ROCCU_DEFINE_FUNC(cuDeviceRegisterAsyncNotification, CU_DRIVER, cuDeviceRegisterAsyncNotification, NOOP, CUresult, (CUdevice device, CUasyncCallback callbackFunc, void* userData, CUasyncCallbackHandle* callback));
ROCCU_DEFINE_FUNC(cuDeviceSetGraphMemAttribute, CU_DRIVER, cuDeviceSetGraphMemAttribute, NOOP, CUresult, (CUdevice device, CUgraphMem_attribute attr, void* value));
ROCCU_DEFINE_FUNC(cuDeviceSetMemPool, CU_DRIVER, cuDeviceSetMemPool, NOOP, CUresult, (CUdevice dev, CUmemoryPool pool));
ROCCU_DEFINE_FUNC(cuDeviceTotalMem, CU_DRIVER, cuDeviceTotalMem_v2, NOOP, CUresult, (size_t* bytes, CUdevice dev));
ROCCU_DEFINE_FUNC(cuDeviceUnregisterAsyncNotification, CU_DRIVER, cuDeviceUnregisterAsyncNotification, NOOP, CUresult, (CUdevice device, CUasyncCallbackHandle callback));
ROCCU_DEFINE_FUNC(cuDriverGetVersion, CU_DRIVER, cuDriverGetVersion, NOOP, CUresult, (int* driverVersion));
ROCCU_DEFINE_FUNC(cuEventCreate, CU_DRIVER, cuEventCreate, NOOP, CUresult, (CUevent* phEvent, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuEventDestroy, CU_DRIVER, cuEventDestroy_v2, NOOP, CUresult, (CUevent hEvent));
ROCCU_DEFINE_FUNC(cuEventElapsedTime, CU_DRIVER, cuEventElapsedTime_v2, NOOP, CUresult, (float* pMilliseconds, CUevent hStart, CUevent hEnd));
ROCCU_DEFINE_FUNC(cuEventQuery, CU_DRIVER, cuEventQuery, NOOP, CUresult, (CUevent hEvent));
ROCCU_DEFINE_FUNC(cuEventRecord, CU_DRIVER, cuEventRecord_ptsz, NOOP, CUresult, (CUevent hEvent, CUstream hStream));
ROCCU_DEFINE_FUNC(cuEventRecordWithFlags, CU_DRIVER, cuEventRecordWithFlags_ptsz, NOOP, CUresult, (CUevent hEvent, CUstream hStream, unsigned int flags));
ROCCU_DEFINE_FUNC(cuEventSynchronize, CU_DRIVER, cuEventSynchronize, NOOP, CUresult, (CUevent hEvent));
ROCCU_DEFINE_FUNC(cuExternalMemoryGetMappedBuffer, CU_DRIVER, cuExternalMemoryGetMappedBuffer, NOOP, CUresult, (CUdeviceptr* devPtr, CUexternalMemory extMem, const CUDA_EXTERNAL_MEMORY_BUFFER_DESC* bufferDesc));
ROCCU_DEFINE_FUNC(cuExternalMemoryGetMappedMipmappedArray, CU_DRIVER, cuExternalMemoryGetMappedMipmappedArray, NOOP, CUresult, (CUmipmappedArray* mipmap, CUexternalMemory extMem, const CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC* mipmapDesc));
ROCCU_DEFINE_FUNC(cuFlushGPUDirectRDMAWrites, CU_DRIVER, cuFlushGPUDirectRDMAWrites, NOOP, CUresult, (CUflushGPUDirectRDMAWritesTarget target, CUflushGPUDirectRDMAWritesScope scope));
ROCCU_DEFINE_FUNC(cuFuncGetAttribute, CU_DRIVER, cuFuncGetAttribute, NOOP, CUresult, (int* pi, CUfunction_attribute attrib, CUfunction hfunc));
ROCCU_DEFINE_FUNC(cuFuncGetModule, CU_DRIVER, cuFuncGetModule, NOOP, CUresult, (CUmodule* hmod, CUfunction hfunc));
ROCCU_DEFINE_FUNC(cuFuncGetName, CU_DRIVER, cuFuncGetName, NOOP, CUresult, (const char** name, CUfunction hfunc));
ROCCU_DEFINE_FUNC(cuFuncGetParamInfo, CU_DRIVER, cuFuncGetParamInfo, NOOP, CUresult, (CUfunction func, size_t paramIndex, size_t* paramOffset, size_t* paramSize));
ROCCU_DEFINE_FUNC(cuFuncIsLoaded, CU_DRIVER, cuFuncIsLoaded, NOOP, CUresult, (CUfunctionLoadingState* state, CUfunction function));
ROCCU_DEFINE_FUNC(cuFuncLoad, CU_DRIVER, cuFuncLoad, NOOP, CUresult, (CUfunction function));
ROCCU_DEFINE_FUNC(cuFuncSetAttribute, CU_DRIVER, cuFuncSetAttribute, NOOP, CUresult, (CUfunction hfunc, CUfunction_attribute attrib, int value));
ROCCU_DEFINE_FUNC(cuFuncSetCacheConfig, CU_DRIVER, cuFuncSetCacheConfig, NOOP, CUresult, (CUfunction hfunc, CUfunc_cache config));
ROCCU_DEFINE_FUNC(cuGLGetDevices, CU_DRIVER, cuGLGetDevices_v2, NOOP, CUresult, (unsigned int* pCudaDeviceCount, CUdevice* pCudaDevices, unsigned int cudaDeviceCount, CUGLDeviceList deviceList));
ROCCU_DEFINE_FUNC(cuGetErrorName, CU_DRIVER, cuGetErrorName, NOOP, CUresult, (CUresult error, const char** pStr));
ROCCU_DEFINE_FUNC(cuGetErrorString, CU_DRIVER, cuGetErrorString, NOOP, CUresult, (CUresult error, const char** pStr));
ROCCU_DEFINE_FUNC(cuGetExportTable, CU_DRIVER, cuGetExportTable, NOOP, CUresult, (const void** ppExportTable, const CUuuid* pExportTableId));
ROCCU_DEFINE_FUNC(cuGetProcAddress, CU_DRIVER, cuGetProcAddress_v2, NOOP, CUresult, (const char* symbol, void** pfn, int cudaVersion, cuuint64_t flags, CUdriverProcAddressQueryResult* symbolStatus));
ROCCU_DEFINE_FUNC(cuGraphAddBatchMemOpNode, CU_DRIVER, cuGraphAddBatchMemOpNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, const CUDA_BATCH_MEM_OP_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphAddChildGraphNode, CU_DRIVER, cuGraphAddChildGraphNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, CUgraph childGraph));
ROCCU_DEFINE_FUNC(cuGraphAddDependencies, CU_DRIVER, cuGraphAddDependencies_v2, NOOP, CUresult, (CUgraph hGraph, const CUgraphNode* from, const CUgraphNode* to, const CUgraphEdgeData* edgeData, size_t numDependencies));
ROCCU_DEFINE_FUNC(cuGraphAddEmptyNode, CU_DRIVER, cuGraphAddEmptyNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies));
ROCCU_DEFINE_FUNC(cuGraphAddEventRecordNode, CU_DRIVER, cuGraphAddEventRecordNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, CUevent event));
ROCCU_DEFINE_FUNC(cuGraphAddEventWaitNode, CU_DRIVER, cuGraphAddEventWaitNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, CUevent event));
ROCCU_DEFINE_FUNC(cuGraphAddExternalSemaphoresSignalNode, CU_DRIVER, cuGraphAddExternalSemaphoresSignalNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphAddExternalSemaphoresWaitNode, CU_DRIVER, cuGraphAddExternalSemaphoresWaitNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, const CUDA_EXT_SEM_WAIT_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphAddHostNode, CU_DRIVER, cuGraphAddHostNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, const CUDA_HOST_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphAddKernelNode, CU_DRIVER, cuGraphAddKernelNode_v2, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, const CUDA_KERNEL_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphAddMemAllocNode, CU_DRIVER, cuGraphAddMemAllocNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, CUDA_MEM_ALLOC_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphAddMemFreeNode, CU_DRIVER, cuGraphAddMemFreeNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, CUdeviceptr dptr));
ROCCU_DEFINE_FUNC(cuGraphAddMemcpyNode, CU_DRIVER, cuGraphAddMemcpyNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, const CUDA_MEMCPY3D* copyParams, CUcontext ctx));
ROCCU_DEFINE_FUNC(cuGraphAddMemsetNode, CU_DRIVER, cuGraphAddMemsetNode, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, size_t numDependencies, const CUDA_MEMSET_NODE_PARAMS* memsetParams, CUcontext ctx));
ROCCU_DEFINE_FUNC(cuGraphAddNode, CU_DRIVER, cuGraphAddNode_v2, NOOP, CUresult, (CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, const CUgraphEdgeData* dependencyData, size_t numDependencies, CUgraphNodeParams* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphBatchMemOpNodeGetParams, CU_DRIVER, cuGraphBatchMemOpNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUDA_BATCH_MEM_OP_NODE_PARAMS* nodeParams_out));
ROCCU_DEFINE_FUNC(cuGraphBatchMemOpNodeSetParams, CU_DRIVER, cuGraphBatchMemOpNodeSetParams, NOOP, CUresult, (CUgraphNode hNode, const CUDA_BATCH_MEM_OP_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphChildGraphNodeGetGraph, CU_DRIVER, cuGraphChildGraphNodeGetGraph, NOOP, CUresult, (CUgraphNode hNode, CUgraph* phGraph));
ROCCU_DEFINE_FUNC(cuGraphClone, CU_DRIVER, cuGraphClone, NOOP, CUresult, (CUgraph* phGraphClone, CUgraph originalGraph));
ROCCU_DEFINE_FUNC(cuGraphConditionalHandleCreate, CU_DRIVER, cuGraphConditionalHandleCreate, NOOP, CUresult, (CUgraphConditionalHandle* pHandle_out, CUgraph hGraph, CUcontext ctx, unsigned int defaultLaunchValue, unsigned int flags));
ROCCU_DEFINE_FUNC(cuGraphCreate, CU_DRIVER, cuGraphCreate, NOOP, CUresult, (CUgraph* phGraph, unsigned int flags));
ROCCU_DEFINE_FUNC(cuGraphDebugDotPrint, CU_DRIVER, cuGraphDebugDotPrint, NOOP, CUresult, (CUgraph hGraph, const char* path, unsigned int flags));
ROCCU_DEFINE_FUNC(cuGraphDestroy, CU_DRIVER, cuGraphDestroy, NOOP, CUresult, (CUgraph hGraph));
ROCCU_DEFINE_FUNC(cuGraphDestroyNode, CU_DRIVER, cuGraphDestroyNode, NOOP, CUresult, (CUgraphNode hNode));
ROCCU_DEFINE_FUNC(cuGraphEventRecordNodeGetEvent, CU_DRIVER, cuGraphEventRecordNodeGetEvent, NOOP, CUresult, (CUgraphNode hNode, CUevent* event_out));
ROCCU_DEFINE_FUNC(cuGraphEventRecordNodeSetEvent, CU_DRIVER, cuGraphEventRecordNodeSetEvent, NOOP, CUresult, (CUgraphNode hNode, CUevent event));
ROCCU_DEFINE_FUNC(cuGraphEventWaitNodeGetEvent, CU_DRIVER, cuGraphEventWaitNodeGetEvent, NOOP, CUresult, (CUgraphNode hNode, CUevent* event_out));
ROCCU_DEFINE_FUNC(cuGraphEventWaitNodeSetEvent, CU_DRIVER, cuGraphEventWaitNodeSetEvent, NOOP, CUresult, (CUgraphNode hNode, CUevent event));
ROCCU_DEFINE_FUNC(cuGraphExecBatchMemOpNodeSetParams, CU_DRIVER, cuGraphExecBatchMemOpNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, const CUDA_BATCH_MEM_OP_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphExecChildGraphNodeSetParams, CU_DRIVER, cuGraphExecChildGraphNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, CUgraph childGraph));
ROCCU_DEFINE_FUNC(cuGraphExecDestroy, CU_DRIVER, cuGraphExecDestroy, NOOP, CUresult, (CUgraphExec hGraphExec));
ROCCU_DEFINE_FUNC(cuGraphExecEventRecordNodeSetEvent, CU_DRIVER, cuGraphExecEventRecordNodeSetEvent, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, CUevent event));
ROCCU_DEFINE_FUNC(cuGraphExecEventWaitNodeSetEvent, CU_DRIVER, cuGraphExecEventWaitNodeSetEvent, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, CUevent event));
ROCCU_DEFINE_FUNC(cuGraphExecExternalSemaphoresSignalNodeSetParams, CU_DRIVER, cuGraphExecExternalSemaphoresSignalNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphExecExternalSemaphoresWaitNodeSetParams, CU_DRIVER, cuGraphExecExternalSemaphoresWaitNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, const CUDA_EXT_SEM_WAIT_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphExecGetFlags, CU_DRIVER, cuGraphExecGetFlags, NOOP, CUresult, (CUgraphExec hGraphExec, cuuint64_t* flags));
ROCCU_DEFINE_FUNC(cuGraphExecGetId, CU_DRIVER, cuGraphExecGetId, NOOP, CUresult, (CUgraphExec hGraphExec, unsigned int* graphId));
ROCCU_DEFINE_FUNC(cuGraphExecHostNodeSetParams, CU_DRIVER, cuGraphExecHostNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, const CUDA_HOST_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphExecKernelNodeSetParams, CU_DRIVER, cuGraphExecKernelNodeSetParams_v2, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, const CUDA_KERNEL_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphExecMemcpyNodeSetParams, CU_DRIVER, cuGraphExecMemcpyNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, const CUDA_MEMCPY3D* copyParams, CUcontext ctx));
ROCCU_DEFINE_FUNC(cuGraphExecMemsetNodeSetParams, CU_DRIVER, cuGraphExecMemsetNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, const CUDA_MEMSET_NODE_PARAMS* memsetParams, CUcontext ctx));
ROCCU_DEFINE_FUNC(cuGraphExecNodeSetParams, CU_DRIVER, cuGraphExecNodeSetParams, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, CUgraphNodeParams* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphExecUpdate, CU_DRIVER, cuGraphExecUpdate_v2, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraph hGraph, CUgraphExecUpdateResultInfo* resultInfo));
ROCCU_DEFINE_FUNC(cuGraphExternalSemaphoresSignalNodeGetParams, CU_DRIVER, cuGraphExternalSemaphoresSignalNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUDA_EXT_SEM_SIGNAL_NODE_PARAMS* params_out));
ROCCU_DEFINE_FUNC(cuGraphExternalSemaphoresSignalNodeSetParams, CU_DRIVER, cuGraphExternalSemaphoresSignalNodeSetParams, NOOP, CUresult, (CUgraphNode hNode, const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphExternalSemaphoresWaitNodeGetParams, CU_DRIVER, cuGraphExternalSemaphoresWaitNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUDA_EXT_SEM_WAIT_NODE_PARAMS* params_out));
ROCCU_DEFINE_FUNC(cuGraphExternalSemaphoresWaitNodeSetParams, CU_DRIVER, cuGraphExternalSemaphoresWaitNodeSetParams, NOOP, CUresult, (CUgraphNode hNode, const CUDA_EXT_SEM_WAIT_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphGetEdges, CU_DRIVER, cuGraphGetEdges_v2, NOOP, CUresult, (CUgraph hGraph, CUgraphNode* from, CUgraphNode* to, CUgraphEdgeData* edgeData, size_t* numEdges));
ROCCU_DEFINE_FUNC(cuGraphGetId, CU_DRIVER, cuGraphGetId, NOOP, CUresult, (CUgraph hGraph, unsigned int* graphId));
ROCCU_DEFINE_FUNC(cuGraphGetNodes, CU_DRIVER, cuGraphGetNodes, NOOP, CUresult, (CUgraph hGraph, CUgraphNode* nodes, size_t* numNodes));
ROCCU_DEFINE_FUNC(cuGraphGetRootNodes, CU_DRIVER, cuGraphGetRootNodes, NOOP, CUresult, (CUgraph hGraph, CUgraphNode* rootNodes, size_t* numRootNodes));
ROCCU_DEFINE_FUNC(cuGraphHostNodeGetParams, CU_DRIVER, cuGraphHostNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUDA_HOST_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphHostNodeSetParams, CU_DRIVER, cuGraphHostNodeSetParams, NOOP, CUresult, (CUgraphNode hNode, const CUDA_HOST_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphInstantiateWithFlags, CU_DRIVER, cuGraphInstantiateWithFlags, NOOP, CUresult, (CUgraphExec* phGraphExec, CUgraph hGraph, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuGraphInstantiateWithParams, CU_DRIVER, cuGraphInstantiateWithParams_ptsz, NOOP, CUresult, (CUgraphExec* phGraphExec, CUgraph hGraph, CUDA_GRAPH_INSTANTIATE_PARAMS* instantiateParams));
ROCCU_DEFINE_FUNC(cuGraphKernelNodeCopyAttributes, CU_DRIVER, cuGraphKernelNodeCopyAttributes, NOOP, CUresult, (CUgraphNode dst, CUgraphNode src));
ROCCU_DEFINE_FUNC(cuGraphKernelNodeGetAttribute, CU_DRIVER, cuGraphKernelNodeGetAttribute, NOOP, CUresult, (CUgraphNode hNode, CUkernelNodeAttrID attr, CUkernelNodeAttrValue* value_out));
ROCCU_DEFINE_FUNC(cuGraphKernelNodeGetParams, CU_DRIVER, cuGraphKernelNodeGetParams_v2, NOOP, CUresult, (CUgraphNode hNode, CUDA_KERNEL_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphKernelNodeSetAttribute, CU_DRIVER, cuGraphKernelNodeSetAttribute, NOOP, CUresult, (CUgraphNode hNode, CUkernelNodeAttrID attr, const CUkernelNodeAttrValue* value));
ROCCU_DEFINE_FUNC(cuGraphKernelNodeSetParams, CU_DRIVER, cuGraphKernelNodeSetParams_v2, NOOP, CUresult, (CUgraphNode hNode, const CUDA_KERNEL_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphLaunch, CU_DRIVER, cuGraphLaunch_ptsz, NOOP, CUresult, (CUgraphExec hGraphExec, CUstream hStream));
ROCCU_DEFINE_FUNC(cuGraphMemAllocNodeGetParams, CU_DRIVER, cuGraphMemAllocNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUDA_MEM_ALLOC_NODE_PARAMS* params_out));
ROCCU_DEFINE_FUNC(cuGraphMemFreeNodeGetParams, CU_DRIVER, cuGraphMemFreeNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUdeviceptr* dptr_out));
ROCCU_DEFINE_FUNC(cuGraphMemcpyNodeGetParams, CU_DRIVER, cuGraphMemcpyNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUDA_MEMCPY3D* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphMemcpyNodeSetParams, CU_DRIVER, cuGraphMemcpyNodeSetParams, NOOP, CUresult, (CUgraphNode hNode, const CUDA_MEMCPY3D* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphMemsetNodeGetParams, CU_DRIVER, cuGraphMemsetNodeGetParams, NOOP, CUresult, (CUgraphNode hNode, CUDA_MEMSET_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphMemsetNodeSetParams, CU_DRIVER, cuGraphMemsetNodeSetParams, NOOP, CUresult, (CUgraphNode hNode, const CUDA_MEMSET_NODE_PARAMS* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphNodeFindInClone, CU_DRIVER, cuGraphNodeFindInClone, NOOP, CUresult, (CUgraphNode* phNode, CUgraphNode hOriginalNode, CUgraph hClonedGraph));
ROCCU_DEFINE_FUNC(cuGraphNodeGetContainingGraph, CU_DRIVER, cuGraphNodeGetContainingGraph, NOOP, CUresult, (CUgraphNode hNode, CUgraph* phGraph));
ROCCU_DEFINE_FUNC(cuGraphNodeGetDependencies, CU_DRIVER, cuGraphNodeGetDependencies_v2, NOOP, CUresult, (CUgraphNode hNode, CUgraphNode* dependencies, CUgraphEdgeData* edgeData, size_t* numDependencies));
ROCCU_DEFINE_FUNC(cuGraphNodeGetDependentNodes, CU_DRIVER, cuGraphNodeGetDependentNodes_v2, NOOP, CUresult, (CUgraphNode hNode, CUgraphNode* dependentNodes, CUgraphEdgeData* edgeData, size_t* numDependentNodes));
ROCCU_DEFINE_FUNC(cuGraphNodeGetEnabled, CU_DRIVER, cuGraphNodeGetEnabled, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, unsigned int* isEnabled));
ROCCU_DEFINE_FUNC(cuGraphNodeGetLocalId, CU_DRIVER, cuGraphNodeGetLocalId, NOOP, CUresult, (CUgraphNode hNode, unsigned int* nodeId));
ROCCU_DEFINE_FUNC(cuGraphNodeGetToolsId, CU_DRIVER, cuGraphNodeGetToolsId, NOOP, CUresult, (CUgraphNode hNode, unsigned long long* toolsNodeId));
ROCCU_DEFINE_FUNC(cuGraphNodeGetType, CU_DRIVER, cuGraphNodeGetType, NOOP, CUresult, (CUgraphNode hNode, CUgraphNodeType* type));
ROCCU_DEFINE_FUNC(cuGraphNodeSetEnabled, CU_DRIVER, cuGraphNodeSetEnabled, NOOP, CUresult, (CUgraphExec hGraphExec, CUgraphNode hNode, unsigned int isEnabled));
ROCCU_DEFINE_FUNC(cuGraphNodeSetParams, CU_DRIVER, cuGraphNodeSetParams, NOOP, CUresult, (CUgraphNode hNode, CUgraphNodeParams* nodeParams));
ROCCU_DEFINE_FUNC(cuGraphReleaseUserObject, CU_DRIVER, cuGraphReleaseUserObject, NOOP, CUresult, (CUgraph graph, CUuserObject object, unsigned int count));
ROCCU_DEFINE_FUNC(cuGraphRemoveDependencies, CU_DRIVER, cuGraphRemoveDependencies_v2, NOOP, CUresult, (CUgraph hGraph, const CUgraphNode* from, const CUgraphNode* to, const CUgraphEdgeData* edgeData, size_t numDependencies));
ROCCU_DEFINE_FUNC(cuGraphRetainUserObject, CU_DRIVER, cuGraphRetainUserObject, NOOP, CUresult, (CUgraph graph, CUuserObject object, unsigned int count, unsigned int flags));
ROCCU_DEFINE_FUNC(cuGraphUpload, CU_DRIVER, cuGraphUpload_ptsz, NOOP, CUresult, (CUgraphExec hGraphExec, CUstream hStream));
ROCCU_DEFINE_FUNC(cuGraphicsGLRegisterBuffer, CU_DRIVER, cuGraphicsGLRegisterBuffer, NOOP, CUresult, (CUgraphicsResource* pCudaResource, unsigned int buffer, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuGraphicsGLRegisterImage, CU_DRIVER, cuGraphicsGLRegisterImage, NOOP, CUresult, (CUgraphicsResource* pCudaResource, unsigned int image, unsigned int target, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuGraphicsMapResources, CU_DRIVER, cuGraphicsMapResources_ptsz, NOOP, CUresult, (unsigned int count, CUgraphicsResource* resources, CUstream hStream));
ROCCU_DEFINE_FUNC(cuGraphicsResourceGetMappedMipmappedArray, CU_DRIVER, cuGraphicsResourceGetMappedMipmappedArray, NOOP, CUresult, (CUmipmappedArray* pMipmappedArray, CUgraphicsResource resource));
ROCCU_DEFINE_FUNC(cuGraphicsResourceGetMappedPointer, CU_DRIVER, cuGraphicsResourceGetMappedPointer_v2, NOOP, CUresult, (CUdeviceptr* pDevPtr, size_t* pSize, CUgraphicsResource resource));
ROCCU_DEFINE_FUNC(cuGraphicsResourceSetMapFlags, CU_DRIVER, cuGraphicsResourceSetMapFlags_v2, NOOP, CUresult, (CUgraphicsResource resource, unsigned int flags));
ROCCU_DEFINE_FUNC(cuGraphicsSubResourceGetMappedArray, CU_DRIVER, cuGraphicsSubResourceGetMappedArray, NOOP, CUresult, (CUarray* pArray, CUgraphicsResource resource, unsigned int arrayIndex, unsigned int mipLevel));
ROCCU_DEFINE_FUNC(cuGraphicsUnmapResources, CU_DRIVER, cuGraphicsUnmapResources_ptsz, NOOP, CUresult, (unsigned int count, CUgraphicsResource* resources, CUstream hStream));
ROCCU_DEFINE_FUNC(cuGraphicsUnregisterResource, CU_DRIVER, cuGraphicsUnregisterResource, NOOP, CUresult, (CUgraphicsResource resource));
ROCCU_DEFINE_FUNC(cuGreenCtxCreate, CU_DRIVER, cuGreenCtxCreate, NOOP, CUresult, (CUgreenCtx* phCtx, CUdevResourceDesc desc, CUdevice dev, unsigned int flags));
ROCCU_DEFINE_FUNC(cuGreenCtxDestroy, CU_DRIVER, cuGreenCtxDestroy, NOOP, CUresult, (CUgreenCtx hCtx));
ROCCU_DEFINE_FUNC(cuGreenCtxGetDevResource, CU_DRIVER, cuGreenCtxGetDevResource, NOOP, CUresult, (CUgreenCtx hCtx, CUdevResource* resource, CUdevResourceType type));
ROCCU_DEFINE_FUNC(cuGreenCtxGetId, CU_DRIVER, cuGreenCtxGetId, NOOP, CUresult, (CUgreenCtx greenCtx, unsigned long long* greenCtxId));
ROCCU_DEFINE_FUNC(cuGreenCtxRecordEvent, CU_DRIVER, cuGreenCtxRecordEvent, NOOP, CUresult, (CUgreenCtx hCtx, CUevent hEvent));
ROCCU_DEFINE_FUNC(cuGreenCtxStreamCreate, CU_DRIVER, cuGreenCtxStreamCreate, NOOP, CUresult, (CUstream* phStream, CUgreenCtx greenCtx, unsigned int flags, int priority));
ROCCU_DEFINE_FUNC(cuGreenCtxWaitEvent, CU_DRIVER, cuGreenCtxWaitEvent, NOOP, CUresult, (CUgreenCtx hCtx, CUevent hEvent));
ROCCU_DEFINE_FUNC(cuImportExternalMemory, CU_DRIVER, cuImportExternalMemory, NOOP, CUresult, (CUexternalMemory* extMem_out, const CUDA_EXTERNAL_MEMORY_HANDLE_DESC* memHandleDesc));
ROCCU_DEFINE_FUNC(cuImportExternalSemaphore, CU_DRIVER, cuImportExternalSemaphore, NOOP, CUresult, (CUexternalSemaphore* extSem_out, const CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC* semHandleDesc));
ROCCU_DEFINE_FUNC(cuInit, CU_DRIVER, cuInit, NOOP, CUresult, (unsigned int Flags));
ROCCU_DEFINE_FUNC(cuIpcCloseMemHandle, CU_DRIVER, cuIpcCloseMemHandle, NOOP, CUresult, (CUdeviceptr dptr));
ROCCU_DEFINE_FUNC(cuIpcGetEventHandle, CU_DRIVER, cuIpcGetEventHandle, NOOP, CUresult, (CUipcEventHandle* pHandle, CUevent event));
ROCCU_DEFINE_FUNC(cuIpcGetMemHandle, CU_DRIVER, cuIpcGetMemHandle, NOOP, CUresult, (CUipcMemHandle* pHandle, CUdeviceptr dptr));
ROCCU_DEFINE_FUNC(cuIpcOpenEventHandle, CU_DRIVER, cuIpcOpenEventHandle, NOOP, CUresult, (CUevent* phEvent, CUipcEventHandle handle));
ROCCU_DEFINE_FUNC(cuIpcOpenMemHandle, CU_DRIVER, cuIpcOpenMemHandle_v2, NOOP, CUresult, (CUdeviceptr* pdptr, CUipcMemHandle handle, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuKernelGetAttribute, CU_DRIVER, cuKernelGetAttribute, NOOP, CUresult, (int* pi, CUfunction_attribute attrib, CUkernel kernel, CUdevice dev));
ROCCU_DEFINE_FUNC(cuKernelGetFunction, CU_DRIVER, cuKernelGetFunction, NOOP, CUresult, (CUfunction* pFunc, CUkernel kernel));
ROCCU_DEFINE_FUNC(cuKernelGetLibrary, CU_DRIVER, cuKernelGetLibrary, NOOP, CUresult, (CUlibrary* pLib, CUkernel kernel));
ROCCU_DEFINE_FUNC(cuKernelGetName, CU_DRIVER, cuKernelGetName, NOOP, CUresult, (const char** name, CUkernel hfunc));
ROCCU_DEFINE_FUNC(cuKernelGetParamInfo, CU_DRIVER, cuKernelGetParamInfo, NOOP, CUresult, (CUkernel kernel, size_t paramIndex, size_t* paramOffset, size_t* paramSize));
ROCCU_DEFINE_FUNC(cuKernelSetAttribute, CU_DRIVER, cuKernelSetAttribute, NOOP, CUresult, (CUfunction_attribute attrib, int val, CUkernel kernel, CUdevice dev));
ROCCU_DEFINE_FUNC(cuKernelSetCacheConfig, CU_DRIVER, cuKernelSetCacheConfig, NOOP, CUresult, (CUkernel kernel, CUfunc_cache config, CUdevice dev));
ROCCU_DEFINE_FUNC(cuLaunchCooperativeKernel, CU_DRIVER, cuLaunchCooperativeKernel_ptsz, NOOP, CUresult, (CUfunction f, unsigned int gridDimX, unsigned int gridDimY, unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY, unsigned int blockDimZ, unsigned int sharedMemBytes, CUstream hStream, void** kernelParams));
ROCCU_DEFINE_FUNC(cuLaunchHostFunc, CU_DRIVER, cuLaunchHostFunc_ptsz, NOOP, CUresult, (CUstream hStream, CUhostFn fn, void* userData));
ROCCU_DEFINE_FUNC(cuLaunchKernel, CU_DRIVER, cuLaunchKernel_ptsz, NOOP, CUresult, (CUfunction f, unsigned int gridDimX, unsigned int gridDimY, unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY, unsigned int blockDimZ, unsigned int sharedMemBytes, CUstream hStream, void** kernelParams, void** extra));
ROCCU_DEFINE_FUNC(cuLaunchKernelEx, CU_DRIVER, cuLaunchKernelEx_ptsz, NOOP, CUresult, (const CUlaunchConfig* config, CUfunction f, void** kernelParams, void** extra));
ROCCU_DEFINE_FUNC(cuLibraryEnumerateKernels, CU_DRIVER, cuLibraryEnumerateKernels, NOOP, CUresult, (CUkernel* kernels, unsigned int numKernels, CUlibrary lib));
ROCCU_DEFINE_FUNC(cuLibraryGetGlobal, CU_DRIVER, cuLibraryGetGlobal, NOOP, CUresult, (CUdeviceptr* dptr, size_t* bytes, CUlibrary library, const char* name));
ROCCU_DEFINE_FUNC(cuLibraryGetKernel, CU_DRIVER, cuLibraryGetKernel, NOOP, CUresult, (CUkernel* pKernel, CUlibrary library, const char* name));
ROCCU_DEFINE_FUNC(cuLibraryGetKernelCount, CU_DRIVER, cuLibraryGetKernelCount, NOOP, CUresult, (unsigned int* count, CUlibrary lib));
ROCCU_DEFINE_FUNC(cuLibraryGetManaged, CU_DRIVER, cuLibraryGetManaged, NOOP, CUresult, (CUdeviceptr* dptr, size_t* bytes, CUlibrary library, const char* name));
ROCCU_DEFINE_FUNC(cuLibraryGetModule, CU_DRIVER, cuLibraryGetModule, NOOP, CUresult, (CUmodule* pMod, CUlibrary library));
ROCCU_DEFINE_FUNC(cuLibraryGetUnifiedFunction, CU_DRIVER, cuLibraryGetUnifiedFunction, NOOP, CUresult, (void** fptr, CUlibrary library, const char* symbol));
ROCCU_DEFINE_FUNC(cuLibraryLoadData, CU_DRIVER, cuLibraryLoadData, NOOP, CUresult, (CUlibrary* library, const void* code, CUjit_option* jitOptions, void** jitOptionsValues, unsigned int numJitOptions, CUlibraryOption* libraryOptions, void** libraryOptionValues, unsigned int numLibraryOptions));
ROCCU_DEFINE_FUNC(cuLibraryLoadFromFile, CU_DRIVER, cuLibraryLoadFromFile, NOOP, CUresult, (CUlibrary* library, const char* fileName, CUjit_option* jitOptions, void** jitOptionsValues, unsigned int numJitOptions, CUlibraryOption* libraryOptions, void** libraryOptionValues, unsigned int numLibraryOptions));
ROCCU_DEFINE_FUNC(cuLibraryUnload, CU_DRIVER, cuLibraryUnload, NOOP, CUresult, (CUlibrary library));
ROCCU_DEFINE_FUNC(cuLinkAddData, CU_DRIVER, cuLinkAddData_v2, NOOP, CUresult, (CUlinkState state, CUjitInputType type, void* data, size_t size, const char* name, unsigned int numOptions, CUjit_option* options, void** optionValues));
ROCCU_DEFINE_FUNC(cuLinkAddFile, CU_DRIVER, cuLinkAddFile_v2, NOOP, CUresult, (CUlinkState state, CUjitInputType type, const char* path, unsigned int numOptions, CUjit_option* options, void** optionValues));
ROCCU_DEFINE_FUNC(cuLinkComplete, CU_DRIVER, cuLinkComplete, NOOP, CUresult, (CUlinkState state, void** cubinOut, size_t* sizeOut));
ROCCU_DEFINE_FUNC(cuLinkCreate, CU_DRIVER, cuLinkCreate_v2, NOOP, CUresult, (unsigned int numOptions, CUjit_option* options, void** optionValues, CUlinkState* stateOut));
ROCCU_DEFINE_FUNC(cuLinkDestroy, CU_DRIVER, cuLinkDestroy, NOOP, CUresult, (CUlinkState state));
ROCCU_DEFINE_FUNC(cuLogsCurrent, CU_DRIVER, cuLogsCurrent, NOOP, CUresult, (CUlogIterator* iterator_out, unsigned int flags));
ROCCU_DEFINE_FUNC(cuLogsDumpToFile, CU_DRIVER, cuLogsDumpToFile, NOOP, CUresult, (CUlogIterator* iterator, const char* pathToFile, unsigned int flags));
ROCCU_DEFINE_FUNC(cuLogsDumpToMemory, CU_DRIVER, cuLogsDumpToMemory, NOOP, CUresult, (CUlogIterator* iterator, char* buffer, size_t* size, unsigned int flags));
ROCCU_DEFINE_FUNC(cuLogsRegisterCallback, CU_DRIVER, cuLogsRegisterCallback, NOOP, CUresult, (CUlogsCallback callbackFunc, void* userData, CUlogsCallbackHandle* callback_out));
ROCCU_DEFINE_FUNC(cuLogsUnregisterCallback, CU_DRIVER, cuLogsUnregisterCallback, NOOP, CUresult, (CUlogsCallbackHandle callback));
ROCCU_DEFINE_FUNC(cuMemAddressFree, CU_DRIVER, cuMemAddressFree, NOOP, CUresult, (CUdeviceptr ptr, size_t size));
ROCCU_DEFINE_FUNC(cuMemAddressReserve, CU_DRIVER, cuMemAddressReserve, NOOP, CUresult, (CUdeviceptr* ptr, size_t size, size_t alignment, CUdeviceptr addr, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMemAdvise, CU_DRIVER, cuMemAdvise_v2, NOOP, CUresult, (CUdeviceptr devPtr, size_t count, CUmem_advise advice, CUmemLocation location));
ROCCU_DEFINE_FUNC(cuMemAlloc, CU_DRIVER, cuMemAlloc_v2, NOOP, CUresult, (CUdeviceptr* dptr, size_t bytesize));
ROCCU_DEFINE_FUNC(cuMemAllocAsync, CU_DRIVER, cuMemAllocAsync_ptsz, NOOP, CUresult, (CUdeviceptr* dptr, size_t bytesize, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemAllocFromPoolAsync, CU_DRIVER, cuMemAllocFromPoolAsync_ptsz, NOOP, CUresult, (CUdeviceptr* dptr, size_t bytesize, CUmemoryPool pool, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemAllocHost, CU_DRIVER, cuMemAllocHost_v2, NOOP, CUresult, (void** pp, size_t bytesize));
ROCCU_DEFINE_FUNC(cuMemAllocManaged, CU_DRIVER, cuMemAllocManaged, NOOP, CUresult, (CUdeviceptr* dptr, size_t bytesize, unsigned int flags));
ROCCU_DEFINE_FUNC(cuMemAllocPitch, CU_DRIVER, cuMemAllocPitch_v2, NOOP, CUresult, (CUdeviceptr* dptr, size_t* pPitch, size_t WidthInBytes, size_t Height, unsigned int ElementSizeBytes));
ROCCU_DEFINE_FUNC(cuMemBatchDecompressAsync, CU_DRIVER, cuMemBatchDecompressAsync_ptsz, NOOP, CUresult, (CUmemDecompressParams* paramsArray, size_t count, unsigned int flags, size_t* errorIndex, CUstream stream));
ROCCU_DEFINE_FUNC(cuMemCreate, CU_DRIVER, cuMemCreate, NOOP, CUresult, (CUmemGenericAllocationHandle* handle, size_t size, const CUmemAllocationProp* prop, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMemDiscardAndPrefetchBatchAsync, CU_DRIVER, cuMemDiscardAndPrefetchBatchAsync_ptsz, NOOP, CUresult, (CUdeviceptr* dptrs, size_t* sizes, size_t count, CUmemLocation* prefetchLocs, size_t* prefetchLocIdxs, size_t numPrefetchLocs, unsigned long long flags, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemDiscardBatchAsync, CU_DRIVER, cuMemDiscardBatchAsync_ptsz, NOOP, CUresult, (CUdeviceptr* dptrs, size_t* sizes, size_t count, unsigned long long flags, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemExportToShareableHandle, CU_DRIVER, cuMemExportToShareableHandle, NOOP, CUresult, (void* shareableHandle, CUmemGenericAllocationHandle handle, CUmemAllocationHandleType handleType, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMemFree, CU_DRIVER, cuMemFree_v2, NOOP, CUresult, (CUdeviceptr dptr));
ROCCU_DEFINE_FUNC(cuMemFreeAsync, CU_DRIVER, cuMemFreeAsync_ptsz, NOOP, CUresult, (CUdeviceptr dptr, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemFreeHost, CU_DRIVER, cuMemFreeHost, NOOP, CUresult, (void* p));
ROCCU_DEFINE_FUNC(cuMemGetAccess, CU_DRIVER, cuMemGetAccess, NOOP, CUresult, (unsigned long long* flags, const CUmemLocation* location, CUdeviceptr ptr));
ROCCU_DEFINE_FUNC(cuMemGetAddressRange, CU_DRIVER, cuMemGetAddressRange_v2, NOOP, CUresult, (CUdeviceptr* pbase, size_t* psize, CUdeviceptr dptr));
ROCCU_DEFINE_FUNC(cuMemGetAllocationGranularity, CU_DRIVER, cuMemGetAllocationGranularity, NOOP, CUresult, (size_t* granularity, const CUmemAllocationProp* prop, CUmemAllocationGranularity_flags option));
ROCCU_DEFINE_FUNC(cuMemGetAllocationPropertiesFromHandle, CU_DRIVER, cuMemGetAllocationPropertiesFromHandle, NOOP, CUresult, (CUmemAllocationProp* prop, CUmemGenericAllocationHandle handle));
ROCCU_DEFINE_FUNC(cuMemGetDefaultMemPool, CU_DRIVER, cuMemGetDefaultMemPool, NOOP, CUresult, (CUmemoryPool* pool_out, CUmemLocation* location, CUmemAllocationType type));
ROCCU_DEFINE_FUNC(cuMemGetHandleForAddressRange, CU_DRIVER, cuMemGetHandleForAddressRange, NOOP, CUresult, (void* handle, CUdeviceptr dptr, size_t size, CUmemRangeHandleType handleType, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMemGetInfo, CU_DRIVER, cuMemGetInfo_v2, NOOP, CUresult, (size_t* free, size_t* total));
ROCCU_DEFINE_FUNC(cuMemGetMemPool, CU_DRIVER, cuMemGetMemPool, NOOP, CUresult, (CUmemoryPool* pool, CUmemLocation* location, CUmemAllocationType type));
ROCCU_DEFINE_FUNC(cuMemHostAlloc, CU_DRIVER, cuMemHostAlloc, NOOP, CUresult, (void** pp, size_t bytesize, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuMemHostGetDevicePointer, CU_DRIVER, cuMemHostGetDevicePointer_v2, NOOP, CUresult, (CUdeviceptr* pdptr, void* p, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuMemHostGetFlags, CU_DRIVER, cuMemHostGetFlags, NOOP, CUresult, (unsigned int* pFlags, void* p));
ROCCU_DEFINE_FUNC(cuMemHostRegister, CU_DRIVER, cuMemHostRegister_v2, NOOP, CUresult, (void* p, size_t bytesize, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuMemHostUnregister, CU_DRIVER, cuMemHostUnregister, NOOP, CUresult, (void* p));
ROCCU_DEFINE_FUNC(cuMemImportFromShareableHandle, CU_DRIVER, cuMemImportFromShareableHandle, NOOP, CUresult, (CUmemGenericAllocationHandle* handle, void* osHandle, CUmemAllocationHandleType shHandleType));
ROCCU_DEFINE_FUNC(cuMemMap, CU_DRIVER, cuMemMap, NOOP, CUresult, (CUdeviceptr ptr, size_t size, size_t offset, CUmemGenericAllocationHandle handle, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMemMapArrayAsync, CU_DRIVER, cuMemMapArrayAsync_ptsz, NOOP, CUresult, (CUarrayMapInfo* mapInfoList, unsigned int count, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemPoolCreate, CU_DRIVER, cuMemPoolCreate, NOOP, CUresult, (CUmemoryPool* pool, const CUmemPoolProps* poolProps));
ROCCU_DEFINE_FUNC(cuMemPoolDestroy, CU_DRIVER, cuMemPoolDestroy, NOOP, CUresult, (CUmemoryPool pool));
ROCCU_DEFINE_FUNC(cuMemPoolExportPointer, CU_DRIVER, cuMemPoolExportPointer, NOOP, CUresult, (CUmemPoolPtrExportData* shareData_out, CUdeviceptr ptr));
ROCCU_DEFINE_FUNC(cuMemPoolExportToShareableHandle, CU_DRIVER, cuMemPoolExportToShareableHandle, NOOP, CUresult, (void* handle_out, CUmemoryPool pool, CUmemAllocationHandleType handleType, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMemPoolGetAccess, CU_DRIVER, cuMemPoolGetAccess, NOOP, CUresult, (CUmemAccess_flags* flags, CUmemoryPool memPool, CUmemLocation* location));
ROCCU_DEFINE_FUNC(cuMemPoolGetAttribute, CU_DRIVER, cuMemPoolGetAttribute, NOOP, CUresult, (CUmemoryPool pool, CUmemPool_attribute attr, void* value));
ROCCU_DEFINE_FUNC(cuMemPoolImportFromShareableHandle, CU_DRIVER, cuMemPoolImportFromShareableHandle, NOOP, CUresult, (CUmemoryPool* pool_out, void* handle, CUmemAllocationHandleType handleType, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMemPoolImportPointer, CU_DRIVER, cuMemPoolImportPointer, NOOP, CUresult, (CUdeviceptr* ptr_out, CUmemoryPool pool, CUmemPoolPtrExportData* shareData));
ROCCU_DEFINE_FUNC(cuMemPoolSetAccess, CU_DRIVER, cuMemPoolSetAccess, NOOP, CUresult, (CUmemoryPool pool, const CUmemAccessDesc* map, size_t count));
ROCCU_DEFINE_FUNC(cuMemPoolSetAttribute, CU_DRIVER, cuMemPoolSetAttribute, NOOP, CUresult, (CUmemoryPool pool, CUmemPool_attribute attr, void* value));
ROCCU_DEFINE_FUNC(cuMemPoolTrimTo, CU_DRIVER, cuMemPoolTrimTo, NOOP, CUresult, (CUmemoryPool pool, size_t minBytesToKeep));
ROCCU_DEFINE_FUNC(cuMemPrefetchAsync, CU_DRIVER, cuMemPrefetchAsync_v2_ptsz, NOOP, CUresult, (CUdeviceptr devPtr, size_t count, CUmemLocation location, unsigned int flags, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemPrefetchBatchAsync, CU_DRIVER, cuMemPrefetchBatchAsync_ptsz, NOOP, CUresult, (CUdeviceptr* dptrs, size_t* sizes, size_t count, CUmemLocation* prefetchLocs, size_t* prefetchLocIdxs, size_t numPrefetchLocs, unsigned long long flags, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemRangeGetAttribute, CU_DRIVER, cuMemRangeGetAttribute, NOOP, CUresult, (void* data, size_t dataSize, CUmem_range_attribute attribute, CUdeviceptr devPtr, size_t count));
ROCCU_DEFINE_FUNC(cuMemRangeGetAttributes, CU_DRIVER, cuMemRangeGetAttributes, NOOP, CUresult, (void** data, size_t* dataSizes, CUmem_range_attribute* attributes, size_t numAttributes, CUdeviceptr devPtr, size_t count));
ROCCU_DEFINE_FUNC(cuMemRelease, CU_DRIVER, cuMemRelease, NOOP, CUresult, (CUmemGenericAllocationHandle handle));
ROCCU_DEFINE_FUNC(cuMemRetainAllocationHandle, CU_DRIVER, cuMemRetainAllocationHandle, NOOP, CUresult, (CUmemGenericAllocationHandle* handle, void* addr));
ROCCU_DEFINE_FUNC(cuMemSetAccess, CU_DRIVER, cuMemSetAccess, NOOP, CUresult, (CUdeviceptr ptr, size_t size, const CUmemAccessDesc* desc, size_t count));
ROCCU_DEFINE_FUNC(cuMemSetMemPool, CU_DRIVER, cuMemSetMemPool, NOOP, CUresult, (CUmemLocation* location, CUmemAllocationType type, CUmemoryPool pool));
ROCCU_DEFINE_FUNC(cuMemUnmap, CU_DRIVER, cuMemUnmap, NOOP, CUresult, (CUdeviceptr ptr, size_t size));
ROCCU_DEFINE_FUNC(cuMemcpy, CU_DRIVER, cuMemcpy_ptds, NOOP, CUresult, (CUdeviceptr dst, CUdeviceptr src, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpy2D, CU_DRIVER, cuMemcpy2D_v2_ptds, NOOP, CUresult, (const CUDA_MEMCPY2D* pCopy));
ROCCU_DEFINE_FUNC(cuMemcpy2DAsync, CU_DRIVER, cuMemcpy2DAsync_v2_ptsz, NOOP, CUresult, (const CUDA_MEMCPY2D* pCopy, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpy2DUnaligned, CU_DRIVER, cuMemcpy2DUnaligned_v2_ptds, NOOP, CUresult, (const CUDA_MEMCPY2D* pCopy));
ROCCU_DEFINE_FUNC(cuMemcpy3D, CU_DRIVER, cuMemcpy3D_v2_ptds, NOOP, CUresult, (const CUDA_MEMCPY3D* pCopy));
ROCCU_DEFINE_FUNC(cuMemcpy3DAsync, CU_DRIVER, cuMemcpy3DAsync_v2_ptsz, NOOP, CUresult, (const CUDA_MEMCPY3D* pCopy, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpy3DBatchAsync, CU_DRIVER, cuMemcpy3DBatchAsync_v2_ptsz, NOOP, CUresult, (size_t numOps, CUDA_MEMCPY3D_BATCH_OP* opList, unsigned long long flags, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpy3DPeer, CU_DRIVER, cuMemcpy3DPeer_ptds, NOOP, CUresult, (const CUDA_MEMCPY3D_PEER* pCopy));
ROCCU_DEFINE_FUNC(cuMemcpy3DPeerAsync, CU_DRIVER, cuMemcpy3DPeerAsync_ptsz, NOOP, CUresult, (const CUDA_MEMCPY3D_PEER* pCopy, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyAsync, CU_DRIVER, cuMemcpyAsync_ptsz, NOOP, CUresult, (CUdeviceptr dst, CUdeviceptr src, size_t ByteCount, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyAtoA, CU_DRIVER, cuMemcpyAtoA_v2_ptds, NOOP, CUresult, (CUarray dstArray, size_t dstOffset, CUarray srcArray, size_t srcOffset, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyAtoD, CU_DRIVER, cuMemcpyAtoD_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, CUarray srcArray, size_t srcOffset, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyAtoH, CU_DRIVER, cuMemcpyAtoH_v2_ptds, NOOP, CUresult, (void* dstHost, CUarray srcArray, size_t srcOffset, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyAtoHAsync, CU_DRIVER, cuMemcpyAtoHAsync_v2_ptsz, NOOP, CUresult, (void* dstHost, CUarray srcArray, size_t srcOffset, size_t ByteCount, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyBatchAsync, CU_DRIVER, cuMemcpyBatchAsync_v2_ptsz, NOOP, CUresult, (CUdeviceptr* dsts, CUdeviceptr* srcs, size_t* sizes, size_t count, CUmemcpyAttributes* attrs, size_t* attrsIdxs, size_t numAttrs, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyDtoA, CU_DRIVER, cuMemcpyDtoA_v2_ptds, NOOP, CUresult, (CUarray dstArray, size_t dstOffset, CUdeviceptr srcDevice, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyDtoD, CU_DRIVER, cuMemcpyDtoD_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, CUdeviceptr srcDevice, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyDtoDAsync, CU_DRIVER, cuMemcpyDtoDAsync_v2_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, CUdeviceptr srcDevice, size_t ByteCount, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyDtoH, CU_DRIVER, cuMemcpyDtoH_v2_ptds, NOOP, CUresult, (void* dstHost, CUdeviceptr srcDevice, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyDtoHAsync, CU_DRIVER, cuMemcpyDtoHAsync_v2_ptsz, NOOP, CUresult, (void* dstHost, CUdeviceptr srcDevice, size_t ByteCount, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyHtoA, CU_DRIVER, cuMemcpyHtoA_v2_ptds, NOOP, CUresult, (CUarray dstArray, size_t dstOffset, const void* srcHost, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyHtoAAsync, CU_DRIVER, cuMemcpyHtoAAsync_v2_ptsz, NOOP, CUresult, (CUarray dstArray, size_t dstOffset, const void* srcHost, size_t ByteCount, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyHtoD, CU_DRIVER, cuMemcpyHtoD_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, const void* srcHost, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyHtoDAsync, CU_DRIVER, cuMemcpyHtoDAsync_v2_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, const void* srcHost, size_t ByteCount, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemcpyPeer, CU_DRIVER, cuMemcpyPeer_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, CUcontext dstContext, CUdeviceptr srcDevice, CUcontext srcContext, size_t ByteCount));
ROCCU_DEFINE_FUNC(cuMemcpyPeerAsync, CU_DRIVER, cuMemcpyPeerAsync_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, CUcontext dstContext, CUdeviceptr srcDevice, CUcontext srcContext, size_t ByteCount, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemsetD16, CU_DRIVER, cuMemsetD16_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, unsigned short us, size_t N));
ROCCU_DEFINE_FUNC(cuMemsetD16Async, CU_DRIVER, cuMemsetD16Async_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, unsigned short us, size_t N, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemsetD2D16, CU_DRIVER, cuMemsetD2D16_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, size_t dstPitch, unsigned short us, size_t Width, size_t Height));
ROCCU_DEFINE_FUNC(cuMemsetD2D16Async, CU_DRIVER, cuMemsetD2D16Async_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, size_t dstPitch, unsigned short us, size_t Width, size_t Height, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemsetD2D32, CU_DRIVER, cuMemsetD2D32_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, size_t dstPitch, unsigned int ui, size_t Width, size_t Height));
ROCCU_DEFINE_FUNC(cuMemsetD2D32Async, CU_DRIVER, cuMemsetD2D32Async_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, size_t dstPitch, unsigned int ui, size_t Width, size_t Height, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemsetD2D8, CU_DRIVER, cuMemsetD2D8_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, size_t dstPitch, unsigned char uc, size_t Width, size_t Height));
ROCCU_DEFINE_FUNC(cuMemsetD2D8Async, CU_DRIVER, cuMemsetD2D8Async_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, size_t dstPitch, unsigned char uc, size_t Width, size_t Height, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemsetD32, CU_DRIVER, cuMemsetD32_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, unsigned int ui, size_t N));
ROCCU_DEFINE_FUNC(cuMemsetD32Async, CU_DRIVER, cuMemsetD32Async_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, unsigned int ui, size_t N, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMemsetD8, CU_DRIVER, cuMemsetD8_v2_ptds, NOOP, CUresult, (CUdeviceptr dstDevice, unsigned char uc, size_t N));
ROCCU_DEFINE_FUNC(cuMemsetD8Async, CU_DRIVER, cuMemsetD8Async_ptsz, NOOP, CUresult, (CUdeviceptr dstDevice, unsigned char uc, size_t N, CUstream hStream));
ROCCU_DEFINE_FUNC(cuMipmappedArrayCreate, CU_DRIVER, cuMipmappedArrayCreate, NOOP, CUresult, (CUmipmappedArray* pHandle, const CUDA_ARRAY3D_DESCRIPTOR* pMipmappedArrayDesc, unsigned int numMipmapLevels));
ROCCU_DEFINE_FUNC(cuMipmappedArrayDestroy, CU_DRIVER, cuMipmappedArrayDestroy, NOOP, CUresult, (CUmipmappedArray hMipmappedArray));
ROCCU_DEFINE_FUNC(cuMipmappedArrayGetLevel, CU_DRIVER, cuMipmappedArrayGetLevel, NOOP, CUresult, (CUarray* pLevelArray, CUmipmappedArray hMipmappedArray, unsigned int level));
ROCCU_DEFINE_FUNC(cuMipmappedArrayGetMemoryRequirements, CU_DRIVER, cuMipmappedArrayGetMemoryRequirements, NOOP, CUresult, (CUDA_ARRAY_MEMORY_REQUIREMENTS* memoryRequirements, CUmipmappedArray mipmap, CUdevice device));
ROCCU_DEFINE_FUNC(cuMipmappedArrayGetSparseProperties, CU_DRIVER, cuMipmappedArrayGetSparseProperties, NOOP, CUresult, (CUDA_ARRAY_SPARSE_PROPERTIES* sparseProperties, CUmipmappedArray mipmap));
ROCCU_DEFINE_FUNC(cuModuleEnumerateFunctions, CU_DRIVER, cuModuleEnumerateFunctions, NOOP, CUresult, (CUfunction* functions, unsigned int numFunctions, CUmodule mod));
ROCCU_DEFINE_FUNC(cuModuleGetFunction, CU_DRIVER, cuModuleGetFunction, NOOP, CUresult, (CUfunction* hfunc, CUmodule hmod, const char* name));
ROCCU_DEFINE_FUNC(cuModuleGetFunctionCount, CU_DRIVER, cuModuleGetFunctionCount, NOOP, CUresult, (unsigned int* count, CUmodule mod));
ROCCU_DEFINE_FUNC(cuModuleGetGlobal, CU_DRIVER, cuModuleGetGlobal_v2, NOOP, CUresult, (CUdeviceptr* dptr, size_t* bytes, CUmodule hmod, const char* name));
ROCCU_DEFINE_FUNC(cuModuleGetLoadingMode, CU_DRIVER, cuModuleGetLoadingMode, NOOP, CUresult, (CUmoduleLoadingMode* mode));
ROCCU_DEFINE_FUNC(cuModuleLoad, CU_DRIVER, cuModuleLoad, NOOP, CUresult, (CUmodule* module, const char* fname));
ROCCU_DEFINE_FUNC(cuModuleLoadData, CU_DRIVER, cuModuleLoadData, NOOP, CUresult, (CUmodule* module, const void* image));
ROCCU_DEFINE_FUNC(cuModuleLoadDataEx, CU_DRIVER, cuModuleLoadDataEx, NOOP, CUresult, (CUmodule* module, const void* image, unsigned int numOptions, CUjit_option* options, void** optionValues));
ROCCU_DEFINE_FUNC(cuModuleLoadFatBinary, CU_DRIVER, cuModuleLoadFatBinary, NOOP, CUresult, (CUmodule* module, const void* fatCubin));
ROCCU_DEFINE_FUNC(cuModuleUnload, CU_DRIVER, cuModuleUnload, NOOP, CUresult, (CUmodule hmod));
ROCCU_DEFINE_FUNC(cuMulticastAddDevice, CU_DRIVER, cuMulticastAddDevice, NOOP, CUresult, (CUmemGenericAllocationHandle mcHandle, CUdevice dev));
ROCCU_DEFINE_FUNC(cuMulticastBindAddr, CU_DRIVER, cuMulticastBindAddr, NOOP, CUresult, (CUmemGenericAllocationHandle mcHandle, size_t mcOffset, CUdeviceptr memptr, size_t size, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMulticastBindAddr_v2, CU_DRIVER, cuMulticastBindAddr_v2, NOOP, CUresult, (CUmemGenericAllocationHandle mcHandle, CUdevice dev, size_t mcOffset, CUdeviceptr memptr, size_t size, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMulticastBindMem, CU_DRIVER, cuMulticastBindMem, NOOP, CUresult, (CUmemGenericAllocationHandle mcHandle, size_t mcOffset, CUmemGenericAllocationHandle memHandle, size_t memOffset, size_t size, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMulticastBindMem_v2, CU_DRIVER, cuMulticastBindMem_v2, NOOP, CUresult, (CUmemGenericAllocationHandle mcHandle, CUdevice dev, size_t mcOffset, CUmemGenericAllocationHandle memHandle, size_t memOffset, size_t size, unsigned long long flags));
ROCCU_DEFINE_FUNC(cuMulticastCreate, CU_DRIVER, cuMulticastCreate, NOOP, CUresult, (CUmemGenericAllocationHandle* mcHandle, const CUmulticastObjectProp* prop));
ROCCU_DEFINE_FUNC(cuMulticastGetGranularity, CU_DRIVER, cuMulticastGetGranularity, NOOP, CUresult, (size_t* granularity, const CUmulticastObjectProp* prop, CUmulticastGranularity_flags option));
ROCCU_DEFINE_FUNC(cuMulticastUnbind, CU_DRIVER, cuMulticastUnbind, NOOP, CUresult, (CUmemGenericAllocationHandle mcHandle, CUdevice dev, size_t mcOffset, size_t size));
ROCCU_DEFINE_FUNC(cuOccupancyAvailableDynamicSMemPerBlock, CU_DRIVER, cuOccupancyAvailableDynamicSMemPerBlock, NOOP, CUresult, (size_t* dynamicSmemSize, CUfunction func, int numBlocks, int blockSize));
ROCCU_DEFINE_FUNC(cuOccupancyMaxActiveBlocksPerMultiprocessor, CU_DRIVER, cuOccupancyMaxActiveBlocksPerMultiprocessor, NOOP, CUresult, (int* numBlocks, CUfunction func, int blockSize, size_t dynamicSMemSize));
ROCCU_DEFINE_FUNC(cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags, CU_DRIVER, cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags, NOOP, CUresult, (int* numBlocks, CUfunction func, int blockSize, size_t dynamicSMemSize, unsigned int flags));
ROCCU_DEFINE_FUNC(cuOccupancyMaxActiveClusters, CU_DRIVER, cuOccupancyMaxActiveClusters, NOOP, CUresult, (int* numClusters, CUfunction func, const CUlaunchConfig* config));
ROCCU_DEFINE_FUNC(cuOccupancyMaxPotentialBlockSize, CU_DRIVER, cuOccupancyMaxPotentialBlockSize, NOOP, CUresult, (int* minGridSize, int* blockSize, CUfunction func, CUoccupancyB2DSize blockSizeToDynamicSMemSize, size_t dynamicSMemSize, int blockSizeLimit));
ROCCU_DEFINE_FUNC(cuOccupancyMaxPotentialBlockSizeWithFlags, CU_DRIVER, cuOccupancyMaxPotentialBlockSizeWithFlags, NOOP, CUresult, (int* minGridSize, int* blockSize, CUfunction func, CUoccupancyB2DSize blockSizeToDynamicSMemSize, size_t dynamicSMemSize, int blockSizeLimit, unsigned int flags));
ROCCU_DEFINE_FUNC(cuOccupancyMaxPotentialClusterSize, CU_DRIVER, cuOccupancyMaxPotentialClusterSize, NOOP, CUresult, (int* clusterSize, CUfunction func, const CUlaunchConfig* config));
ROCCU_DEFINE_FUNC(cuPointerGetAttribute, CU_DRIVER, cuPointerGetAttribute, NOOP, CUresult, (void* data, CUpointer_attribute attribute, CUdeviceptr ptr));
ROCCU_DEFINE_FUNC(cuPointerGetAttributes, CU_DRIVER, cuPointerGetAttributes, NOOP, CUresult, (unsigned int numAttributes, CUpointer_attribute* attributes, void** data, CUdeviceptr ptr));
ROCCU_DEFINE_FUNC(cuPointerSetAttribute, CU_DRIVER, cuPointerSetAttribute, NOOP, CUresult, (const void* value, CUpointer_attribute attribute, CUdeviceptr ptr));
ROCCU_DEFINE_FUNC(cuSignalExternalSemaphoresAsync, CU_DRIVER, cuSignalExternalSemaphoresAsync_ptsz, NOOP, CUresult, (const CUexternalSemaphore* extSemArray, const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS* paramsArray, unsigned int numExtSems, CUstream stream));
ROCCU_DEFINE_FUNC(cuStreamAddCallback, CU_DRIVER, cuStreamAddCallback_ptsz, NOOP, CUresult, (CUstream hStream, CUstreamCallback callback, void* userData, unsigned int flags));
ROCCU_DEFINE_FUNC(cuStreamAttachMemAsync, CU_DRIVER, cuStreamAttachMemAsync_ptsz, NOOP, CUresult, (CUstream hStream, CUdeviceptr dptr, size_t length, unsigned int flags));
ROCCU_DEFINE_FUNC(cuStreamBatchMemOp, CU_DRIVER, cuStreamBatchMemOp_v2_ptsz, NOOP, CUresult, (CUstream stream, unsigned int count, CUstreamBatchMemOpParams* paramArray, unsigned int flags));
ROCCU_DEFINE_FUNC(cuStreamBeginCapture, CU_DRIVER, cuStreamBeginCapture_v2_ptsz, NOOP, CUresult, (CUstream hStream, CUstreamCaptureMode mode));
ROCCU_DEFINE_FUNC(cuStreamBeginCaptureToGraph, CU_DRIVER, cuStreamBeginCaptureToGraph_ptsz, NOOP, CUresult, (CUstream hStream, CUgraph hGraph, const CUgraphNode* dependencies, const CUgraphEdgeData* dependencyData, size_t numDependencies, CUstreamCaptureMode mode));
ROCCU_DEFINE_FUNC(cuStreamCopyAttributes, CU_DRIVER, cuStreamCopyAttributes_ptsz, NOOP, CUresult, (CUstream dst, CUstream src));
ROCCU_DEFINE_FUNC(cuStreamCreate, CU_DRIVER, cuStreamCreate, NOOP, CUresult, (CUstream* phStream, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuStreamCreateWithPriority, CU_DRIVER, cuStreamCreateWithPriority, NOOP, CUresult, (CUstream* phStream, unsigned int flags, int priority));
ROCCU_DEFINE_FUNC(cuStreamDestroy, CU_DRIVER, cuStreamDestroy_v2, NOOP, CUresult, (CUstream hStream));
ROCCU_DEFINE_FUNC(cuStreamEndCapture, CU_DRIVER, cuStreamEndCapture_ptsz, NOOP, CUresult, (CUstream hStream, CUgraph* phGraph));
ROCCU_DEFINE_FUNC(cuStreamGetAttribute, CU_DRIVER, cuStreamGetAttribute_ptsz, NOOP, CUresult, (CUstream hStream, CUstreamAttrID attr, CUstreamAttrValue* value_out));
ROCCU_DEFINE_FUNC(cuStreamGetCaptureInfo, CU_DRIVER, cuStreamGetCaptureInfo_v3_ptsz, NOOP, CUresult, (CUstream hStream, CUstreamCaptureStatus* captureStatus_out, cuuint64_t* id_out, CUgraph* graph_out, const CUgraphNode** dependencies_out, const CUgraphEdgeData** edgeData_out, size_t* numDependencies_out));
ROCCU_DEFINE_FUNC(cuStreamGetCtx, CU_DRIVER, cuStreamGetCtx_ptsz, NOOP, CUresult, (CUstream hStream, CUcontext* pctx));
ROCCU_DEFINE_FUNC(cuStreamGetCtx_v2, CU_DRIVER, cuStreamGetCtx_v2_ptsz, NOOP, CUresult, (CUstream hStream, CUcontext* pCtx, CUgreenCtx* pGreenCtx));
ROCCU_DEFINE_FUNC(cuStreamGetDevResource, CU_DRIVER, cuStreamGetDevResource_ptsz, NOOP, CUresult, (CUstream hStream, CUdevResource* resource, CUdevResourceType type));
ROCCU_DEFINE_FUNC(cuStreamGetDevice, CU_DRIVER, cuStreamGetDevice_ptsz, NOOP, CUresult, (CUstream hStream, CUdevice* device));
ROCCU_DEFINE_FUNC(cuStreamGetFlags, CU_DRIVER, cuStreamGetFlags_ptsz, NOOP, CUresult, (CUstream hStream, unsigned int* flags));
ROCCU_DEFINE_FUNC(cuStreamGetGreenCtx, CU_DRIVER, cuStreamGetGreenCtx, NOOP, CUresult, (CUstream hStream, CUgreenCtx* phCtx));
ROCCU_DEFINE_FUNC(cuStreamGetId, CU_DRIVER, cuStreamGetId_ptsz, NOOP, CUresult, (CUstream hStream, unsigned long long* streamId));
ROCCU_DEFINE_FUNC(cuStreamGetPriority, CU_DRIVER, cuStreamGetPriority_ptsz, NOOP, CUresult, (CUstream hStream, int* priority));
ROCCU_DEFINE_FUNC(cuStreamIsCapturing, CU_DRIVER, cuStreamIsCapturing_ptsz, NOOP, CUresult, (CUstream hStream, CUstreamCaptureStatus* captureStatus));
ROCCU_DEFINE_FUNC(cuStreamQuery, CU_DRIVER, cuStreamQuery_ptsz, NOOP, CUresult, (CUstream hStream));
ROCCU_DEFINE_FUNC(cuStreamSetAttribute, CU_DRIVER, cuStreamSetAttribute_ptsz, NOOP, CUresult, (CUstream hStream, CUstreamAttrID attr, const CUstreamAttrValue* value));
ROCCU_DEFINE_FUNC(cuStreamSynchronize, CU_DRIVER, cuStreamSynchronize_ptsz, NOOP, CUresult, (CUstream hStream));
ROCCU_DEFINE_FUNC(cuStreamUpdateCaptureDependencies, CU_DRIVER, cuStreamUpdateCaptureDependencies_v2_ptsz, NOOP, CUresult, (CUstream hStream, CUgraphNode* dependencies, const CUgraphEdgeData* dependencyData, size_t numDependencies, unsigned int flags));
ROCCU_DEFINE_FUNC(cuStreamWaitEvent, CU_DRIVER, cuStreamWaitEvent_ptsz, NOOP, CUresult, (CUstream hStream, CUevent hEvent, unsigned int Flags));
ROCCU_DEFINE_FUNC(cuStreamWaitValue32, CU_DRIVER, cuStreamWaitValue32_v2_ptsz, NOOP, CUresult, (CUstream stream, CUdeviceptr addr, cuuint32_t value, unsigned int flags));
ROCCU_DEFINE_FUNC(cuStreamWaitValue64, CU_DRIVER, cuStreamWaitValue64_v2_ptsz, NOOP, CUresult, (CUstream stream, CUdeviceptr addr, cuuint64_t value, unsigned int flags));
ROCCU_DEFINE_FUNC(cuStreamWriteValue32, CU_DRIVER, cuStreamWriteValue32_v2_ptsz, NOOP, CUresult, (CUstream stream, CUdeviceptr addr, cuuint32_t value, unsigned int flags));
ROCCU_DEFINE_FUNC(cuStreamWriteValue64, CU_DRIVER, cuStreamWriteValue64_v2_ptsz, NOOP, CUresult, (CUstream stream, CUdeviceptr addr, cuuint64_t value, unsigned int flags));
ROCCU_DEFINE_FUNC(cuSurfObjectCreate, CU_DRIVER, cuSurfObjectCreate, NOOP, CUresult, (CUsurfObject* pSurfObject, const CUDA_RESOURCE_DESC* pResDesc));
ROCCU_DEFINE_FUNC(cuSurfObjectDestroy, CU_DRIVER, cuSurfObjectDestroy, NOOP, CUresult, (CUsurfObject surfObject));
ROCCU_DEFINE_FUNC(cuSurfObjectGetResourceDesc, CU_DRIVER, cuSurfObjectGetResourceDesc, NOOP, CUresult, (CUDA_RESOURCE_DESC* pResDesc, CUsurfObject surfObject));
ROCCU_DEFINE_FUNC(cuTensorMapEncodeIm2col, CU_DRIVER, cuTensorMapEncodeIm2col, NOOP, CUresult, (CUtensorMap* tensorMap, CUtensorMapDataType tensorDataType, cuuint32_t tensorRank, void* globalAddress, const cuuint64_t* globalDim, const cuuint64_t* globalStrides, const int* pixelBoxLowerCorner, const int* pixelBoxUpperCorner, cuuint32_t channelsPerPixel, cuuint32_t pixelsPerColumn, const cuuint32_t* elementStrides, CUtensorMapInterleave interleave, CUtensorMapSwizzle swizzle, CUtensorMapL2promotion l2Promotion, CUtensorMapFloatOOBfill oobFill));
ROCCU_DEFINE_FUNC(cuTensorMapEncodeIm2colWide, CU_DRIVER, cuTensorMapEncodeIm2colWide, NOOP, CUresult, (CUtensorMap* tensorMap, CUtensorMapDataType tensorDataType, cuuint32_t tensorRank, void* globalAddress, const cuuint64_t* globalDim, const cuuint64_t* globalStrides, int pixelBoxLowerCornerWidth, int pixelBoxUpperCornerWidth, cuuint32_t channelsPerPixel, cuuint32_t pixelsPerColumn, const cuuint32_t* elementStrides, CUtensorMapInterleave interleave, CUtensorMapIm2ColWideMode mode, CUtensorMapSwizzle swizzle, CUtensorMapL2promotion l2Promotion, CUtensorMapFloatOOBfill oobFill));
ROCCU_DEFINE_FUNC(cuTensorMapEncodeTiled, CU_DRIVER, cuTensorMapEncodeTiled, NOOP, CUresult, (CUtensorMap* tensorMap, CUtensorMapDataType tensorDataType, cuuint32_t tensorRank, void* globalAddress, const cuuint64_t* globalDim, const cuuint64_t* globalStrides, const cuuint32_t* boxDim, const cuuint32_t* elementStrides, CUtensorMapInterleave interleave, CUtensorMapSwizzle swizzle, CUtensorMapL2promotion l2Promotion, CUtensorMapFloatOOBfill oobFill));
ROCCU_DEFINE_FUNC(cuTensorMapReplaceAddress, CU_DRIVER, cuTensorMapReplaceAddress, NOOP, CUresult, (CUtensorMap* tensorMap, void* globalAddress));
ROCCU_DEFINE_FUNC(cuTexObjectCreate, CU_DRIVER, cuTexObjectCreate, NOOP, CUresult, (CUtexObject* pTexObject, const CUDA_RESOURCE_DESC* pResDesc, const CUDA_TEXTURE_DESC* pTexDesc, const CUDA_RESOURCE_VIEW_DESC* pResViewDesc));
ROCCU_DEFINE_FUNC(cuTexObjectDestroy, CU_DRIVER, cuTexObjectDestroy, NOOP, CUresult, (CUtexObject texObject));
ROCCU_DEFINE_FUNC(cuTexObjectGetResourceDesc, CU_DRIVER, cuTexObjectGetResourceDesc, NOOP, CUresult, (CUDA_RESOURCE_DESC* pResDesc, CUtexObject texObject));
ROCCU_DEFINE_FUNC(cuTexObjectGetResourceViewDesc, CU_DRIVER, cuTexObjectGetResourceViewDesc, NOOP, CUresult, (CUDA_RESOURCE_VIEW_DESC* pResViewDesc, CUtexObject texObject));
ROCCU_DEFINE_FUNC(cuTexObjectGetTextureDesc, CU_DRIVER, cuTexObjectGetTextureDesc, NOOP, CUresult, (CUDA_TEXTURE_DESC* pTexDesc, CUtexObject texObject));
ROCCU_DEFINE_FUNC(cuThreadExchangeStreamCaptureMode, CU_DRIVER, cuThreadExchangeStreamCaptureMode, NOOP, CUresult, (CUstreamCaptureMode* mode));
ROCCU_DEFINE_FUNC(cuUserObjectCreate, CU_DRIVER, cuUserObjectCreate, NOOP, CUresult, (CUuserObject* object_out, void* ptr, CUhostFn destroy, unsigned int initialRefcount, unsigned int flags));
ROCCU_DEFINE_FUNC(cuUserObjectRelease, CU_DRIVER, cuUserObjectRelease, NOOP, CUresult, (CUuserObject object, unsigned int count));
ROCCU_DEFINE_FUNC(cuUserObjectRetain, CU_DRIVER, cuUserObjectRetain, NOOP, CUresult, (CUuserObject object, unsigned int count));
ROCCU_DEFINE_FUNC(cuWaitExternalSemaphoresAsync, CU_DRIVER, cuWaitExternalSemaphoresAsync_ptsz, NOOP, CUresult, (const CUexternalSemaphore* extSemArray, const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS* paramsArray, unsigned int numExtSems, CUstream stream));
ROCCU_DEFINE_FUNC(nvrtcAddNameExpression, CU_RTC, nvrtcAddNameExpression, NOOP, nvrtcResult, (nvrtcProgram prog, const char* name_expression));
ROCCU_DEFINE_FUNC(nvrtcCompileProgram, CU_RTC, nvrtcCompileProgram, NOOP, nvrtcResult, (nvrtcProgram prog, int numOptions, const char** options));
ROCCU_DEFINE_FUNC(nvrtcCreateProgram, CU_RTC, nvrtcCreateProgram, NOOP, nvrtcResult, (nvrtcProgram* prog, const char* src, const char* name, int numHeaders, const char** headers, const char** includeNames));
ROCCU_DEFINE_FUNC(nvrtcDestroyProgram, CU_RTC, nvrtcDestroyProgram, NOOP, nvrtcResult, (nvrtcProgram* prog));
ROCCU_DEFINE_FUNC(nvrtcGetCUBIN, CU_RTC, nvrtcGetCUBIN, NOOP, nvrtcResult, (nvrtcProgram prog, char* cubin));
ROCCU_DEFINE_FUNC(nvrtcGetCUBINSize, CU_RTC, nvrtcGetCUBINSize, NOOP, nvrtcResult, (nvrtcProgram prog, size_t* cubinSizeRet));
ROCCU_DEFINE_FUNC(nvrtcGetErrorString, CU_RTC, nvrtcGetErrorString, NOOP, const char*, (nvrtcResult result));
ROCCU_DEFINE_FUNC(nvrtcGetLTOIR, CU_RTC, nvrtcGetLTOIR, NOOP, nvrtcResult, (nvrtcProgram prog, char* LTOIR));
ROCCU_DEFINE_FUNC(nvrtcGetLTOIRSize, CU_RTC, nvrtcGetLTOIRSize, NOOP, nvrtcResult, (nvrtcProgram prog, size_t* LTOIRSizeRet));
ROCCU_DEFINE_FUNC(nvrtcGetLoweredName, CU_RTC, nvrtcGetLoweredName, NOOP, nvrtcResult, (nvrtcProgram prog, const char* name_expression, const char** lowered_name));
ROCCU_DEFINE_FUNC(nvrtcGetNumSupportedArchs, CU_RTC, nvrtcGetNumSupportedArchs, NOOP, nvrtcResult, (int* numArchs));
ROCCU_DEFINE_FUNC(nvrtcGetOptiXIR, CU_RTC, nvrtcGetOptiXIR, NOOP, nvrtcResult, (nvrtcProgram prog, char* optixir));
ROCCU_DEFINE_FUNC(nvrtcGetOptiXIRSize, CU_RTC, nvrtcGetOptiXIRSize, NOOP, nvrtcResult, (nvrtcProgram prog, size_t* optixirSizeRet));
ROCCU_DEFINE_FUNC(nvrtcGetPCHCreateStatus, CU_RTC, nvrtcGetPCHCreateStatus, NOOP, nvrtcResult, (nvrtcProgram prog));
ROCCU_DEFINE_FUNC(nvrtcGetPCHHeapSize, CU_RTC, nvrtcGetPCHHeapSize, NOOP, nvrtcResult, (size_t* ret));
ROCCU_DEFINE_FUNC(nvrtcGetPCHHeapSizeRequired, CU_RTC, nvrtcGetPCHHeapSizeRequired, NOOP, nvrtcResult, (nvrtcProgram prog, size_t* size));
ROCCU_DEFINE_FUNC(nvrtcGetPTX, CU_RTC, nvrtcGetPTX, NOOP, nvrtcResult, (nvrtcProgram prog, char* ptx));
ROCCU_DEFINE_FUNC(nvrtcGetPTXSize, CU_RTC, nvrtcGetPTXSize, NOOP, nvrtcResult, (nvrtcProgram prog, size_t* ptxSizeRet));
ROCCU_DEFINE_FUNC(nvrtcGetProgramLog, CU_RTC, nvrtcGetProgramLog, NOOP, nvrtcResult, (nvrtcProgram prog, char* log));
ROCCU_DEFINE_FUNC(nvrtcGetProgramLogSize, CU_RTC, nvrtcGetProgramLogSize, NOOP, nvrtcResult, (nvrtcProgram prog, size_t* logSizeRet));
ROCCU_DEFINE_FUNC(nvrtcGetSupportedArchs, CU_RTC, nvrtcGetSupportedArchs, NOOP, nvrtcResult, (int* supportedArchs));
ROCCU_DEFINE_FUNC(nvrtcSetFlowCallback, CU_RTC, nvrtcSetFlowCallback, NOOP, nvrtcResult, (nvrtcProgram prog, int (*callback)(void*, void*), void* payload));
ROCCU_DEFINE_FUNC(nvrtcSetPCHHeapSize, CU_RTC, nvrtcSetPCHHeapSize, NOOP, nvrtcResult, (size_t size));
ROCCU_DEFINE_FUNC(nvrtcVersion, CU_RTC, nvrtcVersion, NOOP, nvrtcResult, (int* major, int* minor));